# Teldrive web UI dist bundle.
# UI dependencies come from ui/bun.nix (generated by `just update-bun-nix`),
# consumed here via the bun2nix hook + fetchBunDeps. No manual outputHash:
# adding/updating an npm dep only requires regenerating ui/bun.nix.
{ lib, stdenv, bun2nix, bun, nodejs, version }:
stdenv.mkDerivation {
  pname = "teldrive-ui-dist";
  inherit version;
  src = lib.cleanSourceWith {
    src = ../ui;
    filter = path: _type:
      !(builtins.elem (baseNameOf path) [ "node_modules" "dist" "test-results" ]);
  };
  nativeBuildInputs = [ bun2nix.hook bun nodejs ];
  bunDeps = bun2nix.fetchBunDeps {
    bunNix = ../ui/bun.nix;
  };
  buildPhase = ''
    runHook preBuild
    export HOME=$TMPDIR
    bun run build
    runHook postBuild
  '';
  installPhase = ''
    runHook preInstall
    mkdir -p $out
    cp -r dist/. $out/
    runHook postInstall
  '';
}
