//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Sessions struct {
	UserID           int64
	CreatedAt        time.Time
	SessionDate      *int32
	ID               uuid.UUID `sql:"primary_key"`
	TgSession        string
	RefreshTokenHash *string
	UpdatedAt        time.Time
	RevokedAt        *time.Time
}
