//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Users struct {
	UserID    int64 `sql:"primary_key"`
	Name      *string
	UserName  string
	IsPremium bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
