version: 2
project_name: teldrive
env:
  - GO111MODULE=on

before:
  hooks:
    - task ui
    - task gen

builds:
  - env:
      - CGO_ENABLED=0
    main: main.go
    flags: -trimpath
    ldflags:
      - -extldflags=-static
      - -s -w
      - -X {{ .ModulePath }}/internal/version.Version={{ .Version }}
      - -X {{ .ModulePath }}/internal/version.CommitSHA={{ .ShortCommit }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

archives:
  - name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README*.md
      - LICENSE

dockers_v2:
  - images:
      - "ghcr.io/tgdrive/{{ .ProjectName }}"
      - "docker.io/{{ .ProjectName }}/{{ .ProjectName }}"
    tags:
      - "{{ .Tag }}"
      - "latest"
    dockerfile: goreleaser.dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Refactoring
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 3
  filters:
    exclude:
      - '^README'
      - '^Update'
      - '^Version'
      - '^ci:'
      - '^docs:'
      - Merge pull request
      - Merge branch

release:
  draft: true