// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEventStreamTicket = `-- name: CreateEventStreamTicket :exec
INSERT INTO /* TEMPLATE: schema */event_stream_tickets (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateEventStreamTicketParams struct {
	TokenHash []byte             `json:"token_hash"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEventStreamTicket(ctx context.Context, arg CreateEventStreamTicketParams) error {
	_, err := q.db.Exec(ctx, createEventStreamTicket, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredEventStreamTickets = `-- name: DeleteExpiredEventStreamTickets :execrows
DELETE FROM /* TEMPLATE: schema */event_stream_tickets
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredEventStreamTickets(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredEventStreamTickets)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserEventsBefore = `-- name: DeleteUserEventsBefore :execrows
DELETE FROM /* TEMPLATE: schema */user_events
WHERE occurred_at < $1
`

func (q *Queries) DeleteUserEventsBefore(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserEventsBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEventStreamTicketUser = `-- name: GetEventStreamTicketUser :one
SELECT user_id
FROM /* TEMPLATE: schema */event_stream_tickets
WHERE token_hash = $1
  AND expires_at > now()
`

func (q *Queries) GetEventStreamTicketUser(ctx context.Context, tokenHash []byte) (int64, error) {
	row := q.db.QueryRow(ctx, getEventStreamTicketUser, tokenHash)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserEventCursorState = `-- name: GetUserEventCursorState :one
SELECT
    EXISTS (
        SELECT 1
        FROM /* TEMPLATE: schema */user_events AS cursor_event
        WHERE cursor_event.user_id = $1
          AND cursor_event.id = $2
    ) AS cursor_exists,
    COALESCE(MIN(event_rows.id), 0)::bigint AS oldest_id,
    COALESCE(MAX(event_rows.id), 0)::bigint AS newest_id,
    COALESCE((
        SELECT stream_state.last_event_id
        FROM /* TEMPLATE: schema */user_event_stream_state AS stream_state
        WHERE stream_state.user_id = $1
    ), 0)::bigint AS last_event_id
FROM /* TEMPLATE: schema */user_events AS event_rows
WHERE event_rows.user_id = $1
`

type GetUserEventCursorStateParams struct {
	CursorUserID int64 `json:"cursor_user_id"`
	AfterID      int64 `json:"after_id"`
}

type GetUserEventCursorStateRow struct {
	CursorExists bool  `json:"cursor_exists"`
	OldestID     int64 `json:"oldest_id"`
	NewestID     int64 `json:"newest_id"`
	LastEventID  int64 `json:"last_event_id"`
}

func (q *Queries) GetUserEventCursorState(ctx context.Context, arg GetUserEventCursorStateParams) (*GetUserEventCursorStateRow, error) {
	row := q.db.QueryRow(ctx, getUserEventCursorState, arg.CursorUserID, arg.AfterID)
	var i GetUserEventCursorStateRow
	err := row.Scan(
		&i.CursorExists,
		&i.OldestID,
		&i.NewestID,
		&i.LastEventID,
	)
	return &i, err
}

const insertUserEvent = `-- name: InsertUserEvent :one
INSERT INTO /* TEMPLATE: schema */user_events (
    user_id, event_type, resource_type, resource_id, generation, payload
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, user_id, event_type, resource_type, resource_id, generation, payload, occurred_at
`

type InsertUserEventParams struct {
	UserID       int64       `json:"user_id"`
	EventType    string      `json:"event_type"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
	Generation   pgtype.Int8 `json:"generation"`
	Payload      []byte      `json:"payload"`
}

func (q *Queries) InsertUserEvent(ctx context.Context, arg InsertUserEventParams) (*UserEvent, error) {
	row := q.db.QueryRow(ctx, insertUserEvent,
		arg.UserID,
		arg.EventType,
		arg.ResourceType,
		arg.ResourceID,
		arg.Generation,
		arg.Payload,
	)
	var i UserEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.ResourceType,
		&i.ResourceID,
		&i.Generation,
		&i.Payload,
		&i.OccurredAt,
	)
	return &i, err
}

const listUserEventsAfter = `-- name: ListUserEventsAfter :many
SELECT id, user_id, event_type, resource_type, resource_id, generation, payload, occurred_at
FROM /* TEMPLATE: schema */user_events
WHERE user_id = $1
  AND id > $2
  AND (
    COALESCE(cardinality($3::text[]), 0) = 0
    OR event_type = ANY($3::text[])
  )
ORDER BY id
LIMIT $4
`

type ListUserEventsAfterParams struct {
	UserID     int64    `json:"user_id"`
	AfterID    int64    `json:"after_id"`
	EventTypes []string `json:"event_types"`
	EventLimit int32    `json:"event_limit"`
}

func (q *Queries) ListUserEventsAfter(ctx context.Context, arg ListUserEventsAfterParams) ([]*UserEvent, error) {
	rows, err := q.db.Query(ctx, listUserEventsAfter,
		arg.UserID,
		arg.AfterID,
		arg.EventTypes,
		arg.EventLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserEvent{}
	for rows.Next() {
		var i UserEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.ResourceType,
			&i.ResourceID,
			&i.Generation,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
