// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incoming_spam.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dismissIncomingSpam = `-- name: DismissIncomingSpam :exec
WITH revoked AS (
  UPDATE /* TEMPLATE: schema */file_access_grants AS grant_entry
  SET revoked_at = now(), updated_at = now()
  WHERE grant_entry.grantee_id = $1 AND grant_entry.file_id = $2
    AND EXISTS (SELECT 1 FROM /* TEMPLATE: schema */incoming_spam AS spam WHERE spam.grantee_id = $1 AND spam.file_id = $2)
  RETURNING id
)
DELETE FROM /* TEMPLATE: schema */incoming_spam AS spam
WHERE spam.grantee_id = $1 AND spam.file_id = $2
`

type DismissIncomingSpamParams struct {
	GranteeID int64       `json:"grantee_id"`
	FileID    pgtype.UUID `json:"file_id"`
}

func (q *Queries) DismissIncomingSpam(ctx context.Context, arg DismissIncomingSpamParams) error {
	_, err := q.db.Exec(ctx, dismissIncomingSpam, arg.GranteeID, arg.FileID)
	return err
}

const expireIncomingSpam = `-- name: ExpireIncomingSpam :exec
WITH revoked AS (
  UPDATE /* TEMPLATE: schema */file_access_grants g
  SET revoked_at = COALESCE(g.revoked_at, now()), updated_at = now()
  FROM /* TEMPLATE: schema */incoming_spam spam
  WHERE g.grantee_id = spam.grantee_id AND g.file_id = spam.file_id
    AND spam.reported_at <= $1
  RETURNING g.id
)
DELETE FROM /* TEMPLATE: schema */incoming_spam AS spam
WHERE spam.reported_at <= $1
`

func (q *Queries) ExpireIncomingSpam(ctx context.Context, reportedBefore pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, expireIncomingSpam, reportedBefore)
	return err
}

const listIncomingSpam = `-- name: ListIncomingSpam :many
SELECT f.id, f.user_id, f.parent_id, f.name, f.kind, f.mime_type, f.size, f.hash_algorithm, f.hash_value, f.encryption, f.encryption_key_version, f.status, f.mod_time, f.generation, f.created_at, f.updated_at, f.deleted_at, spam.reported_at
FROM /* TEMPLATE: schema */incoming_spam spam
JOIN /* TEMPLATE: schema */files f ON f.id = spam.file_id
WHERE spam.grantee_id = $1
  AND f.status = 'active'
ORDER BY spam.reported_at DESC, f.id
`

type ListIncomingSpamRow struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               int64              `json:"user_id"`
	ParentID             pgtype.UUID        `json:"parent_id"`
	Name                 string             `json:"name"`
	Kind                 FileKind           `json:"kind"`
	MimeType             pgtype.Text        `json:"mime_type"`
	Size                 pgtype.Int8        `json:"size"`
	HashAlgorithm        pgtype.Text        `json:"hash_algorithm"`
	HashValue            pgtype.Text        `json:"hash_value"`
	Encryption           bool               `json:"encryption"`
	EncryptionKeyVersion pgtype.Int4        `json:"encryption_key_version"`
	Status               FileStatus         `json:"status"`
	ModTime              pgtype.Timestamptz `json:"mod_time"`
	Generation           int64              `json:"generation"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	ReportedAt           pgtype.Timestamptz `json:"reported_at"`
}

func (q *Queries) ListIncomingSpam(ctx context.Context, granteeID int64) ([]*ListIncomingSpamRow, error) {
	rows, err := q.db.Query(ctx, listIncomingSpam, granteeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListIncomingSpamRow{}
	for rows.Next() {
		var i ListIncomingSpamRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ReportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIncomingSpam = `-- name: MarkIncomingSpam :execrows
INSERT INTO /* TEMPLATE: schema */incoming_spam (grantee_id, file_id)
SELECT $1, f.id
FROM /* TEMPLATE: schema */files f
WHERE f.id = $2 AND f.status = 'active'
  AND f.user_id <> $1
  AND EXISTS (
    SELECT 1 FROM /* TEMPLATE: schema */file_access_grants g
    WHERE g.file_id = f.id AND g.grantee_id = $1
      AND g.revoked_at IS NULL AND (g.expires_at IS NULL OR g.expires_at > now())
  )
ON CONFLICT (grantee_id, file_id) DO NOTHING
`

type MarkIncomingSpamParams struct {
	GranteeID int64       `json:"grantee_id"`
	FileID    pgtype.UUID `json:"file_id"`
}

func (q *Queries) MarkIncomingSpam(ctx context.Context, arg MarkIncomingSpamParams) (int64, error) {
	result, err := q.db.Exec(ctx, markIncomingSpam, arg.GranteeID, arg.FileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreIncomingSpam = `-- name: RestoreIncomingSpam :execrows
DELETE FROM /* TEMPLATE: schema */incoming_spam AS spam
WHERE spam.grantee_id = $1 AND spam.file_id = $2
`

type RestoreIncomingSpamParams struct {
	GranteeID int64       `json:"grantee_id"`
	FileID    pgtype.UUID `json:"file_id"`
}

func (q *Queries) RestoreIncomingSpam(ctx context.Context, arg RestoreIncomingSpamParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreIncomingSpam, arg.GranteeID, arg.FileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
