import type { PlayerLabels } from "@vplayer/react";

export const spanishPlayerLabels = {
  play: "Reproducir",
  pause: "Pausar",
  replay: "Volver a reproducir",
  mute: "Silenciar",
  unmute: "Activar sonido",
  settings: "Configuración",
  pip: "Imagen en imagen",
  pipExit: "Salir de imagen en imagen",
  miniPlayer: "Reproductor pequeño",
  exitMiniPlayer: "Cerrar reproductor pequeño",
  fullscreen: "Pantalla completa",
  fullscreenExit: "Salir de pantalla completa",
  speed: "Velocidad",
  quality: "Calidad",
  subtitles: "Subtítulos",
  off: "Desactivado",
  loadSubtitleFile: "Cargar archivo de subtítulos",
  findSubtitlesOnline: "Buscar subtítulos en línea",
  subtitleSearch: "Buscar subtítulos",
  subtitleSearchPlaceholder: "Título de la película o serie",
  subtitleSource: "Fuente",
  subtitleAllSources: "Todas las fuentes",
  subtitleLanguage: "Idioma",
  subtitleAllLanguages: "Todos los idiomas",
  subtitleNoResults: "No se encontraron subtítulos",
  subtitleSearching: "Buscando subtítulos…",
  captionAppearance: "Apariencia de subtítulos",
  captionSize: "Tamaño",
  captionTextColor: "Color del texto",
  captionBackgroundColor: "Color del fondo",
  captionBackgroundOpacity: "Opacidad del fondo",
  captionSmall: "Pequeño",
  captionMedium: "Mediano",
  captionLarge: "Grande",
  captionFontFamily: "Tipografía",
  captionFontScale: "Escala del texto",
  captionTextOpacity: "Opacidad del texto",
  captionEdgeStyle: "Borde del texto",
  captionEdgeNone: "Sin borde",
  captionEdgeShadow: "Sombra",
  captionEdgeOutline: "Contorno",
  captionEdgeColor: "Color del borde",
  captionPosition: "Posición",
  captionLineHeight: "Espaciado entre líneas",
  captionDelay: "Retraso de subtítulos",
  captionPreview: "Vista previa de subtítulos",
  captionReset: "Restablecer",
  captionSave: "Guardar",
  captionSaved: "Guardado",
  subtitleLoadError: "No se pudieron cargar los subtítulos",
  endedTitle: "Reproducción finalizada",
  screenshot: "Capturar imagen",
  flip: "Voltear imagen",
  flipNormal: "Sin voltear",
  flipHorizontal: "Voltear horizontalmente",
  flipVertical: "Voltear verticalmente",
  aspectRatio: "Proporción de la imagen",
  aspectRatioDefault: "Original",
  aspectRatio16: "16:9",
  aspectRatio4: "4:3",
  aspectRatioFill: "Ajustar",
  aspectRatioCover: "Llenar",
  aspectRatio21: "21:9",
  continue: "Continuar reproducción",
  continuePlay: "Continuar",
  continueStartOver: "Reproducir desde el principio",
  dismiss: "Cerrar",
  error: "No se pudo reproducir el archivo",
  retry: "Volver a intentar",
  contextMenuPlay: "Reproducir",
  contextMenuPause: "Pausar",
  contextMenuLoop: "Repetir",
  infoPanel: "Información multimedia",
  loop: "Repetir",
} satisfies PlayerLabels;
