emit:
  - "teldrive-ogen-openapi3"

options:
  "teldrive-ogen-openapi3":
    emitter-output-dir: "{project-root}/../openapi"
    output-file: "teldrive.openapi.yaml"
    file-type: yaml
    openapi-versions:
      - 3.0.0
    operation-id-strategy: explicit-only
    omit-unreachable-types: true
    safeint-strategy: int64

warn-as-error: true
