/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ShareRouteImport } from "./routes/_share"
import { Route as AuthedRouteImport } from "./routes/_authed"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as AuthedIndexRouteImport } from "./routes/_authed/index"
import { Route as AuthedStorageRouteImport } from "./routes/_authed/storage"
import { Route as AuthedSettingsRouteImport } from "./routes/_authed/settings"
import { Route as AuthedViewRouteImport } from "./routes/_authed/$view"
import { Route as AuthLoginRouteImport } from "./routes/_auth/login"
import { Route as ShareShareIdRouteImport } from "./routes/_share/share.$id"
import { Route as AuthedSettingsTabIdRouteImport } from "./routes/_authed/settings.$tabId"

const ShareRoute = ShareRouteImport.update({
  id: "/_share",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStorageRoute = AuthedStorageRouteImport.update({
  id: "/storage",
  path: "/storage",
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import("./routes/_authed/storage.lazy").then((d) => d.Route),
)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedViewRoute = AuthedViewRouteImport.update({
  id: "/$view",
  path: "/$view",
  getParentRoute: () => AuthedRoute,
} as any).lazy(() => import("./routes/_authed/$view.lazy").then((d) => d.Route))
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import("./routes/_auth/login.lazy").then((d) => d.Route))
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: "/share/$id",
  path: "/share/$id",
  getParentRoute: () => ShareRoute,
} as any).lazy(() =>
  import("./routes/_share/share.$id.lazy").then((d) => d.Route),
)
const AuthedSettingsTabIdRoute = AuthedSettingsTabIdRouteImport.update({
  id: "/$tabId",
  path: "/$tabId",
  getParentRoute: () => AuthedSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  "/login": typeof AuthLoginRoute
  "/$view": typeof AuthedViewRoute
  "/settings": typeof AuthedSettingsRouteWithChildren
  "/storage": typeof AuthedStorageRoute
  "/": typeof AuthedIndexRoute
  "/settings/$tabId": typeof AuthedSettingsTabIdRoute
  "/share/$id": typeof ShareShareIdRoute
}
export interface FileRoutesByTo {
  "/login": typeof AuthLoginRoute
  "/$view": typeof AuthedViewRoute
  "/settings": typeof AuthedSettingsRouteWithChildren
  "/storage": typeof AuthedStorageRoute
  "/": typeof AuthedIndexRoute
  "/settings/$tabId": typeof AuthedSettingsTabIdRoute
  "/share/$id": typeof ShareShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_auth": typeof AuthRouteWithChildren
  "/_authed": typeof AuthedRouteWithChildren
  "/_share": typeof ShareRouteWithChildren
  "/_auth/login": typeof AuthLoginRoute
  "/_authed/$view": typeof AuthedViewRoute
  "/_authed/settings": typeof AuthedSettingsRouteWithChildren
  "/_authed/storage": typeof AuthedStorageRoute
  "/_authed/": typeof AuthedIndexRoute
  "/_authed/settings/$tabId": typeof AuthedSettingsTabIdRoute
  "/_share/share/$id": typeof ShareShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/login"
    | "/$view"
    | "/settings"
    | "/storage"
    | "/"
    | "/settings/$tabId"
    | "/share/$id"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/login"
    | "/$view"
    | "/settings"
    | "/storage"
    | "/"
    | "/settings/$tabId"
    | "/share/$id"
  id:
    | "__root__"
    | "/_auth"
    | "/_authed"
    | "/_share"
    | "/_auth/login"
    | "/_authed/$view"
    | "/_authed/settings"
    | "/_authed/storage"
    | "/_authed/"
    | "/_authed/settings/$tabId"
    | "/_share/share/$id"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
  ShareRoute: typeof ShareRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_share": {
      id: "/_share"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed": {
      id: "/_authed"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed/": {
      id: "/_authed/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/storage": {
      id: "/_authed/storage"
      path: "/storage"
      fullPath: "/storage"
      preLoaderRoute: typeof AuthedStorageRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/settings": {
      id: "/_authed/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/$view": {
      id: "/_authed/$view"
      path: "/$view"
      fullPath: "/$view"
      preLoaderRoute: typeof AuthedViewRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_share/share/$id": {
      id: "/_share/share/$id"
      path: "/share/$id"
      fullPath: "/share/$id"
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof ShareRoute
    }
    "/_authed/settings/$tabId": {
      id: "/_authed/settings/$tabId"
      path: "/$tabId"
      fullPath: "/settings/$tabId"
      preLoaderRoute: typeof AuthedSettingsTabIdRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthedSettingsRouteChildren {
  AuthedSettingsTabIdRoute: typeof AuthedSettingsTabIdRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsTabIdRoute: AuthedSettingsTabIdRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedViewRoute: typeof AuthedViewRoute
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedStorageRoute: typeof AuthedStorageRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedViewRoute: AuthedViewRoute,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedStorageRoute: AuthedStorageRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ShareRouteChildren {
  ShareShareIdRoute: typeof ShareShareIdRoute
}

const ShareRouteChildren: ShareRouteChildren = {
  ShareShareIdRoute: ShareShareIdRoute,
}

const ShareRouteWithChildren = ShareRoute._addFileChildren(ShareRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
  ShareRoute: ShareRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
