// Command nixconfig generates the Nix module options for Teldrive settings
// from the Go configuration structs, so `nix/modules` stays in sync with
// internal/config. Run via `just nix-generate`.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"time"

	"github.com/tgdrive/teldrive/v2/internal/config"
	"github.com/tgdrive/teldrive/v2/internal/size"
)

var (
	durationType = reflect.TypeFor[time.Duration]()
	sizeType     = reflect.TypeFor[size.Size]()
)

// nixEscape renders s as a double-quoted Nix string literal.
func nixEscape(s string) string {
	var b strings.Builder
	b.WriteString("\"")
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString("\\\\")
		case '"':
			b.WriteString("\\\"")
		case '$':
			b.WriteString("\\$")
		default:
			b.WriteRune(r)
		}
	}
	b.WriteString("\"")
	return b.String()
}

func isNested(t reflect.Type) bool {
	return t.Kind() == reflect.Struct && t != durationType && t != sizeType
}

// nixType maps a Go leaf type to a Nix types expression (without nullOr).
func nixType(t reflect.Type, path string) string {
	if t == durationType || t == sizeType {
		// Durations ("10s") and sizes ("5MB") are strings on the wire.
		return "lib.types.str"
	}
	switch t.Kind() {
	case reflect.String:
		return "lib.types.str"
	case reflect.Bool:
		return "lib.types.bool"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return "lib.types.int"
	case reflect.Slice:
		if t.Elem().Kind() != reflect.String {
			panic(fmt.Sprintf("nixconfig: unsupported slice element at %s: %s", path, t.Elem().Kind()))
		}
		return "lib.types.listOf lib.types.str"
	case reflect.Map:
		if t.Elem().Kind() != reflect.String {
			panic(fmt.Sprintf("nixconfig: unsupported map value at %s: %s", path, t.Elem().Kind()))
		}
		return "lib.types.attrsOf lib.types.str"
	default:
		panic(fmt.Sprintf("nixconfig: unsupported type at %s: %s", path, t))
	}
}

func descriptionFor(f reflect.StructField) string {
	desc := f.Tag.Get("description")
	def := f.Tag.Get("default")
	if desc == "" {
		desc = "Teldrive setting."
	}
	if def != "" {
		desc += " (Default: " + def + ")"
	} else {
		desc += " (No default; upstream applies its own.)"
	}
	if v := f.Tag.Get("validate"); v != "" {
		desc += " [validate: " + v + "]"
	}
	return desc
}

func emitOptions(b *strings.Builder, t reflect.Type, path string, indent int, leafMaps *[]string) {
	pad := strings.Repeat("  ", indent)
	for i := range t.NumField() {
		f := t.Field(i)
		key, ok := f.Tag.Lookup("koanf")
		if !ok || key == "" || key == "-" {
			continue
		}
		childPath := key
		if path != "" {
			childPath = path + "." + key
		}
		if isNested(f.Type) {
			fmt.Fprintf(b, "%s%s = {\n", pad, nixEscape(key))
			emitOptions(b, f.Type, childPath, indent+1, leafMaps)
			fmt.Fprintf(b, "%s};\n", pad)
			continue
		}
		if f.Type.Kind() == reflect.Map {
			*leafMaps = append(*leafMaps, childPath)
		}
		fmt.Fprintf(b, "%s%s = lib.mkOption {\n", pad, nixEscape(key))
		fmt.Fprintf(b, "%s  type = lib.types.nullOr (%s);\n", pad, nixType(f.Type, childPath))
		fmt.Fprintf(b, "%s  default = null;\n", pad)
		fmt.Fprintf(b, "%s  description = %s;\n", pad, nixEscape(descriptionFor(f)))
		fmt.Fprintf(b, "%s};\n", pad)
	}
}

func main() {
	var b strings.Builder
	b.WriteString("# GENERATED by `just nix-generate` (internal/tools/nixconfig). Do not edit.\n")
	b.WriteString("# Option schema for services.teldrive.settings, derived from internal/config.\n")
	b.WriteString("# Every leaf defaults to null so only explicitly set values reach the\n")
	b.WriteString("# daemon environment; Teldrive applies its own defaults otherwise.\n")
	b.WriteString("{ lib, ... }:\n{\n")
	var leafMaps []string
	emitOptions(&b, reflect.TypeFor[config.Config](), "", 1, &leafMaps)
	b.WriteString("}\n")

	out := filepath.Join("nix", "modules", "generated-options.nix")
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("generated %s\n", out)

	var m strings.Builder
	m.WriteString("# GENERATED by `just nix-generate` (internal/tools/nixconfig). Do not edit.\n")
	m.WriteString("# Dotted settings paths that are leaf maps (rendered as comma-joined key:value pairs).\n")
	m.WriteString("[\n")
	for _, p := range leafMaps {
		fmt.Fprintf(&m, "  %s\n", nixEscape(p))
	}
	m.WriteString("]\n")
	mapsOut := filepath.Join("nix", "modules", "generated-leaf-maps.nix")
	if err := os.WriteFile(mapsOut, []byte(m.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("generated %s (%d leaf maps)\n", mapsOut, len(leafMaps))
}
