// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO /* TEMPLATE: schema */audit_events (
    id,
    user_id,
    action,
    resource_type,
    resource_id,
    metadata,
    request_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, user_id, action, resource_type, resource_id, metadata, request_id, created_at
`

type InsertAuditEventParams struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.Int8 `json:"user_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.Text `json:"resource_id"`
	Metadata     []byte      `json:"metadata"`
	RequestID    pgtype.Text `json:"request_id"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (*AuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
		arg.RequestID,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Metadata,
		&i.RequestID,
		&i.CreatedAt,
	)
	return &i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, user_id, action, resource_type, resource_id, metadata, request_id, created_at
FROM /* TEMPLATE: schema */audit_events
WHERE user_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < (
      $2::timestamptz,
      $3::uuid
    )
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAuditEventsParams struct {
	UserID         pgtype.Int8        `json:"user_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	PageSize       int32              `json:"page_size"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]*AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
