// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeTelegramLoginFlow = `-- name: CompleteTelegramLoginFlow :one
UPDATE /* TEMPLATE: schema */telegram_login_flows
SET completed_at = now()
WHERE id = $1
  AND completed_at IS NULL
RETURNING id, method, phone_number_ciphertext, telegram_state_ciphertext, password_required, expires_at, completed_at, created_at
`

func (q *Queries) CompleteTelegramLoginFlow(ctx context.Context, id pgtype.UUID) (*TelegramLoginFlow, error) {
	row := q.db.QueryRow(ctx, completeTelegramLoginFlow, id)
	var i TelegramLoginFlow
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.PhoneNumberCiphertext,
		&i.TelegramStateCiphertext,
		&i.PasswordRequired,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO /* TEMPLATE: schema */api_keys (
    id,
    user_id,
    name,
    key_prefix,
    secret_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, user_id, name, key_prefix, secret_hash, last_used_at, expires_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	SecretHash []byte             `json:"secret_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (*ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.KeyPrefix,
		arg.SecretHash,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.SecretHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO /* TEMPLATE: schema */sessions (
    id,
    user_id,
    telegram_session,
    refresh_token_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, telegram_session, refresh_token_hash, expires_at, last_used_at, revoked_at, created_at
`

type CreateSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           int64              `json:"user_id"`
	TelegramSession  []byte             `json:"telegram_session"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (*Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TelegramSession,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TelegramSession,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const createTelegramLoginFlow = `-- name: CreateTelegramLoginFlow :one
INSERT INTO /* TEMPLATE: schema */telegram_login_flows (
    id,
    method,
    phone_number_ciphertext,
    telegram_state_ciphertext,
    password_required,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, method, phone_number_ciphertext, telegram_state_ciphertext, password_required, expires_at, completed_at, created_at
`

type CreateTelegramLoginFlowParams struct {
	ID                      pgtype.UUID         `json:"id"`
	Method                  TelegramLoginMethod `json:"method"`
	PhoneNumberCiphertext   []byte              `json:"phone_number_ciphertext"`
	TelegramStateCiphertext []byte              `json:"telegram_state_ciphertext"`
	PasswordRequired        bool                `json:"password_required"`
	ExpiresAt               pgtype.Timestamptz  `json:"expires_at"`
}

func (q *Queries) CreateTelegramLoginFlow(ctx context.Context, arg CreateTelegramLoginFlowParams) (*TelegramLoginFlow, error) {
	row := q.db.QueryRow(ctx, createTelegramLoginFlow,
		arg.ID,
		arg.Method,
		arg.PhoneNumberCiphertext,
		arg.TelegramStateCiphertext,
		arg.PasswordRequired,
		arg.ExpiresAt,
	)
	var i TelegramLoginFlow
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.PhoneNumberCiphertext,
		&i.TelegramStateCiphertext,
		&i.PasswordRequired,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteExpiredTelegramLoginFlows = `-- name: DeleteExpiredTelegramLoginFlows :execrows
DELETE FROM /* TEMPLATE: schema */telegram_login_flows
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredTelegramLoginFlows(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredTelegramLoginFlows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveAPIKeyByHash = `-- name: GetActiveAPIKeyByHash :one
SELECT id, user_id, name, key_prefix, secret_hash, last_used_at, expires_at, revoked_at, created_at
FROM /* TEMPLATE: schema */api_keys
WHERE secret_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetActiveAPIKeyByHash(ctx context.Context, secretHash []byte) (*ApiKey, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKeyByHash, secretHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.SecretHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, user_id, telegram_session, refresh_token_hash, expires_at, last_used_at, revoked_at, created_at
FROM /* TEMPLATE: schema */sessions
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
  AND expires_at > now()
`

type GetActiveSessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	UserID    int64       `json:"user_id"`
}

func (q *Queries) GetActiveSession(ctx context.Context, arg GetActiveSessionParams) (*Session, error) {
	row := q.db.QueryRow(ctx, getActiveSession, arg.SessionID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TelegramSession,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getLatestActiveSessionForUser = `-- name: GetLatestActiveSessionForUser :one
SELECT id, user_id, telegram_session, refresh_token_hash, expires_at, last_used_at, revoked_at, created_at
FROM /* TEMPLATE: schema */sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY last_used_at DESC NULLS LAST, created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestActiveSessionForUser(ctx context.Context, userID int64) (*Session, error) {
	row := q.db.QueryRow(ctx, getLatestActiveSessionForUser, userID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TelegramSession,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, user_id, telegram_session, refresh_token_hash, expires_at, last_used_at, revoked_at, created_at
FROM /* TEMPLATE: schema */sessions
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash []byte) (*Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TelegramSession,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getTelegramLoginFlow = `-- name: GetTelegramLoginFlow :one
SELECT id, method, phone_number_ciphertext, telegram_state_ciphertext, password_required, expires_at, completed_at, created_at
FROM /* TEMPLATE: schema */telegram_login_flows
WHERE id = $1
  AND completed_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetTelegramLoginFlow(ctx context.Context, id pgtype.UUID) (*TelegramLoginFlow, error) {
	row := q.db.QueryRow(ctx, getTelegramLoginFlow, id)
	var i TelegramLoginFlow
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.PhoneNumberCiphertext,
		&i.TelegramStateCiphertext,
		&i.PasswordRequired,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getTelegramLoginFlowForUpdate = `-- name: GetTelegramLoginFlowForUpdate :one
SELECT id, method, phone_number_ciphertext, telegram_state_ciphertext, password_required, expires_at, completed_at, created_at
FROM /* TEMPLATE: schema */telegram_login_flows
WHERE id = $1
  AND completed_at IS NULL
  AND expires_at > now()
FOR UPDATE
`

func (q *Queries) GetTelegramLoginFlowForUpdate(ctx context.Context, id pgtype.UUID) (*TelegramLoginFlow, error) {
	row := q.db.QueryRow(ctx, getTelegramLoginFlowForUpdate, id)
	var i TelegramLoginFlow
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.PhoneNumberCiphertext,
		&i.TelegramStateCiphertext,
		&i.PasswordRequired,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getUser = `-- name: GetUser :one
SELECT user_id, display_name, username, premium, created_at, updated_at
FROM /* TEMPLATE: schema */users
WHERE user_id = $1
`

func (q *Queries) GetUser(ctx context.Context, userID int64) (*User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Username,
		&i.Premium,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, user_id, name, key_prefix, secret_hash, last_used_at, expires_at, revoked_at, created_at
FROM /* TEMPLATE: schema */api_keys
WHERE user_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < (
      $2::timestamptz,
      $3::uuid
    )
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAPIKeysParams struct {
	UserID         int64              `json:"user_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	PageSize       int32              `json:"page_size"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]*ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyPrefix,
			&i.SecretHash,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, user_id, telegram_session, refresh_token_hash, expires_at, last_used_at, revoked_at, created_at
FROM /* TEMPLATE: schema */sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < (
      $2::timestamptz,
      $3::uuid
    )
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListSessionsParams struct {
	UserID         int64              `json:"user_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	PageSize       int32              `json:"page_size"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]*Session, error) {
	rows, err := q.db.Query(ctx, listSessions,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TelegramSession,
			&i.RefreshTokenHash,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE /* TEMPLATE: schema */api_keys
SET revoked_at = now()
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE /* TEMPLATE: schema */sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1
  AND user_id = $2
`

type RevokeSessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	UserID    int64       `json:"user_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.SessionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateSessionRefreshToken = `-- name: RotateSessionRefreshToken :one
UPDATE /* TEMPLATE: schema */sessions
SET refresh_token_hash = $1,
    last_used_at = now()
WHERE id = $2
  AND refresh_token_hash = $3
  AND revoked_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, telegram_session, refresh_token_hash, expires_at, last_used_at, revoked_at, created_at
`

type RotateSessionRefreshTokenParams struct {
	NewRefreshTokenHash []byte      `json:"new_refresh_token_hash"`
	SessionID           pgtype.UUID `json:"session_id"`
	OldRefreshTokenHash []byte      `json:"old_refresh_token_hash"`
}

func (q *Queries) RotateSessionRefreshToken(ctx context.Context, arg RotateSessionRefreshTokenParams) (*Session, error) {
	row := q.db.QueryRow(ctx, rotateSessionRefreshToken, arg.NewRefreshTokenHash, arg.SessionID, arg.OldRefreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TelegramSession,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE /* TEMPLATE: schema */api_keys
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE /* TEMPLATE: schema */sessions
SET last_used_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, sessionID)
	return err
}

const updateSessionTelegramSession = `-- name: UpdateSessionTelegramSession :execrows
UPDATE /* TEMPLATE: schema */sessions
SET telegram_session = $1,
    last_used_at = now()
WHERE id = $2
  AND revoked_at IS NULL
  AND expires_at > now()
`

type UpdateSessionTelegramSessionParams struct {
	TelegramSession []byte      `json:"telegram_session"`
	SessionID       pgtype.UUID `json:"session_id"`
}

func (q *Queries) UpdateSessionTelegramSession(ctx context.Context, arg UpdateSessionTelegramSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSessionTelegramSession, arg.TelegramSession, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTelegramLoginFlowState = `-- name: UpdateTelegramLoginFlowState :one
UPDATE /* TEMPLATE: schema */telegram_login_flows
SET telegram_state_ciphertext = $1,
    password_required = $2
WHERE id = $3
  AND completed_at IS NULL
  AND expires_at > now()
RETURNING id, method, phone_number_ciphertext, telegram_state_ciphertext, password_required, expires_at, completed_at, created_at
`

type UpdateTelegramLoginFlowStateParams struct {
	TelegramStateCiphertext []byte      `json:"telegram_state_ciphertext"`
	PasswordRequired        bool        `json:"password_required"`
	ID                      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTelegramLoginFlowState(ctx context.Context, arg UpdateTelegramLoginFlowStateParams) (*TelegramLoginFlow, error) {
	row := q.db.QueryRow(ctx, updateTelegramLoginFlowState, arg.TelegramStateCiphertext, arg.PasswordRequired, arg.ID)
	var i TelegramLoginFlow
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.PhoneNumberCiphertext,
		&i.TelegramStateCiphertext,
		&i.PasswordRequired,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO /* TEMPLATE: schema */users (
    user_id,
    display_name,
    username,
    premium
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (user_id) DO UPDATE
SET display_name = EXCLUDED.display_name,
    username = EXCLUDED.username,
    premium = EXCLUDED.premium,
    updated_at = now()
RETURNING user_id, display_name, username, premium, created_at, updated_at
`

type UpsertUserParams struct {
	UserID      int64       `json:"user_id"`
	DisplayName pgtype.Text `json:"display_name"`
	Username    pgtype.Text `json:"username"`
	Premium     bool        `json:"premium"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.UserID,
		arg.DisplayName,
		arg.Username,
		arg.Premium,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Username,
		&i.Premium,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
