// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearUploadSessionParentsByFileIDs = `-- name: ClearUploadSessionParentsByFileIDs :exec
UPDATE /* TEMPLATE: schema */upload_sessions
SET parent_id = NULL,
    updated_at = now()
WHERE user_id = $1
  AND parent_id = ANY($2::uuid[])
`

type ClearUploadSessionParentsByFileIDsParams struct {
	UserID  int64         `json:"user_id"`
	FileIds []pgtype.UUID `json:"file_ids"`
}

func (q *Queries) ClearUploadSessionParentsByFileIDs(ctx context.Context, arg ClearUploadSessionParentsByFileIDsParams) error {
	_, err := q.db.Exec(ctx, clearUploadSessionParentsByFileIDs, arg.UserID, arg.FileIds)
	return err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO /* TEMPLATE: schema */files (
    id,
    user_id,
    parent_id,
    name,
    normalized_name,
    kind,
    mime_type,
    size,
    encryption,
    status,
    mod_time
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'folder',
    'inode/directory',
    NULL,
    false,
    'active',
    $6
)
RETURNING id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
`

type CreateFolderParams struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         int64              `json:"user_id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	ModTime        pgtype.Timestamptz `json:"mod_time"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (*File, error) {
	row := q.db.QueryRow(ctx, createFolder,
		arg.ID,
		arg.UserID,
		arg.ParentID,
		arg.Name,
		arg.NormalizedName,
		arg.ModTime,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const deleteFileCatalogRow = `-- name: DeleteFileCatalogRow :execrows
DELETE FROM /* TEMPLATE: schema */files
WHERE id = $1
  AND user_id = $2
  AND status = 'deletion_pending'
`

type DeleteFileCatalogRowParams struct {
	FileID pgtype.UUID `json:"file_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) DeleteFileCatalogRow(ctx context.Context, arg DeleteFileCatalogRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFileCatalogRow, arg.FileID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFilePartsByFileIDs = `-- name: DeleteFilePartsByFileIDs :exec
DELETE FROM /* TEMPLATE: schema */file_parts
WHERE file_id = ANY($1::uuid[])
`

func (q *Queries) DeleteFilePartsByFileIDs(ctx context.Context, fileIds []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFilePartsByFileIDs, fileIds)
	return err
}

const getActiveFolderForUser = `-- name: GetActiveFolderForUser :one
SELECT id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
FROM /* TEMPLATE: schema */files
WHERE id = $1
  AND user_id = $2
  AND kind = 'folder'
  AND status = 'active'
`

type GetActiveFolderForUserParams struct {
	FolderID pgtype.UUID `json:"folder_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) GetActiveFolderForUser(ctx context.Context, arg GetActiveFolderForUserParams) (*File, error) {
	row := q.db.QueryRow(ctx, getActiveFolderForUser, arg.FolderID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getDriveStatistics = `-- name: GetDriveStatistics :one
SELECT
  count(*) FILTER (WHERE kind = 'file' AND status = 'active')::bigint AS total_files,
  count(*) FILTER (WHERE kind = 'folder' AND status = 'active')::bigint AS total_folders,
  COALESCE(sum(size) FILTER (WHERE kind = 'file' AND status = 'active'), 0)::bigint AS total_bytes,
  count(*) FILTER (WHERE status = 'trashed')::bigint AS trashed_files,
  (SELECT count(*)::bigint FROM /* TEMPLATE: schema */file_shares WHERE owner_id = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())) AS active_shares,
  (SELECT count(*)::bigint FROM /* TEMPLATE: schema */upload_sessions WHERE user_id = $1 AND state IN ('open', 'completing')) AS open_uploads
FROM /* TEMPLATE: schema */files
WHERE user_id = $1
`

type GetDriveStatisticsRow struct {
	TotalFiles   int64 `json:"total_files"`
	TotalFolders int64 `json:"total_folders"`
	TotalBytes   int64 `json:"total_bytes"`
	TrashedFiles int64 `json:"trashed_files"`
	ActiveShares int64 `json:"active_shares"`
	OpenUploads  int64 `json:"open_uploads"`
}

func (q *Queries) GetDriveStatistics(ctx context.Context, userID int64) (*GetDriveStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getDriveStatistics, userID)
	var i GetDriveStatisticsRow
	err := row.Scan(
		&i.TotalFiles,
		&i.TotalFolders,
		&i.TotalBytes,
		&i.TrashedFiles,
		&i.ActiveShares,
		&i.OpenUploads,
	)
	return &i, err
}

const getFileForUser = `-- name: GetFileForUser :one
SELECT id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
FROM /* TEMPLATE: schema */files
WHERE id = $1
  AND user_id = $2
`

type GetFileForUserParams struct {
	FileID pgtype.UUID `json:"file_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) GetFileForUser(ctx context.Context, arg GetFileForUserParams) (*File, error) {
	row := q.db.QueryRow(ctx, getFileForUser, arg.FileID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const insertCopiedFile = `-- name: InsertCopiedFile :exec
INSERT INTO /* TEMPLATE: schema */files (
    id, user_id, parent_id, name, normalized_name, kind, mime_type, size,
    hash_algorithm, hash_value, encryption, encryption_key_version,
    status, mod_time, generation
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12,
    'active', $13, 1
)
`

type InsertCopiedFileParams struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               int64              `json:"user_id"`
	ParentID             pgtype.UUID        `json:"parent_id"`
	Name                 string             `json:"name"`
	NormalizedName       string             `json:"normalized_name"`
	Kind                 FileKind           `json:"kind"`
	MimeType             pgtype.Text        `json:"mime_type"`
	Size                 pgtype.Int8        `json:"size"`
	HashAlgorithm        pgtype.Text        `json:"hash_algorithm"`
	HashValue            pgtype.Text        `json:"hash_value"`
	Encryption           bool               `json:"encryption"`
	EncryptionKeyVersion pgtype.Int4        `json:"encryption_key_version"`
	ModTime              pgtype.Timestamptz `json:"mod_time"`
}

func (q *Queries) InsertCopiedFile(ctx context.Context, arg InsertCopiedFileParams) error {
	_, err := q.db.Exec(ctx, insertCopiedFile,
		arg.ID,
		arg.UserID,
		arg.ParentID,
		arg.Name,
		arg.NormalizedName,
		arg.Kind,
		arg.MimeType,
		arg.Size,
		arg.HashAlgorithm,
		arg.HashValue,
		arg.Encryption,
		arg.EncryptionKeyVersion,
		arg.ModTime,
	)
	return err
}

const insertCopiedFilePart = `-- name: InsertCopiedFilePart :exec
INSERT INTO /* TEMPLATE: schema */file_parts (
    file_id, part_no, channel_id, message_id, plain_size, stored_size,
    checksum, salt, block_hashes
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9
)
`

type InsertCopiedFilePartParams struct {
	FileID      pgtype.UUID `json:"file_id"`
	PartNo      int32       `json:"part_no"`
	ChannelID   int64       `json:"channel_id"`
	MessageID   int64       `json:"message_id"`
	PlainSize   pgtype.Int8 `json:"plain_size"`
	StoredSize  pgtype.Int8 `json:"stored_size"`
	Checksum    pgtype.Text `json:"checksum"`
	Salt        pgtype.Text `json:"salt"`
	BlockHashes []byte      `json:"block_hashes"`
}

func (q *Queries) InsertCopiedFilePart(ctx context.Context, arg InsertCopiedFilePartParams) error {
	_, err := q.db.Exec(ctx, insertCopiedFilePart,
		arg.FileID,
		arg.PartNo,
		arg.ChannelID,
		arg.MessageID,
		arg.PlainSize,
		arg.StoredSize,
		arg.Checksum,
		arg.Salt,
		arg.BlockHashes,
	)
	return err
}

const listActiveNormalizedNames = `-- name: ListActiveNormalizedNames :many
SELECT normalized_name
FROM /* TEMPLATE: schema */files
WHERE user_id = $1
  AND parent_id IS NOT DISTINCT FROM $2::uuid
  AND status = 'active'
  AND ($3::uuid IS NULL OR id <> $3::uuid)
`

type ListActiveNormalizedNamesParams struct {
	UserID    int64       `json:"user_id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	ExcludeID pgtype.UUID `json:"exclude_id"`
}

func (q *Queries) ListActiveNormalizedNames(ctx context.Context, arg ListActiveNormalizedNamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveNormalizedNames, arg.UserID, arg.ParentID, arg.ExcludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var normalized_name string
		if err := rows.Scan(&normalized_name); err != nil {
			return nil, err
		}
		items = append(items, normalized_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileCategoryStatistics = `-- name: ListFileCategoryStatistics :many
SELECT category, count(*)::bigint AS total_files, COALESCE(sum(size), 0)::bigint AS total_size
FROM (
  SELECT CASE
    WHEN lower(COALESCE(f.mime_type, '')) LIKE 'image/%' THEN 'image'
    WHEN lower(COALESCE(f.mime_type, '')) LIKE 'audio/%' THEN 'audio'
    WHEN lower(COALESCE(f.mime_type, '')) LIKE 'video/%' THEN 'video'
    WHEN lower(COALESCE(f.mime_type, '')) LIKE 'text/%'
      OR lower(COALESCE(f.mime_type, '')) IN (
        'application/pdf', 'application/json', 'application/xml',
        'application/msword', 'application/rtf',
        'application/vnd.ms-excel', 'application/vnd.ms-powerpoint',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation'
      ) THEN 'document'
    WHEN lower(COALESCE(f.mime_type, '')) IN (
        'application/zip', 'application/x-rar-compressed', 'application/x-7z-compressed',
        'application/x-tar', 'application/gzip', 'application/x-bzip2', 'application/x-xz'
      ) OR lower(f.name) ~ '\.(zip|rar|7z|tar|gz|tgz|bz2|xz)$' THEN 'archive'
    ELSE 'other'
  END AS category, f.size
  FROM /* TEMPLATE: schema */files f
  WHERE f.user_id = $1
    AND f.kind = 'file'
    AND f.status = 'active'
) categorized
GROUP BY category
ORDER BY category
`

type ListFileCategoryStatisticsRow struct {
	Category   string `json:"category"`
	TotalFiles int64  `json:"total_files"`
	TotalSize  int64  `json:"total_size"`
}

func (q *Queries) ListFileCategoryStatistics(ctx context.Context, userID int64) ([]*ListFileCategoryStatisticsRow, error) {
	rows, err := q.db.Query(ctx, listFileCategoryStatistics, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListFileCategoryStatisticsRow{}
	for rows.Next() {
		var i ListFileCategoryStatisticsRow
		if err := rows.Scan(&i.Category, &i.TotalFiles, &i.TotalSize); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilePartMessageRefs = `-- name: ListFilePartMessageRefs :many
SELECT channel_id, message_id
FROM /* TEMPLATE: schema */file_parts
WHERE file_id = ANY($1::uuid[])
ORDER BY channel_id, message_id
`

type ListFilePartMessageRefsRow struct {
	ChannelID int64 `json:"channel_id"`
	MessageID int64 `json:"message_id"`
}

func (q *Queries) ListFilePartMessageRefs(ctx context.Context, fileIds []pgtype.UUID) ([]*ListFilePartMessageRefsRow, error) {
	rows, err := q.db.Query(ctx, listFilePartMessageRefs, fileIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListFilePartMessageRefsRow{}
	for rows.Next() {
		var i ListFilePartMessageRefsRow
		if err := rows.Scan(&i.ChannelID, &i.MessageID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileParts = `-- name: ListFileParts :many

SELECT file_id, part_no, channel_id, message_id, plain_size, stored_size, checksum, salt, created_at, block_hashes
FROM /* TEMPLATE: schema */file_parts
WHERE file_id = $1
ORDER BY part_no
`

// Recursive move-cycle validation will be implemented as a hand-reviewed query in the file service.
func (q *Queries) ListFileParts(ctx context.Context, fileID pgtype.UUID) ([]*FilePart, error) {
	rows, err := q.db.Query(ctx, listFileParts, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FilePart{}
	for rows.Next() {
		var i FilePart
		if err := rows.Scan(
			&i.FileID,
			&i.PartNo,
			&i.ChannelID,
			&i.MessageID,
			&i.PlainSize,
			&i.StoredSize,
			&i.Checksum,
			&i.Salt,
			&i.CreatedAt,
			&i.BlockHashes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileSubtreeIDs = `-- name: ListFileSubtreeIDs :many
WITH RECURSIVE subtree AS (
  SELECT root.id FROM /* TEMPLATE: schema */files root WHERE root.id = $1 AND root.user_id = $2
  UNION ALL
  SELECT f.id FROM /* TEMPLATE: schema */files f JOIN subtree s ON f.parent_id = s.id WHERE f.user_id = $2
)
SELECT id FROM subtree
`

type ListFileSubtreeIDsParams struct {
	FileID pgtype.UUID `json:"file_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) ListFileSubtreeIDs(ctx context.Context, arg ListFileSubtreeIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listFileSubtreeIDs, arg.FileID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiles = `-- name: ListFiles :many
SELECT id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
FROM /* TEMPLATE: schema */files
WHERE files.user_id = $1
  AND (
    files.parent_id IS NOT DISTINCT FROM $2::uuid
    OR (
      $3::/* TEMPLATE: schema */file_status = 'trashed'
      AND $2::uuid IS NULL
      AND files.parent_id IS NOT NULL
      AND NOT EXISTS (
        SELECT 1
        FROM /* TEMPLATE: schema */files parent
        WHERE parent.id = files.parent_id
          AND parent.user_id = files.user_id
          AND parent.status = 'trashed'
      )
    )
  )
  AND files.status = $3::/* TEMPLATE: schema */file_status
  AND ($4::/* TEMPLATE: schema */file_kind IS NULL OR files.kind = $4::/* TEMPLATE: schema */file_kind)
  AND (
    $5::text IS NULL
    OR files.normalized_name % $5::text
    OR files.normalized_name ILIKE '%' || $5::text || '%'
  )
  AND (
    $6::text IS NULL
    OR (normalized_name, id) > ($6::text, $7::uuid)
  )
ORDER BY normalized_name, id
LIMIT $8
`

type ListFilesParams struct {
	UserID    int64        `json:"user_id"`
	ParentID  pgtype.UUID  `json:"parent_id"`
	Status    FileStatus   `json:"status"`
	Kind      NullFileKind `json:"kind"`
	Search    pgtype.Text  `json:"search"`
	AfterName pgtype.Text  `json:"after_name"`
	AfterID   pgtype.UUID  `json:"after_id"`
	PageSize  int32        `json:"page_size"`
}

func (q *Queries) ListFiles(ctx context.Context, arg ListFilesParams) ([]*File, error) {
	rows, err := q.db.Query(ctx, listFiles,
		arg.UserID,
		arg.ParentID,
		arg.Status,
		arg.Kind,
		arg.Search,
		arg.AfterName,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.NormalizedName,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesAdvanced = `-- name: ListFilesAdvanced :many
SELECT f.id, f.user_id, f.parent_id, f.name, f.normalized_name, f.kind, f.mime_type, f.size, f.hash_algorithm, f.hash_value, f.encryption, f.encryption_key_version, f.status, f.mod_time, f.generation, f.created_at, f.updated_at, f.deleted_at
FROM /* TEMPLATE: schema */files f
WHERE f.user_id = $1
  AND (
    f.parent_id IS NOT DISTINCT FROM $2::uuid
    OR (
      $3::/* TEMPLATE: schema */file_status = 'trashed'
      AND $2::uuid IS NULL
      AND f.parent_id IS NOT NULL
      AND NOT EXISTS (
        SELECT 1
        FROM /* TEMPLATE: schema */files parent
        WHERE parent.id = f.parent_id
          AND parent.user_id = f.user_id
          AND parent.status = 'trashed'
      )
    )
  )
  AND f.status = $3::/* TEMPLATE: schema */file_status
  AND ($4::/* TEMPLATE: schema */file_kind IS NULL OR f.kind = $4::/* TEMPLATE: schema */file_kind)
  AND (
    $5::text IS NULL
    OR ($6::text = 'regex' AND f.name ~* $5::text)
    OR (
      $6::text = 'text'
      AND (
        f.normalized_name % $5::text
        OR f.normalized_name ILIKE '%' || $5::text || '%'
      )
    )
  )
  AND (
    cardinality($7::text[]) = 0
    OR (CASE
      WHEN f.kind = 'folder' THEN 'other'
      WHEN lower(COALESCE(f.mime_type, '')) LIKE 'image/%' THEN 'image'
      WHEN lower(COALESCE(f.mime_type, '')) LIKE 'audio/%' THEN 'audio'
      WHEN lower(COALESCE(f.mime_type, '')) LIKE 'video/%' THEN 'video'
      WHEN lower(COALESCE(f.mime_type, '')) LIKE 'text/%'
        OR lower(COALESCE(f.mime_type, '')) IN (
          'application/pdf', 'application/json', 'application/xml',
          'application/msword', 'application/rtf',
          'application/vnd.ms-excel', 'application/vnd.ms-powerpoint',
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          'application/vnd.openxmlformats-officedocument.presentationml.presentation'
        ) THEN 'document'
      WHEN lower(COALESCE(f.mime_type, '')) IN (
          'application/zip', 'application/x-rar-compressed', 'application/x-7z-compressed',
          'application/x-tar', 'application/gzip', 'application/x-bzip2', 'application/x-xz'
        ) OR lower(f.name) ~ '\.(zip|rar|7z|tar|gz|tgz|bz2|xz)$' THEN 'archive'
      ELSE 'other'
    END) = ANY($7::text[])
  )
  AND ($8::timestamptz IS NULL OR f.updated_at >= $8::timestamptz)
  AND ($9::timestamptz IS NULL OR f.updated_at < $9::timestamptz)
  AND (
    $10::uuid IS NULL
    OR (
      $11::text = 'name'
      AND $12::text IS NOT NULL
      AND (
        ($13::text = 'asc' AND (f.normalized_name, f.id) > ($12::text, $10::uuid))
        OR ($13::text = 'desc' AND (f.normalized_name, f.id) < ($12::text, $10::uuid))
      )
    )
    OR (
      $11::text = 'updatedAt'
      AND $14::timestamptz IS NOT NULL
      AND (
        ($13::text = 'asc' AND (f.updated_at, f.id) > ($14::timestamptz, $10::uuid))
        OR ($13::text = 'desc' AND (f.updated_at, f.id) < ($14::timestamptz, $10::uuid))
      )
    )
    OR (
      $11::text = 'size'
      AND $15::bigint IS NOT NULL
      AND (
        ($13::text = 'asc' AND (COALESCE(f.size, -1), f.id) > ($15::bigint, $10::uuid))
        OR ($13::text = 'desc' AND (COALESCE(f.size, -1), f.id) < ($15::bigint, $10::uuid))
      )
    )
    OR (
      $11::text = 'id'
      AND (
        ($13::text = 'asc' AND f.id > $10::uuid)
        OR ($13::text = 'desc' AND f.id < $10::uuid)
      )
    )
  )
ORDER BY
  CASE WHEN $11::text = 'name' AND $13::text = 'asc' THEN f.normalized_name END ASC,
  CASE WHEN $11::text = 'name' AND $13::text = 'desc' THEN f.normalized_name END DESC,
  CASE WHEN $11::text = 'updatedAt' AND $13::text = 'asc' THEN f.updated_at END ASC,
  CASE WHEN $11::text = 'updatedAt' AND $13::text = 'desc' THEN f.updated_at END DESC,
  CASE WHEN $11::text = 'size' AND $13::text = 'asc' THEN COALESCE(f.size, -1) END ASC,
  CASE WHEN $11::text = 'size' AND $13::text = 'desc' THEN COALESCE(f.size, -1) END DESC,
  CASE WHEN $11::text = 'id' AND $13::text = 'asc' THEN f.id END ASC,
  CASE WHEN $11::text = 'id' AND $13::text = 'desc' THEN f.id END DESC,
  CASE WHEN $13::text = 'asc' THEN f.id END ASC,
  CASE WHEN $13::text = 'desc' THEN f.id END DESC
LIMIT $16
`

type ListFilesAdvancedParams struct {
	UserID         int64              `json:"user_id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	Status         FileStatus         `json:"status"`
	Kind           NullFileKind       `json:"kind"`
	Search         pgtype.Text        `json:"search"`
	SearchType     string             `json:"search_type"`
	Categories     []string           `json:"categories"`
	UpdatedAfter   pgtype.Timestamptz `json:"updated_after"`
	UpdatedBefore  pgtype.Timestamptz `json:"updated_before"`
	AfterID        pgtype.UUID        `json:"after_id"`
	SortBy         string             `json:"sort_by"`
	AfterName      pgtype.Text        `json:"after_name"`
	SortOrder      string             `json:"sort_order"`
	AfterUpdatedAt pgtype.Timestamptz `json:"after_updated_at"`
	AfterSize      pgtype.Int8        `json:"after_size"`
	PageSize       int32              `json:"page_size"`
}

func (q *Queries) ListFilesAdvanced(ctx context.Context, arg ListFilesAdvancedParams) ([]*File, error) {
	rows, err := q.db.Query(ctx, listFilesAdvanced,
		arg.UserID,
		arg.ParentID,
		arg.Status,
		arg.Kind,
		arg.Search,
		arg.SearchType,
		arg.Categories,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.AfterID,
		arg.SortBy,
		arg.AfterName,
		arg.SortOrder,
		arg.AfterUpdatedAt,
		arg.AfterSize,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.NormalizedName,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadFileSubtree = `-- name: LoadFileSubtree :many
WITH RECURSIVE tree AS (
    SELECT f.id, f.user_id, f.parent_id, f.name, f.normalized_name, f.kind, f.mime_type, f.size, f.hash_algorithm, f.hash_value, f.encryption, f.encryption_key_version, f.status, f.mod_time, f.generation, f.created_at, f.updated_at, f.deleted_at, 0::integer AS depth
    FROM /* TEMPLATE: schema */files f
    WHERE f.id = $1 AND f.user_id = $2
    UNION ALL
    SELECT child.id, child.user_id, child.parent_id, child.name, child.normalized_name, child.kind, child.mime_type, child.size, child.hash_algorithm, child.hash_value, child.encryption, child.encryption_key_version, child.status, child.mod_time, child.generation, child.created_at, child.updated_at, child.deleted_at, tree.depth + 1
    FROM /* TEMPLATE: schema */files child
    JOIN tree ON child.parent_id = tree.id
    WHERE child.user_id = $2
)
SELECT id, user_id, parent_id, name, normalized_name, kind, mime_type, size,
       hash_algorithm, hash_value, encryption, encryption_key_version, status,
       mod_time, generation, created_at, updated_at, deleted_at, depth
FROM tree
ORDER BY depth, id
`

type LoadFileSubtreeParams struct {
	RootID pgtype.UUID `json:"root_id"`
	UserID int64       `json:"user_id"`
}

type LoadFileSubtreeRow struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               int64              `json:"user_id"`
	ParentID             pgtype.UUID        `json:"parent_id"`
	Name                 string             `json:"name"`
	NormalizedName       string             `json:"normalized_name"`
	Kind                 FileKind           `json:"kind"`
	MimeType             pgtype.Text        `json:"mime_type"`
	Size                 pgtype.Int8        `json:"size"`
	HashAlgorithm        pgtype.Text        `json:"hash_algorithm"`
	HashValue            pgtype.Text        `json:"hash_value"`
	Encryption           bool               `json:"encryption"`
	EncryptionKeyVersion pgtype.Int4        `json:"encryption_key_version"`
	Status               FileStatus         `json:"status"`
	ModTime              pgtype.Timestamptz `json:"mod_time"`
	Generation           int64              `json:"generation"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	Depth                int32              `json:"depth"`
}

func (q *Queries) LoadFileSubtree(ctx context.Context, arg LoadFileSubtreeParams) ([]*LoadFileSubtreeRow, error) {
	rows, err := q.db.Query(ctx, loadFileSubtree, arg.RootID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*LoadFileSubtreeRow{}
	for rows.Next() {
		var i LoadFileSubtreeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.NormalizedName,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveFiles = `-- name: LockActiveFiles :many
SELECT id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
FROM /* TEMPLATE: schema */files
WHERE user_id = $1
  AND id = ANY($2::uuid[])
  AND status = 'active'
FOR UPDATE
`

type LockActiveFilesParams struct {
	UserID  int64         `json:"user_id"`
	FileIds []pgtype.UUID `json:"file_ids"`
}

func (q *Queries) LockActiveFiles(ctx context.Context, arg LockActiveFilesParams) ([]*File, error) {
	rows, err := q.db.Query(ctx, lockActiveFiles, arg.UserID, arg.FileIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.NormalizedName,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveFolder = `-- name: LockActiveFolder :one
SELECT id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
FROM /* TEMPLATE: schema */files
WHERE id = $1
  AND user_id = $2
  AND kind = 'folder'
  AND status = 'active'
FOR UPDATE
`

type LockActiveFolderParams struct {
	FolderID pgtype.UUID `json:"folder_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) LockActiveFolder(ctx context.Context, arg LockActiveFolderParams) (*File, error) {
	row := q.db.QueryRow(ctx, lockActiveFolder, arg.FolderID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const lockActiveNameConflict = `-- name: LockActiveNameConflict :one
SELECT id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
FROM /* TEMPLATE: schema */files
WHERE user_id = $1
  AND parent_id IS NOT DISTINCT FROM $2::uuid
  AND normalized_name = $3
  AND status = 'active'
  AND id <> $4
FOR UPDATE
`

type LockActiveNameConflictParams struct {
	UserID         int64       `json:"user_id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	NormalizedName string      `json:"normalized_name"`
	ExcludeID      pgtype.UUID `json:"exclude_id"`
}

func (q *Queries) LockActiveNameConflict(ctx context.Context, arg LockActiveNameConflictParams) (*File, error) {
	row := q.db.QueryRow(ctx, lockActiveNameConflict,
		arg.UserID,
		arg.ParentID,
		arg.NormalizedName,
		arg.ExcludeID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const markAllTrashedDeletionPending = `-- name: MarkAllTrashedDeletionPending :execrows
UPDATE /* TEMPLATE: schema */files
SET status = 'deletion_pending',
    deleted_at = COALESCE(deleted_at, now()),
    updated_at = now()
WHERE user_id = $1
  AND status = 'trashed'
`

func (q *Queries) MarkAllTrashedDeletionPending(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, markAllTrashedDeletionPending, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markFileDeletionPending = `-- name: MarkFileDeletionPending :one
UPDATE /* TEMPLATE: schema */files
SET status = 'deletion_pending',
    deleted_at = COALESCE(deleted_at, now()),
    generation = generation + 1,
    updated_at = now()
WHERE id = $1
  AND user_id = $2
  AND status = 'trashed'
RETURNING id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
`

type MarkFileDeletionPendingParams struct {
	FileID pgtype.UUID `json:"file_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) MarkFileDeletionPending(ctx context.Context, arg MarkFileDeletionPendingParams) (*File, error) {
	row := q.db.QueryRow(ctx, markFileDeletionPending, arg.FileID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const markFileIDsDeletionPending = `-- name: MarkFileIDsDeletionPending :exec
UPDATE /* TEMPLATE: schema */files
SET status = 'deletion_pending',
    deleted_at = COALESCE(deleted_at, now()),
    updated_at = now()
WHERE user_id = $1
  AND id = ANY($2::uuid[])
`

type MarkFileIDsDeletionPendingParams struct {
	UserID  int64         `json:"user_id"`
	FileIds []pgtype.UUID `json:"file_ids"`
}

func (q *Queries) MarkFileIDsDeletionPending(ctx context.Context, arg MarkFileIDsDeletionPendingParams) error {
	_, err := q.db.Exec(ctx, markFileIDsDeletionPending, arg.UserID, arg.FileIds)
	return err
}

const markFileSubtreeDeletionPending = `-- name: MarkFileSubtreeDeletionPending :exec
WITH RECURSIVE target AS (
  SELECT root.id FROM /* TEMPLATE: schema */files root WHERE root.id = $2 AND root.user_id = $1 AND root.status = 'active'
  UNION ALL
  SELECT child.id FROM /* TEMPLATE: schema */files child JOIN target parent ON child.parent_id = parent.id WHERE child.user_id = $1 AND child.status = 'active'
)
UPDATE /* TEMPLATE: schema */files AS target_file
SET status = 'deletion_pending',
    deleted_at = COALESCE(target_file.deleted_at, now()),
    generation = target_file.generation + 1,
    updated_at = now()
WHERE target_file.user_id = $1 AND target_file.id IN (SELECT target.id FROM target)
`

type MarkFileSubtreeDeletionPendingParams struct {
	UserID int64       `json:"user_id"`
	FileID pgtype.UUID `json:"file_id"`
}

func (q *Queries) MarkFileSubtreeDeletionPending(ctx context.Context, arg MarkFileSubtreeDeletionPendingParams) error {
	_, err := q.db.Exec(ctx, markFileSubtreeDeletionPending, arg.UserID, arg.FileID)
	return err
}

const moveFile = `-- name: MoveFile :one
UPDATE /* TEMPLATE: schema */files
SET parent_id = $1,
    generation = generation + 1,
    updated_at = now()
WHERE id = $2
  AND user_id = $3
  AND status = 'active'
  AND (
    $4::bigint IS NULL
    OR generation = $4::bigint
  )
RETURNING id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
`

type MoveFileParams struct {
	ParentID           pgtype.UUID `json:"parent_id"`
	FileID             pgtype.UUID `json:"file_id"`
	UserID             int64       `json:"user_id"`
	ExpectedGeneration pgtype.Int8 `json:"expected_generation"`
}

func (q *Queries) MoveFile(ctx context.Context, arg MoveFileParams) (*File, error) {
	row := q.db.QueryRow(ctx, moveFile,
		arg.ParentID,
		arg.FileID,
		arg.UserID,
		arg.ExpectedGeneration,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const moveFileWithName = `-- name: MoveFileWithName :one
UPDATE /* TEMPLATE: schema */files
SET parent_id = $1,
    name = $2,
    normalized_name = $3,
    generation = generation + 1,
    updated_at = now()
WHERE id = $4
  AND user_id = $5
  AND status = 'active'
  AND ($6::bigint IS NULL OR generation = $6::bigint)
RETURNING id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
`

type MoveFileWithNameParams struct {
	ParentID           pgtype.UUID `json:"parent_id"`
	Name               string      `json:"name"`
	NormalizedName     string      `json:"normalized_name"`
	FileID             pgtype.UUID `json:"file_id"`
	UserID             int64       `json:"user_id"`
	ExpectedGeneration pgtype.Int8 `json:"expected_generation"`
}

func (q *Queries) MoveFileWithName(ctx context.Context, arg MoveFileWithNameParams) (*File, error) {
	row := q.db.QueryRow(ctx, moveFileWithName,
		arg.ParentID,
		arg.Name,
		arg.NormalizedName,
		arg.FileID,
		arg.UserID,
		arg.ExpectedGeneration,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const resolveActiveChild = `-- name: ResolveActiveChild :one
SELECT id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
FROM /* TEMPLATE: schema */files
WHERE user_id = $1
  AND parent_id IS NOT DISTINCT FROM $2::uuid
  AND normalized_name = $3
  AND status = 'active'
`

type ResolveActiveChildParams struct {
	UserID         int64       `json:"user_id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	NormalizedName string      `json:"normalized_name"`
}

func (q *Queries) ResolveActiveChild(ctx context.Context, arg ResolveActiveChildParams) (*File, error) {
	row := q.db.QueryRow(ctx, resolveActiveChild, arg.UserID, arg.ParentID, arg.NormalizedName)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const resolveActiveChildFolder = `-- name: ResolveActiveChildFolder :one
SELECT id
FROM /* TEMPLATE: schema */files
WHERE user_id = $1
  AND parent_id IS NOT DISTINCT FROM $2::uuid
  AND normalized_name = $3
  AND kind = 'folder'
  AND status = 'active'
`

type ResolveActiveChildFolderParams struct {
	UserID         int64       `json:"user_id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	NormalizedName string      `json:"normalized_name"`
}

func (q *Queries) ResolveActiveChildFolder(ctx context.Context, arg ResolveActiveChildFolderParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveActiveChildFolder, arg.UserID, arg.ParentID, arg.NormalizedName)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const restoreFile = `-- name: RestoreFile :one
UPDATE /* TEMPLATE: schema */files
SET status = 'active',
    deleted_at = NULL,
    generation = generation + 1,
    updated_at = now()
WHERE id = $1
  AND user_id = $2
  AND status = 'trashed'
RETURNING id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
`

type RestoreFileParams struct {
	FileID pgtype.UUID `json:"file_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) RestoreFile(ctx context.Context, arg RestoreFileParams) (*File, error) {
	row := q.db.QueryRow(ctx, restoreFile, arg.FileID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const revokeSharesForFileSubtree = `-- name: RevokeSharesForFileSubtree :exec
WITH RECURSIVE target AS (
  SELECT root.id FROM /* TEMPLATE: schema */files root WHERE root.id = $2 AND root.user_id = $1
  UNION ALL
  SELECT child.id FROM /* TEMPLATE: schema */files child JOIN target parent ON child.parent_id = parent.id WHERE child.user_id = $1
)
UPDATE /* TEMPLATE: schema */file_shares AS share
SET revoked_at = COALESCE(share.revoked_at, now())
WHERE share.owner_id = $1
  AND share.revoked_at IS NULL
  AND share.file_id IN (SELECT target.id FROM target)
`

type RevokeSharesForFileSubtreeParams struct {
	UserID int64       `json:"user_id"`
	FileID pgtype.UUID `json:"file_id"`
}

func (q *Queries) RevokeSharesForFileSubtree(ctx context.Context, arg RevokeSharesForFileSubtreeParams) error {
	_, err := q.db.Exec(ctx, revokeSharesForFileSubtree, arg.UserID, arg.FileID)
	return err
}

const revokeSharesForFileSubtrees = `-- name: RevokeSharesForFileSubtrees :exec
WITH RECURSIVE target AS (
  SELECT root.id FROM /* TEMPLATE: schema */files root WHERE root.user_id = $1 AND root.id = ANY($2::uuid[])
  UNION
  SELECT child.id FROM /* TEMPLATE: schema */files child JOIN target parent ON child.parent_id = parent.id WHERE child.user_id = $1
)
UPDATE /* TEMPLATE: schema */file_shares AS share
SET revoked_at = COALESCE(share.revoked_at, now())
WHERE share.owner_id = $1
  AND share.revoked_at IS NULL
  AND share.file_id IN (SELECT target.id FROM target)
`

type RevokeSharesForFileSubtreesParams struct {
	UserID  int64         `json:"user_id"`
	FileIds []pgtype.UUID `json:"file_ids"`
}

func (q *Queries) RevokeSharesForFileSubtrees(ctx context.Context, arg RevokeSharesForFileSubtreesParams) error {
	_, err := q.db.Exec(ctx, revokeSharesForFileSubtrees, arg.UserID, arg.FileIds)
	return err
}

const sumFilePartSizes = `-- name: SumFilePartSizes :one
SELECT
    COALESCE(sum(plain_size), 0)::bigint AS plain_size,
    COALESCE(sum(stored_size), 0)::bigint AS stored_size,
    count(*)::integer AS part_count
FROM /* TEMPLATE: schema */file_parts
WHERE file_id = $1
`

type SumFilePartSizesRow struct {
	PlainSize  int64 `json:"plain_size"`
	StoredSize int64 `json:"stored_size"`
	PartCount  int32 `json:"part_count"`
}

func (q *Queries) SumFilePartSizes(ctx context.Context, fileID pgtype.UUID) (*SumFilePartSizesRow, error) {
	row := q.db.QueryRow(ctx, sumFilePartSizes, fileID)
	var i SumFilePartSizesRow
	err := row.Scan(&i.PlainSize, &i.StoredSize, &i.PartCount)
	return &i, err
}

const trashFile = `-- name: TrashFile :one
UPDATE /* TEMPLATE: schema */files
SET status = 'trashed',
    deleted_at = now(),
    generation = generation + 1,
    updated_at = now()
WHERE id = $1
  AND user_id = $2
  AND status = 'active'
RETURNING id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
`

type TrashFileParams struct {
	FileID pgtype.UUID `json:"file_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) TrashFile(ctx context.Context, arg TrashFileParams) (*File, error) {
	row := q.db.QueryRow(ctx, trashFile, arg.FileID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const trashFileSubtrees = `-- name: TrashFileSubtrees :many
WITH RECURSIVE target AS (
  SELECT root.id
  FROM /* TEMPLATE: schema */files root
  WHERE root.user_id = $1
    AND root.id = ANY($2::uuid[])
    AND root.status = 'active'
  UNION
  SELECT child.id
  FROM /* TEMPLATE: schema */files child
  JOIN target parent ON child.parent_id = parent.id
  WHERE child.user_id = $1
    AND child.status = 'active'
)
UPDATE /* TEMPLATE: schema */files AS target_file
SET status = 'trashed',
    deleted_at = now(),
    generation = target_file.generation + 1,
    updated_at = now()
WHERE target_file.user_id = $1
  AND target_file.id IN (SELECT target.id FROM target)
RETURNING target_file.id, target_file.user_id, target_file.parent_id, target_file.name, target_file.normalized_name, target_file.kind, target_file.mime_type, target_file.size, target_file.hash_algorithm, target_file.hash_value, target_file.encryption, target_file.encryption_key_version, target_file.status, target_file.mod_time, target_file.generation, target_file.created_at, target_file.updated_at, target_file.deleted_at
`

type TrashFileSubtreesParams struct {
	UserID  int64         `json:"user_id"`
	FileIds []pgtype.UUID `json:"file_ids"`
}

func (q *Queries) TrashFileSubtrees(ctx context.Context, arg TrashFileSubtreesParams) ([]*File, error) {
	rows, err := q.db.Query(ctx, trashFileSubtrees, arg.UserID, arg.FileIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.NormalizedName,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileMetadata = `-- name: UpdateFileMetadata :one
UPDATE /* TEMPLATE: schema */files
SET name = COALESCE($1, name),
    normalized_name = COALESCE($2, normalized_name),
    mod_time = COALESCE($3, mod_time),
    generation = generation + 1,
    updated_at = now()
WHERE id = $4
  AND user_id = $5
  AND status = 'active'
  AND (
    $6::bigint IS NULL
    OR generation = $6::bigint
  )
RETURNING id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
`

type UpdateFileMetadataParams struct {
	Name               pgtype.Text        `json:"name"`
	NormalizedName     pgtype.Text        `json:"normalized_name"`
	ModTime            pgtype.Timestamptz `json:"mod_time"`
	FileID             pgtype.UUID        `json:"file_id"`
	UserID             int64              `json:"user_id"`
	ExpectedGeneration pgtype.Int8        `json:"expected_generation"`
}

func (q *Queries) UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) (*File, error) {
	row := q.db.QueryRow(ctx, updateFileMetadata,
		arg.Name,
		arg.NormalizedName,
		arg.ModTime,
		arg.FileID,
		arg.UserID,
		arg.ExpectedGeneration,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateFilePartSizes = `-- name: UpdateFilePartSizes :execrows
UPDATE /* TEMPLATE: schema */file_parts
SET plain_size = $1,
    stored_size = $2
WHERE file_id = $3
  AND part_no = $4
  AND (plain_size IS NULL OR stored_size IS NULL)
`

type UpdateFilePartSizesParams struct {
	PlainSize  pgtype.Int8 `json:"plain_size"`
	StoredSize pgtype.Int8 `json:"stored_size"`
	FileID     pgtype.UUID `json:"file_id"`
	PartNo     int32       `json:"part_no"`
}

func (q *Queries) UpdateFilePartSizes(ctx context.Context, arg UpdateFilePartSizesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFilePartSizes,
		arg.PlainSize,
		arg.StoredSize,
		arg.FileID,
		arg.PartNo,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
