// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearUploadSessionParentsByFileIDs = `-- name: ClearUploadSessionParentsByFileIDs :exec
UPDATE /* TEMPLATE: schema */upload_sessions
SET parent_id = NULL,
    updated_at = now()
WHERE user_id = $1
  AND parent_id = ANY($2::uuid[])
`

type ClearUploadSessionParentsByFileIDsParams struct {
	UserID  int64         `json:"user_id"`
	FileIds []pgtype.UUID `json:"file_ids"`
}

func (q *Queries) ClearUploadSessionParentsByFileIDs(ctx context.Context, arg ClearUploadSessionParentsByFileIDsParams) error {
	_, err := q.db.Exec(ctx, clearUploadSessionParentsByFileIDs, arg.UserID, arg.FileIds)
	return err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO /* TEMPLATE: schema */files (
    id,
    user_id,
    parent_id,
    name,
    kind,
    mime_type,
    size,
    encryption,
    status,
    mod_time
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'folder',
    'inode/directory',
    NULL,
    false,
    'active',
    $5
)
RETURNING id, user_id, parent_id, name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
`

type CreateFolderParams struct {
	ID       pgtype.UUID        `json:"id"`
	UserID   int64              `json:"user_id"`
	ParentID pgtype.UUID        `json:"parent_id"`
	Name     string             `json:"name"`
	ModTime  pgtype.Timestamptz `json:"mod_time"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (*File, error) {
	row := q.db.QueryRow(ctx, createFolder,
		arg.ID,
		arg.UserID,
		arg.ParentID,
		arg.Name,
		arg.ModTime,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const deleteFileCatalogRowsByIDs = `-- name: DeleteFileCatalogRowsByIDs :execrows
DELETE FROM /* TEMPLATE: schema */files
WHERE id = ANY($1::uuid[])
  AND user_id = $2
  AND status = 'deletion_pending'
`

type DeleteFileCatalogRowsByIDsParams struct {
	FileIds []pgtype.UUID `json:"file_ids"`
	UserID  int64         `json:"user_id"`
}

func (q *Queries) DeleteFileCatalogRowsByIDs(ctx context.Context, arg DeleteFileCatalogRowsByIDsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFileCatalogRowsByIDs, arg.FileIds, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFilePartsByFileIDs = `-- name: DeleteFilePartsByFileIDs :exec
DELETE FROM /* TEMPLATE: schema */file_parts
WHERE file_id = ANY($1::uuid[])
`

func (q *Queries) DeleteFilePartsByFileIDs(ctx context.Context, fileIds []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFilePartsByFileIDs, fileIds)
	return err
}

const getActiveFolderForUser = `-- name: GetActiveFolderForUser :one
SELECT id, user_id, parent_id, name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
FROM /* TEMPLATE: schema */files
WHERE id = $1
  AND user_id = $2
  AND kind = 'folder'
  AND status = 'active'
`

type GetActiveFolderForUserParams struct {
	FolderID pgtype.UUID `json:"folder_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) GetActiveFolderForUser(ctx context.Context, arg GetActiveFolderForUserParams) (*File, error) {
	row := q.db.QueryRow(ctx, getActiveFolderForUser, arg.FolderID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getDriveStatistics = `-- name: GetDriveStatistics :one
SELECT
  count(*) FILTER (WHERE kind = 'file' AND status = 'active')::bigint AS total_files,
  count(*) FILTER (WHERE kind = 'folder' AND status = 'active')::bigint AS total_folders,
  COALESCE(sum(size) FILTER (WHERE kind = 'file' AND status = 'active'), 0)::bigint AS total_bytes,
  count(*) FILTER (WHERE status = 'trashed')::bigint AS trashed_files,
  (SELECT count(*)::bigint FROM /* TEMPLATE: schema */file_shares WHERE owner_id = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())) AS active_shares,
  (SELECT count(*)::bigint FROM /* TEMPLATE: schema */upload_sessions WHERE user_id = $1 AND state IN ('open', 'completing')) AS open_uploads
FROM /* TEMPLATE: schema */files
WHERE user_id = $1
`

type GetDriveStatisticsRow struct {
	TotalFiles   int64 `json:"total_files"`
	TotalFolders int64 `json:"total_folders"`
	TotalBytes   int64 `json:"total_bytes"`
	TrashedFiles int64 `json:"trashed_files"`
	ActiveShares int64 `json:"active_shares"`
	OpenUploads  int64 `json:"open_uploads"`
}

func (q *Queries) GetDriveStatistics(ctx context.Context, userID int64) (*GetDriveStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getDriveStatistics, userID)
	var i GetDriveStatisticsRow
	err := row.Scan(
		&i.TotalFiles,
		&i.TotalFolders,
		&i.TotalBytes,
		&i.TrashedFiles,
		&i.ActiveShares,
		&i.OpenUploads,
	)
	return &i, err
}

const getFileForUser = `-- name: GetFileForUser :one
SELECT id, user_id, parent_id, name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
FROM /* TEMPLATE: schema */files
WHERE id = $1
  AND user_id = $2
`

type GetFileForUserParams struct {
	FileID pgtype.UUID `json:"file_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) GetFileForUser(ctx context.Context, arg GetFileForUserParams) (*File, error) {
	row := q.db.QueryRow(ctx, getFileForUser, arg.FileID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const insertCopiedFileParts = `-- name: InsertCopiedFileParts :execrows
INSERT INTO /* TEMPLATE: schema */file_parts (
    file_id, part_no, channel_id, message_id, plain_size, stored_size,
    checksum, salt, block_hashes
)
SELECT input.file_id, input.part_no, input.channel_id, input.message_id,
       input.plain_size, input.stored_size, input.checksum, input.salt,
       decode(input.block_hashes, 'base64')
FROM jsonb_to_recordset($1::jsonb) AS input(
    file_id uuid, part_no integer, channel_id bigint, message_id bigint,
    plain_size bigint, stored_size bigint, checksum text, salt text,
    block_hashes text
)
`

func (q *Queries) InsertCopiedFileParts(ctx context.Context, parts []byte) (int64, error) {
	result, err := q.db.Exec(ctx, insertCopiedFileParts, parts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCopiedFiles = `-- name: InsertCopiedFiles :many
INSERT INTO /* TEMPLATE: schema */files AS file (
    id, user_id, parent_id, name, kind, mime_type, size,
    hash_algorithm, hash_value, encryption, encryption_key_version,
    status, mod_time, generation
)
SELECT input.id, input.user_id, input.parent_id, input.name,
       input.kind::/* TEMPLATE: schema */file_kind, input.mime_type, input.size,
       input.hash_algorithm, input.hash_value, input.encryption,
       input.encryption_key_version, 'active', input.mod_time, 1
FROM jsonb_to_recordset($1::jsonb) AS input(
    id uuid, user_id bigint, parent_id uuid, name text,
    kind text, mime_type text, size bigint, hash_algorithm text, hash_value text,
    encryption boolean, encryption_key_version integer, mod_time timestamptz
)
RETURNING file.id, file.user_id, file.parent_id, file.name, file.kind, file.mime_type, file.size, file.hash_algorithm, file.hash_value, file.encryption, file.encryption_key_version, file.status, file.mod_time, file.generation, file.created_at, file.updated_at, file.deleted_at
`

func (q *Queries) InsertCopiedFiles(ctx context.Context, files []byte) ([]*File, error) {
	rows, err := q.db.Query(ctx, insertCopiedFiles, files)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveNames = `-- name: ListActiveNames :many
SELECT name
FROM /* TEMPLATE: schema */files
WHERE user_id = $1
  AND parent_id IS NOT DISTINCT FROM $2::uuid
  AND status = 'active'
  AND ($3::uuid IS NULL OR id <> $3::uuid)
`

type ListActiveNamesParams struct {
	UserID    int64       `json:"user_id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	ExcludeID pgtype.UUID `json:"exclude_id"`
}

func (q *Queries) ListActiveNames(ctx context.Context, arg ListActiveNamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveNames, arg.UserID, arg.ParentID, arg.ExcludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileAncestorIDs = `-- name: ListFileAncestorIDs :many
WITH RECURSIVE ancestors AS (
  SELECT file.id, file.parent_id
  FROM /* TEMPLATE: schema */files AS file
  WHERE file.id = $1
    AND file.user_id = $2
  UNION ALL
  SELECT parent.id, parent.parent_id
  FROM /* TEMPLATE: schema */files AS parent
  JOIN ancestors AS child ON parent.id = child.parent_id
  WHERE parent.user_id = $2
)
SELECT id FROM ancestors
`

type ListFileAncestorIDsParams struct {
	FileID pgtype.UUID `json:"file_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) ListFileAncestorIDs(ctx context.Context, arg ListFileAncestorIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listFileAncestorIDs, arg.FileID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileCategoryStatistics = `-- name: ListFileCategoryStatistics :many
SELECT category, count(*)::bigint AS total_files, COALESCE(sum(size), 0)::bigint AS total_size
FROM (
  SELECT CASE
    WHEN lower(COALESCE(f.mime_type, '')) LIKE 'image/%' THEN 'image'
    WHEN lower(COALESCE(f.mime_type, '')) LIKE 'audio/%' THEN 'audio'
    WHEN lower(COALESCE(f.mime_type, '')) LIKE 'video/%' THEN 'video'
    WHEN lower(COALESCE(f.mime_type, '')) LIKE 'text/%'
      OR lower(COALESCE(f.mime_type, '')) IN (
        'application/pdf', 'application/json', 'application/xml',
        'application/msword', 'application/rtf',
        'application/vnd.ms-excel', 'application/vnd.ms-powerpoint',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation'
      ) THEN 'document'
    WHEN lower(COALESCE(f.mime_type, '')) IN (
        'application/zip', 'application/x-rar-compressed', 'application/x-7z-compressed',
        'application/x-tar', 'application/gzip', 'application/x-bzip2', 'application/x-xz'
      ) OR lower(f.name) ~ '\.(zip|rar|7z|tar|gz|tgz|bz2|xz)$' THEN 'archive'
    ELSE 'other'
  END AS category, f.size
  FROM /* TEMPLATE: schema */files f
  WHERE f.user_id = $1
    AND f.kind = 'file'
    AND f.status = 'active'
) categorized
GROUP BY category
ORDER BY category
`

type ListFileCategoryStatisticsRow struct {
	Category   string `json:"category"`
	TotalFiles int64  `json:"total_files"`
	TotalSize  int64  `json:"total_size"`
}

func (q *Queries) ListFileCategoryStatistics(ctx context.Context, userID int64) ([]*ListFileCategoryStatisticsRow, error) {
	rows, err := q.db.Query(ctx, listFileCategoryStatistics, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListFileCategoryStatisticsRow{}
	for rows.Next() {
		var i ListFileCategoryStatisticsRow
		if err := rows.Scan(&i.Category, &i.TotalFiles, &i.TotalSize); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilePartMessageRefs = `-- name: ListFilePartMessageRefs :many
SELECT channel_id, message_id
FROM /* TEMPLATE: schema */file_parts
WHERE file_id = ANY($1::uuid[])
ORDER BY channel_id, message_id
`

type ListFilePartMessageRefsRow struct {
	ChannelID int64 `json:"channel_id"`
	MessageID int64 `json:"message_id"`
}

func (q *Queries) ListFilePartMessageRefs(ctx context.Context, fileIds []pgtype.UUID) ([]*ListFilePartMessageRefsRow, error) {
	rows, err := q.db.Query(ctx, listFilePartMessageRefs, fileIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListFilePartMessageRefsRow{}
	for rows.Next() {
		var i ListFilePartMessageRefsRow
		if err := rows.Scan(&i.ChannelID, &i.MessageID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileParts = `-- name: ListFileParts :many

SELECT file_id, part_no, channel_id, message_id, plain_size, stored_size, checksum, salt, created_at, block_hashes
FROM /* TEMPLATE: schema */file_parts
WHERE file_id = $1
ORDER BY part_no
`

// Recursive move-cycle validation will be implemented as a hand-reviewed query in the file service.
func (q *Queries) ListFileParts(ctx context.Context, fileID pgtype.UUID) ([]*FilePart, error) {
	rows, err := q.db.Query(ctx, listFileParts, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FilePart{}
	for rows.Next() {
		var i FilePart
		if err := rows.Scan(
			&i.FileID,
			&i.PartNo,
			&i.ChannelID,
			&i.MessageID,
			&i.PlainSize,
			&i.StoredSize,
			&i.Checksum,
			&i.Salt,
			&i.CreatedAt,
			&i.BlockHashes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilePartsByFileIDs = `-- name: ListFilePartsByFileIDs :many
SELECT file_id, part_no, channel_id, message_id, plain_size, stored_size, checksum, salt, created_at, block_hashes
FROM /* TEMPLATE: schema */file_parts
WHERE file_id = ANY($1::uuid[])
ORDER BY file_id, part_no
`

func (q *Queries) ListFilePartsByFileIDs(ctx context.Context, fileIds []pgtype.UUID) ([]*FilePart, error) {
	rows, err := q.db.Query(ctx, listFilePartsByFileIDs, fileIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FilePart{}
	for rows.Next() {
		var i FilePart
		if err := rows.Scan(
			&i.FileID,
			&i.PartNo,
			&i.ChannelID,
			&i.MessageID,
			&i.PlainSize,
			&i.StoredSize,
			&i.Checksum,
			&i.Salt,
			&i.CreatedAt,
			&i.BlockHashes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileSubtreeIDs = `-- name: ListFileSubtreeIDs :many
WITH RECURSIVE subtree AS (
  SELECT root.id FROM /* TEMPLATE: schema */files root WHERE root.id = $1 AND root.user_id = $2
  UNION ALL
  SELECT f.id FROM /* TEMPLATE: schema */files f JOIN subtree s ON f.parent_id = s.id WHERE f.user_id = $2
)
SELECT id FROM subtree
`

type ListFileSubtreeIDsParams struct {
	FileID pgtype.UUID `json:"file_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) ListFileSubtreeIDs(ctx context.Context, arg ListFileSubtreeIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listFileSubtreeIDs, arg.FileID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiles = `-- name: ListFiles :many
SELECT id, user_id, parent_id, name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
FROM /* TEMPLATE: schema */files
WHERE files.user_id = $1
  AND (
    files.parent_id IS NOT DISTINCT FROM $2::uuid
    OR (
      $3::/* TEMPLATE: schema */file_status = 'trashed'
      AND $2::uuid IS NULL
      AND files.parent_id IS NOT NULL
      AND NOT EXISTS (
        SELECT 1
        FROM /* TEMPLATE: schema */files parent
        WHERE parent.id = files.parent_id
          AND parent.user_id = files.user_id
          AND parent.status = 'trashed'
      )
    )
  )
  AND files.status = $3::/* TEMPLATE: schema */file_status
  AND ($4::/* TEMPLATE: schema */file_kind IS NULL OR files.kind = $4::/* TEMPLATE: schema */file_kind)
  AND (
    $5::text IS NULL
    OR files.name % $5::text
    OR files.name ILIKE '%' || $5::text || '%'
  )
  AND (
    $6::text IS NULL
    OR (name, id) > ($6::text, $7::uuid)
  )
ORDER BY name, id
LIMIT $8
`

type ListFilesParams struct {
	UserID    int64        `json:"user_id"`
	ParentID  pgtype.UUID  `json:"parent_id"`
	Status    FileStatus   `json:"status"`
	Kind      NullFileKind `json:"kind"`
	Search    pgtype.Text  `json:"search"`
	AfterName pgtype.Text  `json:"after_name"`
	AfterID   pgtype.UUID  `json:"after_id"`
	PageSize  int32        `json:"page_size"`
}

func (q *Queries) ListFiles(ctx context.Context, arg ListFilesParams) ([]*File, error) {
	rows, err := q.db.Query(ctx, listFiles,
		arg.UserID,
		arg.ParentID,
		arg.Status,
		arg.Kind,
		arg.Search,
		arg.AfterName,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesAdvanced = `-- name: ListFilesAdvanced :many
SELECT f.id, f.user_id, f.parent_id, f.name, f.kind, f.mime_type, f.size, f.hash_algorithm, f.hash_value, f.encryption, f.encryption_key_version, f.status, f.mod_time, f.generation, f.created_at, f.updated_at, f.deleted_at
FROM /* TEMPLATE: schema */files f
WHERE f.user_id = $1
  AND (
    f.parent_id IS NOT DISTINCT FROM $2::uuid
    OR (
      $3::/* TEMPLATE: schema */file_status = 'trashed'
      AND $2::uuid IS NULL
      AND f.parent_id IS NOT NULL
      AND NOT EXISTS (
        SELECT 1
        FROM /* TEMPLATE: schema */files parent
        WHERE parent.id = f.parent_id
          AND parent.user_id = f.user_id
          AND parent.status = 'trashed'
      )
    )
  )
  AND f.status = $3::/* TEMPLATE: schema */file_status
  AND ($4::/* TEMPLATE: schema */file_kind IS NULL OR f.kind = $4::/* TEMPLATE: schema */file_kind)
  AND (
    $5::text IS NULL
    OR ($6::text = 'regex' AND f.name ~* $5::text)
    OR (
      $6::text = 'text'
      AND (
        f.name % $5::text
        OR f.name ILIKE '%' || $5::text || '%'
      )
    )
  )
  AND (
    cardinality($7::text[]) = 0
    OR (CASE
      WHEN f.kind = 'folder' THEN 'other'
      WHEN lower(COALESCE(f.mime_type, '')) LIKE 'image/%' THEN 'image'
      WHEN lower(COALESCE(f.mime_type, '')) LIKE 'audio/%' THEN 'audio'
      WHEN lower(COALESCE(f.mime_type, '')) LIKE 'video/%' THEN 'video'
      WHEN lower(COALESCE(f.mime_type, '')) LIKE 'text/%'
        OR lower(COALESCE(f.mime_type, '')) IN (
          'application/pdf', 'application/json', 'application/xml',
          'application/msword', 'application/rtf',
          'application/vnd.ms-excel', 'application/vnd.ms-powerpoint',
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          'application/vnd.openxmlformats-officedocument.presentationml.presentation'
        ) THEN 'document'
      WHEN lower(COALESCE(f.mime_type, '')) IN (
          'application/zip', 'application/x-rar-compressed', 'application/x-7z-compressed',
          'application/x-tar', 'application/gzip', 'application/x-bzip2', 'application/x-xz'
        ) OR lower(f.name) ~ '\.(zip|rar|7z|tar|gz|tgz|bz2|xz)$' THEN 'archive'
      ELSE 'other'
    END) = ANY($7::text[])
  )
  AND ($8::timestamptz IS NULL OR f.updated_at >= $8::timestamptz)
  AND ($9::timestamptz IS NULL OR f.updated_at < $9::timestamptz)
  AND (
    $10::uuid IS NULL
    OR (
      $11::text = 'name'
      AND $12::text IS NOT NULL
      AND (
        ($13::text = 'asc' AND (f.name, f.id) > ($12::text, $10::uuid))
        OR ($13::text = 'desc' AND (f.name, f.id) < ($12::text, $10::uuid))
      )
    )
    OR (
      $11::text = 'updatedAt'
      AND $14::timestamptz IS NOT NULL
      AND (
        ($13::text = 'asc' AND (f.updated_at, f.id) > ($14::timestamptz, $10::uuid))
        OR ($13::text = 'desc' AND (f.updated_at, f.id) < ($14::timestamptz, $10::uuid))
      )
    )
    OR (
      $11::text = 'size'
      AND $15::bigint IS NOT NULL
      AND (
        ($13::text = 'asc' AND (COALESCE(f.size, -1), f.id) > ($15::bigint, $10::uuid))
        OR ($13::text = 'desc' AND (COALESCE(f.size, -1), f.id) < ($15::bigint, $10::uuid))
      )
    )
    OR (
      $11::text = 'id'
      AND (
        ($13::text = 'asc' AND f.id > $10::uuid)
        OR ($13::text = 'desc' AND f.id < $10::uuid)
      )
    )
  )
ORDER BY
  CASE WHEN $11::text = 'name' AND $13::text = 'asc' THEN f.name END ASC,
  CASE WHEN $11::text = 'name' AND $13::text = 'desc' THEN f.name END DESC,
  CASE WHEN $11::text = 'updatedAt' AND $13::text = 'asc' THEN f.updated_at END ASC,
  CASE WHEN $11::text = 'updatedAt' AND $13::text = 'desc' THEN f.updated_at END DESC,
  CASE WHEN $11::text = 'size' AND $13::text = 'asc' THEN COALESCE(f.size, -1) END ASC,
  CASE WHEN $11::text = 'size' AND $13::text = 'desc' THEN COALESCE(f.size, -1) END DESC,
  CASE WHEN $11::text = 'id' AND $13::text = 'asc' THEN f.id END ASC,
  CASE WHEN $11::text = 'id' AND $13::text = 'desc' THEN f.id END DESC,
  CASE WHEN $13::text = 'asc' THEN f.id END ASC,
  CASE WHEN $13::text = 'desc' THEN f.id END DESC
LIMIT $16
`

type ListFilesAdvancedParams struct {
	UserID         int64              `json:"user_id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	Status         FileStatus         `json:"status"`
	Kind           NullFileKind       `json:"kind"`
	Search         pgtype.Text        `json:"search"`
	SearchType     string             `json:"search_type"`
	Categories     []string           `json:"categories"`
	UpdatedAfter   pgtype.Timestamptz `json:"updated_after"`
	UpdatedBefore  pgtype.Timestamptz `json:"updated_before"`
	AfterID        pgtype.UUID        `json:"after_id"`
	SortBy         string             `json:"sort_by"`
	AfterName      pgtype.Text        `json:"after_name"`
	SortOrder      string             `json:"sort_order"`
	AfterUpdatedAt pgtype.Timestamptz `json:"after_updated_at"`
	AfterSize      pgtype.Int8        `json:"after_size"`
	PageSize       int32              `json:"page_size"`
}

func (q *Queries) ListFilesAdvanced(ctx context.Context, arg ListFilesAdvancedParams) ([]*File, error) {
	rows, err := q.db.Query(ctx, listFilesAdvanced,
		arg.UserID,
		arg.ParentID,
		arg.Status,
		arg.Kind,
		arg.Search,
		arg.SearchType,
		arg.Categories,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.AfterID,
		arg.SortBy,
		arg.AfterName,
		arg.SortOrder,
		arg.AfterUpdatedAt,
		arg.AfterSize,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadFileSubtree = `-- name: LoadFileSubtree :many
WITH RECURSIVE tree AS (
    SELECT f.id, f.user_id, f.parent_id, f.name, f.kind, f.mime_type, f.size, f.hash_algorithm, f.hash_value, f.encryption, f.encryption_key_version, f.status, f.mod_time, f.generation, f.created_at, f.updated_at, f.deleted_at, 0::integer AS depth
    FROM /* TEMPLATE: schema */files f
    WHERE f.id = $1 AND f.user_id = $2
    UNION ALL
    SELECT child.id, child.user_id, child.parent_id, child.name, child.kind, child.mime_type, child.size, child.hash_algorithm, child.hash_value, child.encryption, child.encryption_key_version, child.status, child.mod_time, child.generation, child.created_at, child.updated_at, child.deleted_at, tree.depth + 1
    FROM /* TEMPLATE: schema */files child
    JOIN tree ON child.parent_id = tree.id
    WHERE child.user_id = $2
)
SELECT id, user_id, parent_id, name, kind, mime_type, size,
       hash_algorithm, hash_value, encryption, encryption_key_version, status,
       mod_time, generation, created_at, updated_at, deleted_at, depth
FROM tree
ORDER BY depth, id
`

type LoadFileSubtreeParams struct {
	RootID pgtype.UUID `json:"root_id"`
	UserID int64       `json:"user_id"`
}

type LoadFileSubtreeRow struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               int64              `json:"user_id"`
	ParentID             pgtype.UUID        `json:"parent_id"`
	Name                 string             `json:"name"`
	Kind                 FileKind           `json:"kind"`
	MimeType             pgtype.Text        `json:"mime_type"`
	Size                 pgtype.Int8        `json:"size"`
	HashAlgorithm        pgtype.Text        `json:"hash_algorithm"`
	HashValue            pgtype.Text        `json:"hash_value"`
	Encryption           bool               `json:"encryption"`
	EncryptionKeyVersion pgtype.Int4        `json:"encryption_key_version"`
	Status               FileStatus         `json:"status"`
	ModTime              pgtype.Timestamptz `json:"mod_time"`
	Generation           int64              `json:"generation"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	Depth                int32              `json:"depth"`
}

func (q *Queries) LoadFileSubtree(ctx context.Context, arg LoadFileSubtreeParams) ([]*LoadFileSubtreeRow, error) {
	rows, err := q.db.Query(ctx, loadFileSubtree, arg.RootID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*LoadFileSubtreeRow{}
	for rows.Next() {
		var i LoadFileSubtreeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadFileSubtrees = `-- name: LoadFileSubtrees :many
WITH RECURSIVE tree AS (
    SELECT f.id, f.user_id, f.parent_id, f.name, f.kind, f.mime_type, f.size, f.hash_algorithm, f.hash_value, f.encryption, f.encryption_key_version, f.status, f.mod_time, f.generation, f.created_at, f.updated_at, f.deleted_at, 0::integer AS depth
    FROM /* TEMPLATE: schema */files f
    WHERE f.id = ANY($1::uuid[])
      AND f.user_id = $2
    UNION ALL
    SELECT child.id, child.user_id, child.parent_id, child.name, child.kind, child.mime_type, child.size, child.hash_algorithm, child.hash_value, child.encryption, child.encryption_key_version, child.status, child.mod_time, child.generation, child.created_at, child.updated_at, child.deleted_at, tree.depth + 1
    FROM /* TEMPLATE: schema */files child
    JOIN tree ON child.parent_id = tree.id
    WHERE child.user_id = $2
)
SELECT id, user_id, parent_id, name, kind, mime_type, size,
       hash_algorithm, hash_value, encryption, encryption_key_version, status,
       mod_time, generation, created_at, updated_at, deleted_at, depth
FROM tree
ORDER BY depth, id
`

type LoadFileSubtreesParams struct {
	RootIds []pgtype.UUID `json:"root_ids"`
	UserID  int64         `json:"user_id"`
}

type LoadFileSubtreesRow struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               int64              `json:"user_id"`
	ParentID             pgtype.UUID        `json:"parent_id"`
	Name                 string             `json:"name"`
	Kind                 FileKind           `json:"kind"`
	MimeType             pgtype.Text        `json:"mime_type"`
	Size                 pgtype.Int8        `json:"size"`
	HashAlgorithm        pgtype.Text        `json:"hash_algorithm"`
	HashValue            pgtype.Text        `json:"hash_value"`
	Encryption           bool               `json:"encryption"`
	EncryptionKeyVersion pgtype.Int4        `json:"encryption_key_version"`
	Status               FileStatus         `json:"status"`
	ModTime              pgtype.Timestamptz `json:"mod_time"`
	Generation           int64              `json:"generation"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	Depth                int32              `json:"depth"`
}

func (q *Queries) LoadFileSubtrees(ctx context.Context, arg LoadFileSubtreesParams) ([]*LoadFileSubtreesRow, error) {
	rows, err := q.db.Query(ctx, loadFileSubtrees, arg.RootIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*LoadFileSubtreesRow{}
	for rows.Next() {
		var i LoadFileSubtreesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveDestinationEntries = `-- name: LockActiveDestinationEntries :many
SELECT id, name
FROM /* TEMPLATE: schema */files
WHERE user_id = $1
  AND parent_id IS NOT DISTINCT FROM $2::uuid
  AND status = 'active'
FOR UPDATE
`

type LockActiveDestinationEntriesParams struct {
	UserID   int64       `json:"user_id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

type LockActiveDestinationEntriesRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) LockActiveDestinationEntries(ctx context.Context, arg LockActiveDestinationEntriesParams) ([]*LockActiveDestinationEntriesRow, error) {
	rows, err := q.db.Query(ctx, lockActiveDestinationEntries, arg.UserID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*LockActiveDestinationEntriesRow{}
	for rows.Next() {
		var i LockActiveDestinationEntriesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveFiles = `-- name: LockActiveFiles :many
SELECT id, user_id, parent_id, name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
FROM /* TEMPLATE: schema */files
WHERE user_id = $1
  AND id = ANY($2::uuid[])
  AND status = 'active'
FOR UPDATE
`

type LockActiveFilesParams struct {
	UserID  int64         `json:"user_id"`
	FileIds []pgtype.UUID `json:"file_ids"`
}

func (q *Queries) LockActiveFiles(ctx context.Context, arg LockActiveFilesParams) ([]*File, error) {
	rows, err := q.db.Query(ctx, lockActiveFiles, arg.UserID, arg.FileIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveFolder = `-- name: LockActiveFolder :one
SELECT id, user_id, parent_id, name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
FROM /* TEMPLATE: schema */files
WHERE id = $1
  AND user_id = $2
  AND kind = 'folder'
  AND status = 'active'
FOR UPDATE
`

type LockActiveFolderParams struct {
	FolderID pgtype.UUID `json:"folder_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) LockActiveFolder(ctx context.Context, arg LockActiveFolderParams) (*File, error) {
	row := q.db.QueryRow(ctx, lockActiveFolder, arg.FolderID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const markAllTrashedDeletionPending = `-- name: MarkAllTrashedDeletionPending :execrows
UPDATE /* TEMPLATE: schema */files
SET status = 'deletion_pending',
    deleted_at = COALESCE(deleted_at, now()),
    updated_at = now()
WHERE user_id = $1
  AND status = 'trashed'
`

func (q *Queries) MarkAllTrashedDeletionPending(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, markAllTrashedDeletionPending, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markFileDeletionPending = `-- name: MarkFileDeletionPending :one
UPDATE /* TEMPLATE: schema */files
SET status = 'deletion_pending',
    deleted_at = COALESCE(deleted_at, now()),
    generation = generation + 1,
    updated_at = now()
WHERE id = $1
  AND user_id = $2
  AND status = 'trashed'
RETURNING id, user_id, parent_id, name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
`

type MarkFileDeletionPendingParams struct {
	FileID pgtype.UUID `json:"file_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) MarkFileDeletionPending(ctx context.Context, arg MarkFileDeletionPendingParams) (*File, error) {
	row := q.db.QueryRow(ctx, markFileDeletionPending, arg.FileID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const markFileIDsDeletionPending = `-- name: MarkFileIDsDeletionPending :exec
UPDATE /* TEMPLATE: schema */files
SET status = 'deletion_pending',
    deleted_at = COALESCE(deleted_at, now()),
    updated_at = now()
WHERE user_id = $1
  AND id = ANY($2::uuid[])
`

type MarkFileIDsDeletionPendingParams struct {
	UserID  int64         `json:"user_id"`
	FileIds []pgtype.UUID `json:"file_ids"`
}

func (q *Queries) MarkFileIDsDeletionPending(ctx context.Context, arg MarkFileIDsDeletionPendingParams) error {
	_, err := q.db.Exec(ctx, markFileIDsDeletionPending, arg.UserID, arg.FileIds)
	return err
}

const markFileSubtreeDeletionPending = `-- name: MarkFileSubtreeDeletionPending :exec
WITH RECURSIVE target AS (
  SELECT root.id FROM /* TEMPLATE: schema */files root WHERE root.id = $2 AND root.user_id = $1 AND root.status = 'active'
  UNION ALL
  SELECT child.id FROM /* TEMPLATE: schema */files child JOIN target parent ON child.parent_id = parent.id WHERE child.user_id = $1 AND child.status = 'active'
)
UPDATE /* TEMPLATE: schema */files AS target_file
SET status = 'deletion_pending',
    deleted_at = COALESCE(target_file.deleted_at, now()),
    generation = target_file.generation + 1,
    updated_at = now()
WHERE target_file.user_id = $1 AND target_file.id IN (SELECT target.id FROM target)
`

type MarkFileSubtreeDeletionPendingParams struct {
	UserID int64       `json:"user_id"`
	FileID pgtype.UUID `json:"file_id"`
}

func (q *Queries) MarkFileSubtreeDeletionPending(ctx context.Context, arg MarkFileSubtreeDeletionPendingParams) error {
	_, err := q.db.Exec(ctx, markFileSubtreeDeletionPending, arg.UserID, arg.FileID)
	return err
}

const markFileSubtreesDeletionPending = `-- name: MarkFileSubtreesDeletionPending :exec
WITH RECURSIVE target AS (
  SELECT root.id
  FROM /* TEMPLATE: schema */files AS root
  WHERE root.id = ANY($2::uuid[])
    AND root.user_id = $1
    AND root.status = 'active'
  UNION
  SELECT child.id
  FROM /* TEMPLATE: schema */files AS child
  JOIN target AS parent ON child.parent_id = parent.id
  WHERE child.user_id = $1
    AND child.status = 'active'
)
UPDATE /* TEMPLATE: schema */files AS target_file
SET status = 'deletion_pending',
    deleted_at = COALESCE(target_file.deleted_at, now()),
    generation = target_file.generation + 1,
    updated_at = now()
WHERE target_file.user_id = $1
  AND target_file.id IN (SELECT target.id FROM target)
`

type MarkFileSubtreesDeletionPendingParams struct {
	UserID  int64         `json:"user_id"`
	FileIds []pgtype.UUID `json:"file_ids"`
}

func (q *Queries) MarkFileSubtreesDeletionPending(ctx context.Context, arg MarkFileSubtreesDeletionPendingParams) error {
	_, err := q.db.Exec(ctx, markFileSubtreesDeletionPending, arg.UserID, arg.FileIds)
	return err
}

const moveFile = `-- name: MoveFile :one
UPDATE /* TEMPLATE: schema */files
SET parent_id = $1,
    generation = generation + 1,
    updated_at = now()
WHERE id = $2
  AND user_id = $3
  AND status = 'active'
  AND (
    $4::bigint IS NULL
    OR generation = $4::bigint
  )
RETURNING id, user_id, parent_id, name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
`

type MoveFileParams struct {
	ParentID           pgtype.UUID `json:"parent_id"`
	FileID             pgtype.UUID `json:"file_id"`
	UserID             int64       `json:"user_id"`
	ExpectedGeneration pgtype.Int8 `json:"expected_generation"`
}

func (q *Queries) MoveFile(ctx context.Context, arg MoveFileParams) (*File, error) {
	row := q.db.QueryRow(ctx, moveFile,
		arg.ParentID,
		arg.FileID,
		arg.UserID,
		arg.ExpectedGeneration,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const moveFilesWithNames = `-- name: MoveFilesWithNames :many
WITH arrays AS (
  SELECT $4::uuid[] AS file_ids,
         $5::text[] AS names
), input AS (
  SELECT arrays.file_ids[index] AS file_id,
         arrays.names[index] AS name
  FROM arrays
  CROSS JOIN LATERAL generate_subscripts(arrays.file_ids, 1) AS index
)
UPDATE /* TEMPLATE: schema */files AS file
SET parent_id = $1,
    name = input.name,
    generation = file.generation + 1,
    updated_at = now()
FROM input
WHERE file.id = input.file_id
  AND file.user_id = $2
  AND file.status = 'active'
  AND ($3::bigint IS NULL OR file.generation = $3::bigint)
RETURNING file.id, file.user_id, file.parent_id, file.name, file.kind, file.mime_type, file.size, file.hash_algorithm, file.hash_value, file.encryption, file.encryption_key_version, file.status, file.mod_time, file.generation, file.created_at, file.updated_at, file.deleted_at
`

type MoveFilesWithNamesParams struct {
	ParentID           pgtype.UUID   `json:"parent_id"`
	UserID             int64         `json:"user_id"`
	ExpectedGeneration pgtype.Int8   `json:"expected_generation"`
	FileIds            []pgtype.UUID `json:"file_ids"`
	Names              []string      `json:"names"`
}

func (q *Queries) MoveFilesWithNames(ctx context.Context, arg MoveFilesWithNamesParams) ([]*File, error) {
	rows, err := q.db.Query(ctx, moveFilesWithNames,
		arg.ParentID,
		arg.UserID,
		arg.ExpectedGeneration,
		arg.FileIds,
		arg.Names,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueFileSubtreePurge = `-- name: QueueFileSubtreePurge :many
WITH RECURSIVE target AS (
  SELECT root.id
  FROM /* TEMPLATE: schema */files root
  WHERE root.id = $2
    AND root.user_id = $1
    AND root.status = 'trashed'
  UNION ALL
  SELECT child.id
  FROM /* TEMPLATE: schema */files child
  JOIN target parent ON child.parent_id = parent.id
  WHERE child.user_id = $1
)
UPDATE /* TEMPLATE: schema */files AS target_file
SET status = 'deletion_pending',
    deleted_at = COALESCE(target_file.deleted_at, now()),
    updated_at = now()
WHERE target_file.user_id = $1
  AND target_file.id IN (SELECT target.id FROM target)
RETURNING target_file.id, target_file.user_id, target_file.parent_id, target_file.name, target_file.kind, target_file.mime_type, target_file.size, target_file.hash_algorithm, target_file.hash_value, target_file.encryption, target_file.encryption_key_version, target_file.status, target_file.mod_time, target_file.generation, target_file.created_at, target_file.updated_at, target_file.deleted_at
`

type QueueFileSubtreePurgeParams struct {
	UserID int64       `json:"user_id"`
	FileID pgtype.UUID `json:"file_id"`
}

func (q *Queries) QueueFileSubtreePurge(ctx context.Context, arg QueueFileSubtreePurgeParams) ([]*File, error) {
	rows, err := q.db.Query(ctx, queueFileSubtreePurge, arg.UserID, arg.FileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveActiveChild = `-- name: ResolveActiveChild :one
SELECT id, user_id, parent_id, name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
FROM /* TEMPLATE: schema */files
WHERE user_id = $1
  AND parent_id IS NOT DISTINCT FROM $2::uuid
  AND name = $3
  AND status = 'active'
`

type ResolveActiveChildParams struct {
	UserID   int64       `json:"user_id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
}

func (q *Queries) ResolveActiveChild(ctx context.Context, arg ResolveActiveChildParams) (*File, error) {
	row := q.db.QueryRow(ctx, resolveActiveChild, arg.UserID, arg.ParentID, arg.Name)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const resolveActiveChildFolder = `-- name: ResolveActiveChildFolder :one
SELECT id
FROM /* TEMPLATE: schema */files
WHERE user_id = $1
  AND parent_id IS NOT DISTINCT FROM $2::uuid
  AND name = $3
  AND kind = 'folder'
  AND status = 'active'
`

type ResolveActiveChildFolderParams struct {
	UserID   int64       `json:"user_id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
}

func (q *Queries) ResolveActiveChildFolder(ctx context.Context, arg ResolveActiveChildFolderParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveActiveChildFolder, arg.UserID, arg.ParentID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const restoreFileSubtree = `-- name: RestoreFileSubtree :many
WITH RECURSIVE target AS (
  SELECT root.id
  FROM /* TEMPLATE: schema */files root
  WHERE root.id = $2
    AND root.user_id = $1
    AND root.status = 'trashed'
    AND (
      root.parent_id IS NULL
      OR EXISTS (
        SELECT 1
        FROM /* TEMPLATE: schema */files parent
        WHERE parent.id = root.parent_id
          AND parent.user_id = root.user_id
          AND parent.status = 'active'
      )
    )
  UNION ALL
  SELECT child.id
  FROM /* TEMPLATE: schema */files child
  JOIN target parent ON child.parent_id = parent.id
  WHERE child.user_id = $1
    AND child.status = 'trashed'
)
UPDATE /* TEMPLATE: schema */files AS target_file
SET status = 'active',
    deleted_at = NULL,
    generation = target_file.generation + 1,
    updated_at = now()
WHERE target_file.user_id = $1
  AND target_file.id IN (SELECT target.id FROM target)
RETURNING target_file.id, target_file.user_id, target_file.parent_id, target_file.name, target_file.kind, target_file.mime_type, target_file.size, target_file.hash_algorithm, target_file.hash_value, target_file.encryption, target_file.encryption_key_version, target_file.status, target_file.mod_time, target_file.generation, target_file.created_at, target_file.updated_at, target_file.deleted_at
`

type RestoreFileSubtreeParams struct {
	UserID int64       `json:"user_id"`
	FileID pgtype.UUID `json:"file_id"`
}

func (q *Queries) RestoreFileSubtree(ctx context.Context, arg RestoreFileSubtreeParams) ([]*File, error) {
	rows, err := q.db.Query(ctx, restoreFileSubtree, arg.UserID, arg.FileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSharesForFileSubtree = `-- name: RevokeSharesForFileSubtree :exec
WITH RECURSIVE target AS (
  SELECT root.id FROM /* TEMPLATE: schema */files root WHERE root.id = $2 AND root.user_id = $1
  UNION ALL
  SELECT child.id FROM /* TEMPLATE: schema */files child JOIN target parent ON child.parent_id = parent.id WHERE child.user_id = $1
)
UPDATE /* TEMPLATE: schema */file_shares AS share
SET revoked_at = COALESCE(share.revoked_at, now())
WHERE share.owner_id = $1
  AND share.revoked_at IS NULL
  AND share.file_id IN (SELECT target.id FROM target)
`

type RevokeSharesForFileSubtreeParams struct {
	UserID int64       `json:"user_id"`
	FileID pgtype.UUID `json:"file_id"`
}

func (q *Queries) RevokeSharesForFileSubtree(ctx context.Context, arg RevokeSharesForFileSubtreeParams) error {
	_, err := q.db.Exec(ctx, revokeSharesForFileSubtree, arg.UserID, arg.FileID)
	return err
}

const revokeSharesForFileSubtrees = `-- name: RevokeSharesForFileSubtrees :exec
WITH RECURSIVE target AS (
  SELECT root.id FROM /* TEMPLATE: schema */files root WHERE root.user_id = $1 AND root.id = ANY($2::uuid[])
  UNION
  SELECT child.id FROM /* TEMPLATE: schema */files child JOIN target parent ON child.parent_id = parent.id WHERE child.user_id = $1
)
UPDATE /* TEMPLATE: schema */file_shares AS share
SET revoked_at = COALESCE(share.revoked_at, now())
WHERE share.owner_id = $1
  AND share.revoked_at IS NULL
  AND share.file_id IN (SELECT target.id FROM target)
`

type RevokeSharesForFileSubtreesParams struct {
	UserID  int64         `json:"user_id"`
	FileIds []pgtype.UUID `json:"file_ids"`
}

func (q *Queries) RevokeSharesForFileSubtrees(ctx context.Context, arg RevokeSharesForFileSubtreesParams) error {
	_, err := q.db.Exec(ctx, revokeSharesForFileSubtrees, arg.UserID, arg.FileIds)
	return err
}

const sumFilePartSizes = `-- name: SumFilePartSizes :one
SELECT
    COALESCE(sum(plain_size), 0)::bigint AS plain_size,
    COALESCE(sum(stored_size), 0)::bigint AS stored_size,
    count(*)::integer AS part_count
FROM /* TEMPLATE: schema */file_parts
WHERE file_id = $1
`

type SumFilePartSizesRow struct {
	PlainSize  int64 `json:"plain_size"`
	StoredSize int64 `json:"stored_size"`
	PartCount  int32 `json:"part_count"`
}

func (q *Queries) SumFilePartSizes(ctx context.Context, fileID pgtype.UUID) (*SumFilePartSizesRow, error) {
	row := q.db.QueryRow(ctx, sumFilePartSizes, fileID)
	var i SumFilePartSizesRow
	err := row.Scan(&i.PlainSize, &i.StoredSize, &i.PartCount)
	return &i, err
}

const trashFile = `-- name: TrashFile :one
UPDATE /* TEMPLATE: schema */files
SET status = 'trashed',
    deleted_at = now(),
    generation = generation + 1,
    updated_at = now()
WHERE id = $1
  AND user_id = $2
  AND status = 'active'
RETURNING id, user_id, parent_id, name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
`

type TrashFileParams struct {
	FileID pgtype.UUID `json:"file_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) TrashFile(ctx context.Context, arg TrashFileParams) (*File, error) {
	row := q.db.QueryRow(ctx, trashFile, arg.FileID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const trashFileSubtrees = `-- name: TrashFileSubtrees :many
WITH RECURSIVE target AS (
  SELECT root.id
  FROM /* TEMPLATE: schema */files root
  WHERE root.user_id = $1
    AND root.id = ANY($2::uuid[])
    AND root.status = 'active'
  UNION
  SELECT child.id
  FROM /* TEMPLATE: schema */files child
  JOIN target parent ON child.parent_id = parent.id
  WHERE child.user_id = $1
    AND child.status = 'active'
)
UPDATE /* TEMPLATE: schema */files AS target_file
SET status = 'trashed',
    deleted_at = now(),
    generation = target_file.generation + 1,
    updated_at = now()
WHERE target_file.user_id = $1
  AND target_file.id IN (SELECT target.id FROM target)
RETURNING target_file.id, target_file.user_id, target_file.parent_id, target_file.name, target_file.kind, target_file.mime_type, target_file.size, target_file.hash_algorithm, target_file.hash_value, target_file.encryption, target_file.encryption_key_version, target_file.status, target_file.mod_time, target_file.generation, target_file.created_at, target_file.updated_at, target_file.deleted_at
`

type TrashFileSubtreesParams struct {
	UserID  int64         `json:"user_id"`
	FileIds []pgtype.UUID `json:"file_ids"`
}

func (q *Queries) TrashFileSubtrees(ctx context.Context, arg TrashFileSubtreesParams) ([]*File, error) {
	rows, err := q.db.Query(ctx, trashFileSubtrees, arg.UserID, arg.FileIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Kind,
			&i.MimeType,
			&i.Size,
			&i.HashAlgorithm,
			&i.HashValue,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.Status,
			&i.ModTime,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileMetadata = `-- name: UpdateFileMetadata :one
UPDATE /* TEMPLATE: schema */files
SET name = COALESCE($1, name),
    mod_time = COALESCE($2, mod_time),
    generation = generation + 1,
    updated_at = now()
WHERE id = $3
  AND user_id = $4
  AND status = 'active'
  AND (
    $5::bigint IS NULL
    OR generation = $5::bigint
  )
RETURNING id, user_id, parent_id, name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
`

type UpdateFileMetadataParams struct {
	Name               pgtype.Text        `json:"name"`
	ModTime            pgtype.Timestamptz `json:"mod_time"`
	FileID             pgtype.UUID        `json:"file_id"`
	UserID             int64              `json:"user_id"`
	ExpectedGeneration pgtype.Int8        `json:"expected_generation"`
}

func (q *Queries) UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) (*File, error) {
	row := q.db.QueryRow(ctx, updateFileMetadata,
		arg.Name,
		arg.ModTime,
		arg.FileID,
		arg.UserID,
		arg.ExpectedGeneration,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateFilePartSizes = `-- name: UpdateFilePartSizes :execrows
UPDATE /* TEMPLATE: schema */file_parts
SET plain_size = $1,
    stored_size = $2
WHERE file_id = $3
  AND part_no = $4
  AND (plain_size IS NULL OR stored_size IS NULL)
`

type UpdateFilePartSizesParams struct {
	PlainSize  pgtype.Int8 `json:"plain_size"`
	StoredSize pgtype.Int8 `json:"stored_size"`
	FileID     pgtype.UUID `json:"file_id"`
	PartNo     int32       `json:"part_no"`
}

func (q *Queries) UpdateFilePartSizes(ctx context.Context, arg UpdateFilePartSizesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFilePartSizes,
		arg.PlainSize,
		arg.StoredSize,
		arg.FileID,
		arg.PartNo,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFilePartSizesMany = `-- name: UpdateFilePartSizesMany :execrows
UPDATE /* TEMPLATE: schema */file_parts AS part
SET plain_size = input.plain_size,
    stored_size = input.stored_size
FROM jsonb_to_recordset($2::jsonb) AS input(
    part_no integer, plain_size bigint, stored_size bigint
)
WHERE part.file_id = $1
  AND part.part_no = input.part_no
  AND (part.plain_size IS NULL OR part.stored_size IS NULL)
`

type UpdateFilePartSizesManyParams struct {
	FileID pgtype.UUID `json:"file_id"`
	Parts  []byte      `json:"parts"`
}

func (q *Queries) UpdateFilePartSizesMany(ctx context.Context, arg UpdateFilePartSizesManyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFilePartSizesMany, arg.FileID, arg.Parts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
