// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :one
UPDATE /* TEMPLATE: schema */idempotency_keys
SET resource_type = $1,
    resource_id = $2,
    response_ciphertext = $3,
    completed_at = now()
WHERE user_id = $4
  AND scope = $5
  AND key = $6
  AND request_hash = $7
RETURNING user_id, scope, key, request_hash, resource_type, resource_id, response_ciphertext, completed_at, expires_at, created_at
`

type CompleteIdempotencyKeyParams struct {
	ResourceType       pgtype.Text `json:"resource_type"`
	ResourceID         pgtype.Text `json:"resource_id"`
	ResponseCiphertext []byte      `json:"response_ciphertext"`
	UserID             int64       `json:"user_id"`
	Scope              string      `json:"scope"`
	Key                pgtype.UUID `json:"key"`
	RequestHash        []byte      `json:"request_hash"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (*IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, completeIdempotencyKey,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResponseCiphertext,
		arg.UserID,
		arg.Scope,
		arg.Key,
		arg.RequestHash,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.UserID,
		&i.Scope,
		&i.Key,
		&i.RequestHash,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResponseCiphertext,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM /* TEMPLATE: schema */idempotency_keys
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT user_id, scope, key, request_hash, resource_type, resource_id, response_ciphertext, completed_at, expires_at, created_at
FROM /* TEMPLATE: schema */idempotency_keys
WHERE user_id = $1
  AND scope = $2
  AND key = $3
  AND expires_at > now()
`

type GetIdempotencyKeyParams struct {
	UserID int64       `json:"user_id"`
	Scope  string      `json:"scope"`
	Key    pgtype.UUID `json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (*IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.Scope, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.UserID,
		&i.Scope,
		&i.Key,
		&i.RequestHash,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResponseCiphertext,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}

const reserveIdempotencyKey = `-- name: ReserveIdempotencyKey :one
INSERT INTO /* TEMPLATE: schema */idempotency_keys (
    user_id,
    scope,
    key,
    request_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (user_id, scope, key) DO NOTHING
RETURNING user_id, scope, key, request_hash, resource_type, resource_id, response_ciphertext, completed_at, expires_at, created_at
`

type ReserveIdempotencyKeyParams struct {
	UserID      int64              `json:"user_id"`
	Scope       string             `json:"scope"`
	Key         pgtype.UUID        `json:"key"`
	RequestHash []byte             `json:"request_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ReserveIdempotencyKey(ctx context.Context, arg ReserveIdempotencyKeyParams) (*IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, reserveIdempotencyKey,
		arg.UserID,
		arg.Scope,
		arg.Key,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.UserID,
		&i.Scope,
		&i.Key,
		&i.RequestHash,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResponseCiphertext,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}
