// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChannelHealth string

const (
	ChannelHealthUnknown     ChannelHealth = "unknown"
	ChannelHealthHealthy     ChannelHealth = "healthy"
	ChannelHealthDegraded    ChannelHealth = "degraded"
	ChannelHealthUnavailable ChannelHealth = "unavailable"
)

func (e *ChannelHealth) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChannelHealth(s)
	case string:
		*e = ChannelHealth(s)
	default:
		return fmt.Errorf("unsupported scan type for ChannelHealth: %T", src)
	}
	return nil
}

type NullChannelHealth struct {
	ChannelHealth ChannelHealth `json:"channel_health"`
	Valid         bool          `json:"valid"` // Valid is true if ChannelHealth is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChannelHealth) Scan(value interface{}) error {
	if value == nil {
		ns.ChannelHealth, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChannelHealth.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChannelHealth) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChannelHealth), nil
}

type FileKind string

const (
	FileKindFile   FileKind = "file"
	FileKindFolder FileKind = "folder"
)

func (e *FileKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileKind(s)
	case string:
		*e = FileKind(s)
	default:
		return fmt.Errorf("unsupported scan type for FileKind: %T", src)
	}
	return nil
}

type NullFileKind struct {
	FileKind FileKind `json:"file_kind"`
	Valid    bool     `json:"valid"` // Valid is true if FileKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileKind) Scan(value interface{}) error {
	if value == nil {
		ns.FileKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileKind), nil
}

type FileStatus string

const (
	FileStatusActive          FileStatus = "active"
	FileStatusTrashed         FileStatus = "trashed"
	FileStatusDeletionPending FileStatus = "deletion_pending"
)

func (e *FileStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileStatus(s)
	case string:
		*e = FileStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FileStatus: %T", src)
	}
	return nil
}

type NullFileStatus struct {
	FileStatus FileStatus `json:"file_status"`
	Valid      bool       `json:"valid"` // Valid is true if FileStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FileStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileStatus), nil
}

type NameConflictPolicy string

const (
	NameConflictPolicyFail    NameConflictPolicy = "fail"
	NameConflictPolicyReplace NameConflictPolicy = "replace"
	NameConflictPolicyRename  NameConflictPolicy = "rename"
)

func (e *NameConflictPolicy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NameConflictPolicy(s)
	case string:
		*e = NameConflictPolicy(s)
	default:
		return fmt.Errorf("unsupported scan type for NameConflictPolicy: %T", src)
	}
	return nil
}

type NullNameConflictPolicy struct {
	NameConflictPolicy NameConflictPolicy `json:"name_conflict_policy"`
	Valid              bool               `json:"valid"` // Valid is true if NameConflictPolicy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNameConflictPolicy) Scan(value interface{}) error {
	if value == nil {
		ns.NameConflictPolicy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NameConflictPolicy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNameConflictPolicy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NameConflictPolicy), nil
}

type TelegramLoginMethod string

const (
	TelegramLoginMethodPhone TelegramLoginMethod = "phone"
	TelegramLoginMethodQr    TelegramLoginMethod = "qr"
)

func (e *TelegramLoginMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TelegramLoginMethod(s)
	case string:
		*e = TelegramLoginMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for TelegramLoginMethod: %T", src)
	}
	return nil
}

type NullTelegramLoginMethod struct {
	TelegramLoginMethod TelegramLoginMethod `json:"telegram_login_method"`
	Valid               bool                `json:"valid"` // Valid is true if TelegramLoginMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTelegramLoginMethod) Scan(value interface{}) error {
	if value == nil {
		ns.TelegramLoginMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TelegramLoginMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTelegramLoginMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TelegramLoginMethod), nil
}

type UploadPartState string

const (
	UploadPartStateReserved  UploadPartState = "reserved"
	UploadPartStateUploading UploadPartState = "uploading"
	UploadPartStateStored    UploadPartState = "stored"
	UploadPartStateFailed    UploadPartState = "failed"
)

func (e *UploadPartState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UploadPartState(s)
	case string:
		*e = UploadPartState(s)
	default:
		return fmt.Errorf("unsupported scan type for UploadPartState: %T", src)
	}
	return nil
}

type NullUploadPartState struct {
	UploadPartState UploadPartState `json:"upload_part_state"`
	Valid           bool            `json:"valid"` // Valid is true if UploadPartState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUploadPartState) Scan(value interface{}) error {
	if value == nil {
		ns.UploadPartState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UploadPartState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUploadPartState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UploadPartState), nil
}

type UploadState string

const (
	UploadStateOpen       UploadState = "open"
	UploadStateCompleting UploadState = "completing"
	UploadStateCompleted  UploadState = "completed"
	UploadStateAborted    UploadState = "aborted"
	UploadStateExpired    UploadState = "expired"
)

func (e *UploadState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UploadState(s)
	case string:
		*e = UploadState(s)
	default:
		return fmt.Errorf("unsupported scan type for UploadState: %T", src)
	}
	return nil
}

type NullUploadState struct {
	UploadState UploadState `json:"upload_state"`
	Valid       bool        `json:"valid"` // Valid is true if UploadState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUploadState) Scan(value interface{}) error {
	if value == nil {
		ns.UploadState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UploadState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUploadState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UploadState), nil
}

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	SecretHash []byte             `json:"secret_hash"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditEvent struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.Int8        `json:"user_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	Metadata     []byte             `json:"metadata"`
	RequestID    pgtype.Text        `json:"request_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Bot struct {
	BotID               int64              `json:"bot_id"`
	UserID              int64              `json:"user_id"`
	Username            pgtype.Text        `json:"username"`
	TokenCiphertext     []byte             `json:"token_ciphertext"`
	Enabled             bool               `json:"enabled"`
	Session             []byte             `json:"session"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastError           pgtype.Text        `json:"last_error"`
	LastUsedAt          pgtype.Timestamptz `json:"last_used_at"`
	RetryAfter          pgtype.Timestamptz `json:"retry_after"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type BotSelectionCounter struct {
	UserID    int64              `json:"user_id"`
	Operation string             `json:"operation"`
	NextValue int64              `json:"next_value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Channel struct {
	ChannelID     int64              `json:"channel_id"`
	UserID        int64              `json:"user_id"`
	Name          string             `json:"name"`
	Selected      bool               `json:"selected"`
	Health        ChannelHealth      `json:"health"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type EventStreamTicket struct {
	TokenHash []byte             `json:"token_hash"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type File struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               int64              `json:"user_id"`
	ParentID             pgtype.UUID        `json:"parent_id"`
	Name                 string             `json:"name"`
	NormalizedName       string             `json:"normalized_name"`
	Kind                 FileKind           `json:"kind"`
	MimeType             pgtype.Text        `json:"mime_type"`
	Size                 pgtype.Int8        `json:"size"`
	HashAlgorithm        pgtype.Text        `json:"hash_algorithm"`
	HashValue            pgtype.Text        `json:"hash_value"`
	Encryption           bool               `json:"encryption"`
	EncryptionKeyVersion pgtype.Int4        `json:"encryption_key_version"`
	Status               FileStatus         `json:"status"`
	ModTime              pgtype.Timestamptz `json:"mod_time"`
	Generation           int64              `json:"generation"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type FilePart struct {
	FileID     pgtype.UUID        `json:"file_id"`
	PartNo     int32              `json:"part_no"`
	ChannelID  int64              `json:"channel_id"`
	MessageID  int64              `json:"message_id"`
	PlainSize  pgtype.Int8        `json:"plain_size"`
	StoredSize pgtype.Int8        `json:"stored_size"`
	Checksum   pgtype.Text        `json:"checksum"`
	Salt       pgtype.Text        `json:"salt"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	// Concatenated 32-byte BLAKE3 hashes for each 16 MiB plaintext block in this finalized part.
	BlockHashes []byte `json:"block_hashes"`
}

type FileShare struct {
	ID            pgtype.UUID        `json:"id"`
	FileID        pgtype.UUID        `json:"file_id"`
	OwnerID       int64              `json:"owner_id"`
	TokenPrefix   string             `json:"token_prefix"`
	TokenHash     []byte             `json:"token_hash"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	MaxDownloads  pgtype.Int8        `json:"max_downloads"`
	DownloadCount int64              `json:"download_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
}

type FileViewState struct {
	UserID      int64              `json:"user_id"`
	FileID      pgtype.UUID        `json:"file_id"`
	ViewerKind  string             `json:"viewer_kind"`
	Position    []byte             `json:"position"`
	Preferences []byte             `json:"preferences"`
	Bookmarks   []byte             `json:"bookmarks"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type IdempotencyKey struct {
	UserID             int64              `json:"user_id"`
	Scope              string             `json:"scope"`
	Key                pgtype.UUID        `json:"key"`
	RequestHash        []byte             `json:"request_hash"`
	ResourceType       pgtype.Text        `json:"resource_type"`
	ResourceID         pgtype.Text        `json:"resource_id"`
	ResponseCiphertext []byte             `json:"response_ciphertext"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           int64              `json:"user_id"`
	TelegramSession  []byte             `json:"telegram_session"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type TelegramLoginFlow struct {
	ID                      pgtype.UUID         `json:"id"`
	Method                  TelegramLoginMethod `json:"method"`
	PhoneNumberCiphertext   []byte              `json:"phone_number_ciphertext"`
	TelegramStateCiphertext []byte              `json:"telegram_state_ciphertext"`
	PasswordRequired        bool                `json:"password_required"`
	ExpiresAt               pgtype.Timestamptz  `json:"expires_at"`
	CompletedAt             pgtype.Timestamptz  `json:"completed_at"`
	CreatedAt               pgtype.Timestamptz  `json:"created_at"`
}

type UploadPart struct {
	UploadID       pgtype.UUID        `json:"upload_id"`
	PartNo         int32              `json:"part_no"`
	ChannelID      int64              `json:"channel_id"`
	MessageID      pgtype.Int8        `json:"message_id"`
	PlainSize      int64              `json:"plain_size"`
	StoredSize     pgtype.Int8        `json:"stored_size"`
	Checksum       pgtype.Text        `json:"checksum"`
	Salt           pgtype.Text        `json:"salt"`
	State          UploadPartState    `json:"state"`
	LeaseToken     pgtype.UUID        `json:"lease_token"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	LastErrorCode  pgtype.Text        `json:"last_error_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	// Concatenated 32-byte BLAKE3 hashes for each 16 MiB plaintext block in this upload part.
	BlockHashes []byte `json:"block_hashes"`
}

type UploadSession struct {
	ID                    pgtype.UUID        `json:"id"`
	UserID                int64              `json:"user_id"`
	ParentID              pgtype.UUID        `json:"parent_id"`
	Name                  string             `json:"name"`
	NormalizedName        string             `json:"normalized_name"`
	ExpectedSize          int64              `json:"expected_size"`
	ExpectedHashAlgorithm pgtype.Text        `json:"expected_hash_algorithm"`
	ExpectedHashValue     pgtype.Text        `json:"expected_hash_value"`
	MimeType              pgtype.Text        `json:"mime_type"`
	ModTime               pgtype.Timestamptz `json:"mod_time"`
	Encryption            bool               `json:"encryption"`
	EncryptionKeyVersion  pgtype.Int4        `json:"encryption_key_version"`
	ConflictPolicy        NameConflictPolicy `json:"conflict_policy"`
	PartSize              int64              `json:"part_size"`
	State                 UploadState        `json:"state"`
	FileID                pgtype.UUID        `json:"file_id"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
}

type User struct {
	UserID      int64              `json:"user_id"`
	DisplayName pgtype.Text        `json:"display_name"`
	Username    pgtype.Text        `json:"username"`
	Premium     bool               `json:"premium"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserEvent struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	EventType    string             `json:"event_type"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	Generation   pgtype.Int8        `json:"generation"`
	Payload      []byte             `json:"payload"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
}

type UserEventStreamState struct {
	UserID      int64              `json:"user_id"`
	LastEventID int64              `json:"last_event_id"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
