// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFileShare = `-- name: CreateFileShare :one
INSERT INTO /* TEMPLATE: schema */file_shares (
    id,
    file_id,
    owner_id,
    token_prefix,
    token_hash,
    password_hash,
    expires_at,
    max_downloads
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, file_id, owner_id, token_prefix, token_hash, password_hash, expires_at, max_downloads, download_count, created_at, revoked_at
`

type CreateFileShareParams struct {
	ID           pgtype.UUID        `json:"id"`
	FileID       pgtype.UUID        `json:"file_id"`
	OwnerID      int64              `json:"owner_id"`
	TokenPrefix  string             `json:"token_prefix"`
	TokenHash    []byte             `json:"token_hash"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	MaxDownloads pgtype.Int8        `json:"max_downloads"`
}

func (q *Queries) CreateFileShare(ctx context.Context, arg CreateFileShareParams) (*FileShare, error) {
	row := q.db.QueryRow(ctx, createFileShare,
		arg.ID,
		arg.FileID,
		arg.OwnerID,
		arg.TokenPrefix,
		arg.TokenHash,
		arg.PasswordHash,
		arg.ExpiresAt,
		arg.MaxDownloads,
	)
	var i FileShare
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.OwnerID,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.MaxDownloads,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const getActiveShareByTokenHash = `-- name: GetActiveShareByTokenHash :one
SELECT fs.id, fs.file_id, fs.owner_id, fs.token_prefix, fs.token_hash, fs.password_hash, fs.expires_at, fs.max_downloads, fs.download_count, fs.created_at, fs.revoked_at, f.name AS file_name, f.kind AS file_kind, f.status AS file_status
FROM /* TEMPLATE: schema */file_shares fs
JOIN /* TEMPLATE: schema */files f ON f.id = fs.file_id
WHERE fs.token_hash = $1
  AND fs.revoked_at IS NULL
  AND (fs.expires_at IS NULL OR fs.expires_at > now())
  AND (fs.max_downloads IS NULL OR fs.download_count < fs.max_downloads)
  AND f.status = 'active'
`

type GetActiveShareByTokenHashRow struct {
	ID            pgtype.UUID        `json:"id"`
	FileID        pgtype.UUID        `json:"file_id"`
	OwnerID       int64              `json:"owner_id"`
	TokenPrefix   string             `json:"token_prefix"`
	TokenHash     []byte             `json:"token_hash"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	MaxDownloads  pgtype.Int8        `json:"max_downloads"`
	DownloadCount int64              `json:"download_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	FileName      string             `json:"file_name"`
	FileKind      FileKind           `json:"file_kind"`
	FileStatus    FileStatus         `json:"file_status"`
}

func (q *Queries) GetActiveShareByTokenHash(ctx context.Context, tokenHash []byte) (*GetActiveShareByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveShareByTokenHash, tokenHash)
	var i GetActiveShareByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.OwnerID,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.MaxDownloads,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.FileName,
		&i.FileKind,
		&i.FileStatus,
	)
	return &i, err
}

const getFileShareForOwner = `-- name: GetFileShareForOwner :one
SELECT id, file_id, owner_id, token_prefix, token_hash, password_hash, expires_at, max_downloads, download_count, created_at, revoked_at
FROM /* TEMPLATE: schema */file_shares
WHERE id = $1
  AND owner_id = $2
`

type GetFileShareForOwnerParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID int64       `json:"owner_id"`
}

func (q *Queries) GetFileShareForOwner(ctx context.Context, arg GetFileShareForOwnerParams) (*FileShare, error) {
	row := q.db.QueryRow(ctx, getFileShareForOwner, arg.ID, arg.OwnerID)
	var i FileShare
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.OwnerID,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.MaxDownloads,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const incrementShareDownloadCount = `-- name: IncrementShareDownloadCount :one
UPDATE /* TEMPLATE: schema */file_shares
SET download_count = download_count + 1
WHERE id = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
  AND (max_downloads IS NULL OR download_count < max_downloads)
RETURNING id, file_id, owner_id, token_prefix, token_hash, password_hash, expires_at, max_downloads, download_count, created_at, revoked_at
`

func (q *Queries) IncrementShareDownloadCount(ctx context.Context, id pgtype.UUID) (*FileShare, error) {
	row := q.db.QueryRow(ctx, incrementShareDownloadCount, id)
	var i FileShare
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.OwnerID,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.MaxDownloads,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const listFileShares = `-- name: ListFileShares :many
SELECT id, file_id, owner_id, token_prefix, token_hash, password_hash, expires_at, max_downloads, download_count, created_at, revoked_at
FROM /* TEMPLATE: schema */file_shares
WHERE owner_id = $1
  AND file_id = $2
  AND (
    $3::timestamptz IS NULL
    OR (created_at, id) < (
      $3::timestamptz,
      $4::uuid
    )
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListFileSharesParams struct {
	OwnerID        int64              `json:"owner_id"`
	FileID         pgtype.UUID        `json:"file_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	PageSize       int32              `json:"page_size"`
}

func (q *Queries) ListFileShares(ctx context.Context, arg ListFileSharesParams) ([]*FileShare, error) {
	rows, err := q.db.Query(ctx, listFileShares,
		arg.OwnerID,
		arg.FileID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FileShare{}
	for rows.Next() {
		var i FileShare
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.OwnerID,
			&i.TokenPrefix,
			&i.TokenHash,
			&i.PasswordHash,
			&i.ExpiresAt,
			&i.MaxDownloads,
			&i.DownloadCount,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeExpiredShares = `-- name: RevokeExpiredShares :execrows
UPDATE /* TEMPLATE: schema */file_shares
SET revoked_at = now()
WHERE revoked_at IS NULL
  AND expires_at IS NOT NULL
  AND expires_at <= now()
`

func (q *Queries) RevokeExpiredShares(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, revokeExpiredShares)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeFileShare = `-- name: RevokeFileShare :execrows
UPDATE /* TEMPLATE: schema */file_shares
SET revoked_at = now()
WHERE id = $1
  AND owner_id = $2
  AND revoked_at IS NULL
`

type RevokeFileShareParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID int64       `json:"owner_id"`
}

func (q *Queries) RevokeFileShare(ctx context.Context, arg RevokeFileShareParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeFileShare, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFileShare = `-- name: UpdateFileShare :one
UPDATE /* TEMPLATE: schema */file_shares
SET password_hash = CASE
      WHEN $1::boolean THEN NULL
      ELSE COALESCE($2, password_hash)
    END,
    expires_at = CASE
      WHEN $3::boolean THEN NULL
      ELSE COALESCE($4, expires_at)
    END,
    max_downloads = CASE
      WHEN $5::boolean THEN NULL
      ELSE COALESCE($6, max_downloads)
    END
WHERE id = $7
  AND owner_id = $8
  AND revoked_at IS NULL
  AND (
    $5::boolean
    OR $6::bigint IS NULL
    OR $6::bigint >= download_count
  )
RETURNING id, file_id, owner_id, token_prefix, token_hash, password_hash, expires_at, max_downloads, download_count, created_at, revoked_at
`

type UpdateFileShareParams struct {
	ClearPassword     bool               `json:"clear_password"`
	PasswordHash      pgtype.Text        `json:"password_hash"`
	ClearExpiresAt    bool               `json:"clear_expires_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ClearMaxDownloads bool               `json:"clear_max_downloads"`
	MaxDownloads      pgtype.Int8        `json:"max_downloads"`
	ID                pgtype.UUID        `json:"id"`
	OwnerID           int64              `json:"owner_id"`
}

func (q *Queries) UpdateFileShare(ctx context.Context, arg UpdateFileShareParams) (*FileShare, error) {
	row := q.db.QueryRow(ctx, updateFileShare,
		arg.ClearPassword,
		arg.PasswordHash,
		arg.ClearExpiresAt,
		arg.ExpiresAt,
		arg.ClearMaxDownloads,
		arg.MaxDownloads,
		arg.ID,
		arg.OwnerID,
	)
	var i FileShare
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.OwnerID,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.MaxDownloads,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return &i, err
}
