// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStorageCleanupStatistics = `-- name: GetStorageCleanupStatistics :one
SELECT
    COALESCE((
        SELECT sum(fp.stored_size)
        FROM /* TEMPLATE: schema */file_parts fp
        JOIN /* TEMPLATE: schema */files f ON f.id = fp.file_id
        WHERE f.user_id = $1
          AND f.kind = 'file'
          AND f.status = 'trashed'
    ), 0)::bigint AS trash_bytes,
    COALESCE((
        SELECT sum(up.stored_size)
        FROM /* TEMPLATE: schema */upload_parts up
        JOIN /* TEMPLATE: schema */upload_sessions us ON us.id = up.upload_id
        WHERE us.user_id = $1
          AND us.state IN ('open', 'completing')
          AND us.expires_at <= now()
          AND up.state = 'stored'
    ), 0)::bigint AS stale_upload_bytes,
    COALESCE((
        SELECT count(*)
        FROM /* TEMPLATE: schema */upload_sessions us
        WHERE us.user_id = $1
          AND us.state IN ('open', 'completing')
          AND us.expires_at <= now()
    ), 0)::bigint AS stale_uploads
`

type GetStorageCleanupStatisticsRow struct {
	TrashBytes       int64 `json:"trash_bytes"`
	StaleUploadBytes int64 `json:"stale_upload_bytes"`
	StaleUploads     int64 `json:"stale_uploads"`
}

func (q *Queries) GetStorageCleanupStatistics(ctx context.Context, userID int64) (*GetStorageCleanupStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getStorageCleanupStatistics, userID)
	var i GetStorageCleanupStatisticsRow
	err := row.Scan(&i.TrashBytes, &i.StaleUploadBytes, &i.StaleUploads)
	return &i, err
}

const getStorageDashboardTotals = `-- name: GetStorageDashboardTotals :one
SELECT
    COALESCE(sum(f.size) FILTER (WHERE f.kind = 'file' AND f.status = 'active'), 0)::bigint AS logical_bytes,
    count(*) FILTER (WHERE f.kind = 'file' AND f.status = 'active')::bigint AS active_files,
    count(*) FILTER (WHERE f.kind = 'folder' AND f.status = 'active')::bigint AS active_folders,
    count(*) FILTER (WHERE f.kind = 'file' AND f.status = 'trashed')::bigint AS trashed_files,
    COALESCE(sum(f.size) FILTER (WHERE f.kind = 'file' AND f.status = 'trashed'), 0)::bigint AS trash_bytes
FROM /* TEMPLATE: schema */files f
WHERE f.user_id = $1
`

type GetStorageDashboardTotalsRow struct {
	LogicalBytes  int64 `json:"logical_bytes"`
	ActiveFiles   int64 `json:"active_files"`
	ActiveFolders int64 `json:"active_folders"`
	TrashedFiles  int64 `json:"trashed_files"`
	TrashBytes    int64 `json:"trash_bytes"`
}

func (q *Queries) GetStorageDashboardTotals(ctx context.Context, userID int64) (*GetStorageDashboardTotalsRow, error) {
	row := q.db.QueryRow(ctx, getStorageDashboardTotals, userID)
	var i GetStorageDashboardTotalsRow
	err := row.Scan(
		&i.LogicalBytes,
		&i.ActiveFiles,
		&i.ActiveFolders,
		&i.TrashedFiles,
		&i.TrashBytes,
	)
	return &i, err
}

const listRecentStorageActivity = `-- name: ListRecentStorageActivity :many
SELECT id, event_type, resource_type, resource_id, payload, occurred_at
FROM /* TEMPLATE: schema */user_events
WHERE user_id = $1
  AND event_type IN (
    'file.created', 'file.trashed', 'file.restored', 'file.purged',
    'upload.completed', 'upload.aborted', 'upload.expired',
    'share.created', 'share.deleted',
    'channel.created', 'channel.updated', 'channel.deleted'
  )
ORDER BY id DESC
LIMIT $2
`

type ListRecentStorageActivityParams struct {
	UserID        int64 `json:"user_id"`
	ActivityLimit int32 `json:"activity_limit"`
}

type ListRecentStorageActivityRow struct {
	ID           int64              `json:"id"`
	EventType    string             `json:"event_type"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	Payload      []byte             `json:"payload"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) ListRecentStorageActivity(ctx context.Context, arg ListRecentStorageActivityParams) ([]*ListRecentStorageActivityRow, error) {
	rows, err := q.db.Query(ctx, listRecentStorageActivity, arg.UserID, arg.ActivityLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListRecentStorageActivityRow{}
	for rows.Next() {
		var i ListRecentStorageActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ResourceType,
			&i.ResourceID,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageChannelStatistics = `-- name: ListStorageChannelStatistics :many
SELECT
    c.channel_id,
    c.name,
    c.selected,
    c.health::text AS health,
    c.last_checked_at,
    COALESCE(count(f.id), 0)::bigint AS part_count,
    COALESCE(sum(fp.stored_size) FILTER (WHERE f.id IS NOT NULL), 0)::bigint AS stored_bytes
FROM /* TEMPLATE: schema */channels c
LEFT JOIN /* TEMPLATE: schema */file_parts fp ON fp.channel_id = c.channel_id
LEFT JOIN /* TEMPLATE: schema */files f ON f.id = fp.file_id AND f.user_id = c.user_id AND f.status = 'active'
WHERE c.user_id = $1
GROUP BY c.channel_id, c.name, c.selected, c.health, c.last_checked_at
ORDER BY c.selected DESC, stored_bytes DESC, c.channel_id
`

type ListStorageChannelStatisticsRow struct {
	ChannelID     int64              `json:"channel_id"`
	Name          string             `json:"name"`
	Selected      bool               `json:"selected"`
	Health        string             `json:"health"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
	PartCount     int64              `json:"part_count"`
	StoredBytes   int64              `json:"stored_bytes"`
}

func (q *Queries) ListStorageChannelStatistics(ctx context.Context, userID int64) ([]*ListStorageChannelStatisticsRow, error) {
	rows, err := q.db.Query(ctx, listStorageChannelStatistics, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListStorageChannelStatisticsRow{}
	for rows.Next() {
		var i ListStorageChannelStatisticsRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.Name,
			&i.Selected,
			&i.Health,
			&i.LastCheckedAt,
			&i.PartCount,
			&i.StoredBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageGrowth = `-- name: ListStorageGrowth :many
WITH days AS (
    SELECT generate_series(
        date_trunc('day', now()) - interval '29 days',
        date_trunc('day', now()),
        interval '1 day'
    )::date AS day
), daily AS (
    SELECT
        f.created_at::date AS day,
        COALESCE(sum(f.size), 0)::bigint AS added_bytes
    FROM /* TEMPLATE: schema */files f
    WHERE f.user_id = $1
      AND f.kind = 'file'
      AND f.status = 'active'
      AND f.created_at >= date_trunc('day', now()) - interval '29 days'
    GROUP BY f.created_at::date
), baseline AS (
    SELECT COALESCE(sum(f.size), 0)::bigint AS bytes
    FROM /* TEMPLATE: schema */files f
    WHERE f.user_id = $1
      AND f.kind = 'file'
      AND f.status = 'active'
      AND f.created_at < date_trunc('day', now()) - interval '29 days'
)
SELECT
    days.day,
    COALESCE(daily.added_bytes, 0)::bigint AS added_bytes,
    (
        baseline.bytes + sum(COALESCE(daily.added_bytes, 0)) OVER (ORDER BY days.day)
    )::bigint AS logical_bytes
FROM days
CROSS JOIN baseline
LEFT JOIN daily USING (day)
ORDER BY days.day
`

type ListStorageGrowthRow struct {
	Day          pgtype.Date `json:"day"`
	AddedBytes   int64       `json:"added_bytes"`
	LogicalBytes int64       `json:"logical_bytes"`
}

func (q *Queries) ListStorageGrowth(ctx context.Context, userID int64) ([]*ListStorageGrowthRow, error) {
	rows, err := q.db.Query(ctx, listStorageGrowth, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListStorageGrowthRow{}
	for rows.Next() {
		var i ListStorageGrowthRow
		if err := rows.Scan(&i.Day, &i.AddedBytes, &i.LogicalBytes); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
