// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package sqlcgen

import (
	"context"
)

const acquireAdvisoryLock = `-- name: AcquireAdvisoryLock :exec
SELECT pg_advisory_lock($1)
`

func (q *Queries) AcquireAdvisoryLock(ctx context.Context, lockID int64) error {
	_, err := q.db.Exec(ctx, acquireAdvisoryLock, lockID)
	return err
}

const acquireAdvisoryTransactionLock = `-- name: AcquireAdvisoryTransactionLock :exec
SELECT pg_advisory_xact_lock($1)
`

func (q *Queries) AcquireAdvisoryTransactionLock(ctx context.Context, lockID int64) error {
	_, err := q.db.Exec(ctx, acquireAdvisoryTransactionLock, lockID)
	return err
}

const releaseAdvisoryLock = `-- name: ReleaseAdvisoryLock :one
SELECT pg_advisory_unlock($1)
`

func (q *Queries) ReleaseAdvisoryLock(ctx context.Context, lockID int64) (bool, error) {
	row := q.db.QueryRow(ctx, releaseAdvisoryLock, lockID)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}

const tryAdvisoryLock = `-- name: TryAdvisoryLock :one
SELECT pg_try_advisory_lock($1)
`

func (q *Queries) TryAdvisoryLock(ctx context.Context, lockID int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryAdvisoryLock, lockID)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}
