// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package sqlcgen

import (
	"context"
)

const acquireAdvisoryLock = `-- name: AcquireAdvisoryLock :exec
SELECT pg_advisory_lock($1)
`

func (q *Queries) AcquireAdvisoryLock(ctx context.Context, lockID int64) error {
	_, err := q.db.Exec(ctx, acquireAdvisoryLock, lockID)
	return err
}

const acquireAdvisoryTransactionLock = `-- name: AcquireAdvisoryTransactionLock :exec
SELECT pg_advisory_xact_lock($1)
`

func (q *Queries) AcquireAdvisoryTransactionLock(ctx context.Context, lockID int64) error {
	_, err := q.db.Exec(ctx, acquireAdvisoryTransactionLock, lockID)
	return err
}

const releaseAdvisoryLock = `-- name: ReleaseAdvisoryLock :one
SELECT pg_advisory_unlock($1)
`

func (q *Queries) ReleaseAdvisoryLock(ctx context.Context, lockID int64) (bool, error) {
	row := q.db.QueryRow(ctx, releaseAdvisoryLock, lockID)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}

const tryAdvisoryLock = `-- name: TryAdvisoryLock :one
SELECT pg_try_advisory_lock($1)
`

func (q *Queries) TryAdvisoryLock(ctx context.Context, lockID int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryAdvisoryLock, lockID)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}

const tryAdvisoryLocks = `-- name: TryAdvisoryLocks :many
SELECT candidate.lock_id::bigint AS lock_id, pg_try_advisory_lock(candidate.lock_id) AS locked
FROM unnest($1::bigint[]) AS candidate(lock_id)
`

type TryAdvisoryLocksRow struct {
	LockID int64 `json:"lock_id"`
	Locked bool  `json:"locked"`
}

func (q *Queries) TryAdvisoryLocks(ctx context.Context, lockIds []int64) ([]*TryAdvisoryLocksRow, error) {
	rows, err := q.db.Query(ctx, tryAdvisoryLocks, lockIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*TryAdvisoryLocksRow{}
	for rows.Next() {
		var i TryAdvisoryLocksRow
		if err := rows.Scan(&i.LockID, &i.Locked); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
