// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abortUploadSession = `-- name: AbortUploadSession :one
UPDATE /* TEMPLATE: schema */upload_sessions
SET state = 'aborted',
    updated_at = now()
WHERE id = $1
  AND user_id = $2
  AND state IN ('open', 'completing')
RETURNING id, user_id, parent_id, name, normalized_name, expected_size, expected_hash_algorithm, expected_hash_value, mime_type, mod_time, encryption, encryption_key_version, conflict_policy, part_size, state, file_id, expires_at, created_at, updated_at, completed_at
`

type AbortUploadSessionParams struct {
	UploadID pgtype.UUID `json:"upload_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) AbortUploadSession(ctx context.Context, arg AbortUploadSessionParams) (*UploadSession, error) {
	row := q.db.QueryRow(ctx, abortUploadSession, arg.UploadID, arg.UserID)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.ExpectedSize,
		&i.ExpectedHashAlgorithm,
		&i.ExpectedHashValue,
		&i.MimeType,
		&i.ModTime,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.ConflictPolicy,
		&i.PartSize,
		&i.State,
		&i.FileID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return &i, err
}

const claimUploadPart = `-- name: ClaimUploadPart :one
INSERT INTO /* TEMPLATE: schema */upload_parts (
    upload_id,
    part_no,
    channel_id,
    plain_size,
    checksum,
    state,
    lease_token,
    lease_expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'uploading',
    $6,
    $7
)
ON CONFLICT (upload_id, part_no) DO UPDATE
SET channel_id = EXCLUDED.channel_id,
    plain_size = EXCLUDED.plain_size,
    checksum = EXCLUDED.checksum,
    state = 'uploading',
    lease_token = EXCLUDED.lease_token,
    lease_expires_at = EXCLUDED.lease_expires_at,
    last_error_code = NULL,
    updated_at = now()
WHERE /* TEMPLATE: schema */upload_parts.state <> 'stored'
  AND (
    /* TEMPLATE: schema */upload_parts.lease_expires_at IS NULL
    OR /* TEMPLATE: schema */upload_parts.lease_expires_at < now()
  )
RETURNING upload_id, part_no, channel_id, message_id, plain_size, stored_size, checksum, salt, state, lease_token, lease_expires_at, last_error_code, created_at, updated_at, block_hashes
`

type ClaimUploadPartParams struct {
	UploadID       pgtype.UUID        `json:"upload_id"`
	PartNo         int32              `json:"part_no"`
	ChannelID      int64              `json:"channel_id"`
	PlainSize      int64              `json:"plain_size"`
	Checksum       pgtype.Text        `json:"checksum"`
	LeaseToken     pgtype.UUID        `json:"lease_token"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) ClaimUploadPart(ctx context.Context, arg ClaimUploadPartParams) (*UploadPart, error) {
	row := q.db.QueryRow(ctx, claimUploadPart,
		arg.UploadID,
		arg.PartNo,
		arg.ChannelID,
		arg.PlainSize,
		arg.Checksum,
		arg.LeaseToken,
		arg.LeaseExpiresAt,
	)
	var i UploadPart
	err := row.Scan(
		&i.UploadID,
		&i.PartNo,
		&i.ChannelID,
		&i.MessageID,
		&i.PlainSize,
		&i.StoredSize,
		&i.Checksum,
		&i.Salt,
		&i.State,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlockHashes,
	)
	return &i, err
}

const completeUploadSession = `-- name: CompleteUploadSession :one
UPDATE /* TEMPLATE: schema */upload_sessions
SET state = 'completed',
    file_id = $1,
    completed_at = now(),
    updated_at = now()
WHERE id = $2
  AND user_id = $3
  AND state = 'completing'
RETURNING id, user_id, parent_id, name, normalized_name, expected_size, expected_hash_algorithm, expected_hash_value, mime_type, mod_time, encryption, encryption_key_version, conflict_policy, part_size, state, file_id, expires_at, created_at, updated_at, completed_at
`

type CompleteUploadSessionParams struct {
	FileID   pgtype.UUID `json:"file_id"`
	UploadID pgtype.UUID `json:"upload_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) CompleteUploadSession(ctx context.Context, arg CompleteUploadSessionParams) (*UploadSession, error) {
	row := q.db.QueryRow(ctx, completeUploadSession, arg.FileID, arg.UploadID, arg.UserID)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.ExpectedSize,
		&i.ExpectedHashAlgorithm,
		&i.ExpectedHashValue,
		&i.MimeType,
		&i.ModTime,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.ConflictPolicy,
		&i.PartSize,
		&i.State,
		&i.FileID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return &i, err
}

const countInvalidOpenEndedUploadParts = `-- name: CountInvalidOpenEndedUploadParts :one
WITH final_part AS (
    SELECT COALESCE(max(part_no), 0)::integer AS part_no
    FROM /* TEMPLATE: schema */upload_parts
    WHERE upload_id = $1
      AND state = 'stored'
)
SELECT count(*)::bigint
FROM /* TEMPLATE: schema */upload_parts parts
CROSS JOIN final_part
WHERE parts.upload_id = $1
  AND parts.state = 'stored'
  AND parts.part_no < final_part.part_no
  AND parts.plain_size <> $2
`

type CountInvalidOpenEndedUploadPartsParams struct {
	UploadID pgtype.UUID `json:"upload_id"`
	PartSize int64       `json:"part_size"`
}

func (q *Queries) CountInvalidOpenEndedUploadParts(ctx context.Context, arg CountInvalidOpenEndedUploadPartsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvalidOpenEndedUploadParts, arg.UploadID, arg.PartSize)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUploadSession = `-- name: CreateUploadSession :one
INSERT INTO /* TEMPLATE: schema */upload_sessions (
    id,
    user_id,
    parent_id,
    name,
    normalized_name,
    expected_size,
    expected_hash_algorithm,
    expected_hash_value,
    mime_type,
    mod_time,
    encryption,
    encryption_key_version,
    conflict_policy,
    part_size,
    state,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    'open',
    $15
)
RETURNING id, user_id, parent_id, name, normalized_name, expected_size, expected_hash_algorithm, expected_hash_value, mime_type, mod_time, encryption, encryption_key_version, conflict_policy, part_size, state, file_id, expires_at, created_at, updated_at, completed_at
`

type CreateUploadSessionParams struct {
	ID                    pgtype.UUID        `json:"id"`
	UserID                int64              `json:"user_id"`
	ParentID              pgtype.UUID        `json:"parent_id"`
	Name                  string             `json:"name"`
	NormalizedName        string             `json:"normalized_name"`
	ExpectedSize          int64              `json:"expected_size"`
	ExpectedHashAlgorithm pgtype.Text        `json:"expected_hash_algorithm"`
	ExpectedHashValue     pgtype.Text        `json:"expected_hash_value"`
	MimeType              pgtype.Text        `json:"mime_type"`
	ModTime               pgtype.Timestamptz `json:"mod_time"`
	Encryption            bool               `json:"encryption"`
	EncryptionKeyVersion  pgtype.Int4        `json:"encryption_key_version"`
	ConflictPolicy        NameConflictPolicy `json:"conflict_policy"`
	PartSize              int64              `json:"part_size"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) (*UploadSession, error) {
	row := q.db.QueryRow(ctx, createUploadSession,
		arg.ID,
		arg.UserID,
		arg.ParentID,
		arg.Name,
		arg.NormalizedName,
		arg.ExpectedSize,
		arg.ExpectedHashAlgorithm,
		arg.ExpectedHashValue,
		arg.MimeType,
		arg.ModTime,
		arg.Encryption,
		arg.EncryptionKeyVersion,
		arg.ConflictPolicy,
		arg.PartSize,
		arg.ExpiresAt,
	)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.ExpectedSize,
		&i.ExpectedHashAlgorithm,
		&i.ExpectedHashValue,
		&i.MimeType,
		&i.ModTime,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.ConflictPolicy,
		&i.PartSize,
		&i.State,
		&i.FileID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return &i, err
}

const deleteUploadPartForCleanup = `-- name: DeleteUploadPartForCleanup :execrows
DELETE FROM /* TEMPLATE: schema */upload_parts up
USING /* TEMPLATE: schema */upload_sessions us
WHERE up.upload_id = $1
  AND up.part_no = $2
  AND up.message_id = $3
  AND us.id = up.upload_id
  AND us.state IN ('aborted', 'expired')
`

type DeleteUploadPartForCleanupParams struct {
	UploadID  pgtype.UUID `json:"upload_id"`
	PartNo    int32       `json:"part_no"`
	MessageID pgtype.Int8 `json:"message_id"`
}

func (q *Queries) DeleteUploadPartForCleanup(ctx context.Context, arg DeleteUploadPartForCleanupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUploadPartForCleanup, arg.UploadID, arg.PartNo, arg.MessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireUploadSessions = `-- name: ExpireUploadSessions :many
UPDATE /* TEMPLATE: schema */upload_sessions
SET state = 'expired',
    updated_at = now()
WHERE id IN (
    SELECT id
    FROM /* TEMPLATE: schema */upload_sessions
    WHERE state IN ('open', 'completing')
      AND expires_at <= now()
    ORDER BY expires_at
    FOR UPDATE SKIP LOCKED
    LIMIT $1
)
RETURNING id, user_id, parent_id, name, normalized_name, expected_size, expected_hash_algorithm, expected_hash_value, mime_type, mod_time, encryption, encryption_key_version, conflict_policy, part_size, state, file_id, expires_at, created_at, updated_at, completed_at
`

func (q *Queries) ExpireUploadSessions(ctx context.Context, batchSize int32) ([]*UploadSession, error) {
	rows, err := q.db.Query(ctx, expireUploadSessions, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UploadSession{}
	for rows.Next() {
		var i UploadSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.NormalizedName,
			&i.ExpectedSize,
			&i.ExpectedHashAlgorithm,
			&i.ExpectedHashValue,
			&i.MimeType,
			&i.ModTime,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.ConflictPolicy,
			&i.PartSize,
			&i.State,
			&i.FileID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finalizeUploadExpectedSize = `-- name: FinalizeUploadExpectedSize :one
UPDATE /* TEMPLATE: schema */upload_sessions
SET expected_size = $1,
    updated_at = now()
WHERE id = $2
  AND user_id = $3
  AND expected_size = -1
  AND state = 'open'
RETURNING id, user_id, parent_id, name, normalized_name, expected_size, expected_hash_algorithm, expected_hash_value, mime_type, mod_time, encryption, encryption_key_version, conflict_policy, part_size, state, file_id, expires_at, created_at, updated_at, completed_at
`

type FinalizeUploadExpectedSizeParams struct {
	ExpectedSize int64       `json:"expected_size"`
	UploadID     pgtype.UUID `json:"upload_id"`
	UserID       int64       `json:"user_id"`
}

func (q *Queries) FinalizeUploadExpectedSize(ctx context.Context, arg FinalizeUploadExpectedSizeParams) (*UploadSession, error) {
	row := q.db.QueryRow(ctx, finalizeUploadExpectedSize, arg.ExpectedSize, arg.UploadID, arg.UserID)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.ExpectedSize,
		&i.ExpectedHashAlgorithm,
		&i.ExpectedHashValue,
		&i.MimeType,
		&i.ModTime,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.ConflictPolicy,
		&i.PartSize,
		&i.State,
		&i.FileID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return &i, err
}

const getAllUploadPartSummary = `-- name: GetAllUploadPartSummary :one
SELECT
    count(*)::bigint AS total_parts,
    count(*) FILTER (WHERE state = 'stored')::bigint AS stored_parts,
    COALESCE(sum(plain_size) FILTER (WHERE state = 'stored'), 0)::bigint AS stored_plain_size,
    COALESCE(min(part_no) FILTER (WHERE state = 'stored'), 0)::integer AS min_part_no,
    COALESCE(max(part_no) FILTER (WHERE state = 'stored'), 0)::integer AS max_part_no
FROM /* TEMPLATE: schema */upload_parts
WHERE upload_id = $1
`

type GetAllUploadPartSummaryRow struct {
	TotalParts      int64 `json:"total_parts"`
	StoredParts     int64 `json:"stored_parts"`
	StoredPlainSize int64 `json:"stored_plain_size"`
	MinPartNo       int32 `json:"min_part_no"`
	MaxPartNo       int32 `json:"max_part_no"`
}

func (q *Queries) GetAllUploadPartSummary(ctx context.Context, uploadID pgtype.UUID) (*GetAllUploadPartSummaryRow, error) {
	row := q.db.QueryRow(ctx, getAllUploadPartSummary, uploadID)
	var i GetAllUploadPartSummaryRow
	err := row.Scan(
		&i.TotalParts,
		&i.StoredParts,
		&i.StoredPlainSize,
		&i.MinPartNo,
		&i.MaxPartNo,
	)
	return &i, err
}

const getStoredUploadPartSummary = `-- name: GetStoredUploadPartSummary :one
SELECT
    count(*)::integer AS part_count,
    COALESCE(sum(plain_size), 0)::bigint AS plain_size,
    COALESCE(sum(stored_size), 0)::bigint AS stored_size,
    COALESCE(min(part_no), 0)::integer AS min_part_no,
    COALESCE(max(part_no), 0)::integer AS max_part_no
FROM /* TEMPLATE: schema */upload_parts
WHERE upload_id = $1
  AND state = 'stored'
`

type GetStoredUploadPartSummaryRow struct {
	PartCount  int32 `json:"part_count"`
	PlainSize  int64 `json:"plain_size"`
	StoredSize int64 `json:"stored_size"`
	MinPartNo  int32 `json:"min_part_no"`
	MaxPartNo  int32 `json:"max_part_no"`
}

func (q *Queries) GetStoredUploadPartSummary(ctx context.Context, uploadID pgtype.UUID) (*GetStoredUploadPartSummaryRow, error) {
	row := q.db.QueryRow(ctx, getStoredUploadPartSummary, uploadID)
	var i GetStoredUploadPartSummaryRow
	err := row.Scan(
		&i.PartCount,
		&i.PlainSize,
		&i.StoredSize,
		&i.MinPartNo,
		&i.MaxPartNo,
	)
	return &i, err
}

const getUploadPart = `-- name: GetUploadPart :one
SELECT upload_id, part_no, channel_id, message_id, plain_size, stored_size, checksum, salt, state, lease_token, lease_expires_at, last_error_code, created_at, updated_at, block_hashes
FROM /* TEMPLATE: schema */upload_parts
WHERE upload_id = $1
  AND part_no = $2
`

type GetUploadPartParams struct {
	UploadID pgtype.UUID `json:"upload_id"`
	PartNo   int32       `json:"part_no"`
}

func (q *Queries) GetUploadPart(ctx context.Context, arg GetUploadPartParams) (*UploadPart, error) {
	row := q.db.QueryRow(ctx, getUploadPart, arg.UploadID, arg.PartNo)
	var i UploadPart
	err := row.Scan(
		&i.UploadID,
		&i.PartNo,
		&i.ChannelID,
		&i.MessageID,
		&i.PlainSize,
		&i.StoredSize,
		&i.Checksum,
		&i.Salt,
		&i.State,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlockHashes,
	)
	return &i, err
}

const getUploadSessionForUser = `-- name: GetUploadSessionForUser :one
SELECT id, user_id, parent_id, name, normalized_name, expected_size, expected_hash_algorithm, expected_hash_value, mime_type, mod_time, encryption, encryption_key_version, conflict_policy, part_size, state, file_id, expires_at, created_at, updated_at, completed_at
FROM /* TEMPLATE: schema */upload_sessions
WHERE id = $1
  AND user_id = $2
`

type GetUploadSessionForUserParams struct {
	UploadID pgtype.UUID `json:"upload_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) GetUploadSessionForUser(ctx context.Context, arg GetUploadSessionForUserParams) (*UploadSession, error) {
	row := q.db.QueryRow(ctx, getUploadSessionForUser, arg.UploadID, arg.UserID)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.ExpectedSize,
		&i.ExpectedHashAlgorithm,
		&i.ExpectedHashValue,
		&i.MimeType,
		&i.ModTime,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.ConflictPolicy,
		&i.PartSize,
		&i.State,
		&i.FileID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return &i, err
}

const insertFileFromUpload = `-- name: InsertFileFromUpload :one
INSERT INTO /* TEMPLATE: schema */files (
    id,
    user_id,
    parent_id,
    name,
    normalized_name,
    kind,
    mime_type,
    size,
    hash_algorithm,
    hash_value,
    encryption,
    encryption_key_version,
    status,
    mod_time
)
SELECT
    $1,
    user_id,
    parent_id,
    name,
    normalized_name,
    'file',
    mime_type,
    expected_size,
    $2,
    $3,
    encryption,
    encryption_key_version,
    'active',
    mod_time
FROM /* TEMPLATE: schema */upload_sessions us
WHERE us.id = $4
  AND us.user_id = $5
  AND us.state = 'completing'
RETURNING id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
`

type InsertFileFromUploadParams struct {
	FileID        pgtype.UUID `json:"file_id"`
	HashAlgorithm pgtype.Text `json:"hash_algorithm"`
	HashValue     pgtype.Text `json:"hash_value"`
	UploadID      pgtype.UUID `json:"upload_id"`
	UserID        int64       `json:"user_id"`
}

func (q *Queries) InsertFileFromUpload(ctx context.Context, arg InsertFileFromUploadParams) (*File, error) {
	row := q.db.QueryRow(ctx, insertFileFromUpload,
		arg.FileID,
		arg.HashAlgorithm,
		arg.HashValue,
		arg.UploadID,
		arg.UserID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const insertFilePartsFromUpload = `-- name: InsertFilePartsFromUpload :execrows
INSERT INTO /* TEMPLATE: schema */file_parts (
    file_id,
    part_no,
    channel_id,
    message_id,
    plain_size,
    stored_size,
    checksum,
    salt,
    block_hashes
)
SELECT
    $1,
    part_no,
    channel_id,
    message_id,
    plain_size,
    stored_size,
    checksum,
    salt,
    block_hashes
FROM /* TEMPLATE: schema */upload_parts
WHERE upload_id = $2
  AND state = 'stored'
ORDER BY part_no
`

type InsertFilePartsFromUploadParams struct {
	FileID   pgtype.UUID `json:"file_id"`
	UploadID pgtype.UUID `json:"upload_id"`
}

func (q *Queries) InsertFilePartsFromUpload(ctx context.Context, arg InsertFilePartsFromUploadParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertFilePartsFromUpload, arg.FileID, arg.UploadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listStoredUploadPartHashes = `-- name: ListStoredUploadPartHashes :many
SELECT block_hashes
FROM /* TEMPLATE: schema */upload_parts
WHERE upload_id = $1
  AND state = 'stored'
ORDER BY part_no
`

func (q *Queries) ListStoredUploadPartHashes(ctx context.Context, uploadID pgtype.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listStoredUploadPartHashes, uploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var block_hashes []byte
		if err := rows.Scan(&block_hashes); err != nil {
			return nil, err
		}
		items = append(items, block_hashes)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadDailyStatistics = `-- name: ListUploadDailyStatistics :many
WITH days AS (
  SELECT generate_series(
    (CURRENT_DATE - ($1::integer - 1))::date,
    CURRENT_DATE,
    interval '1 day'
  )::date AS day
), totals AS (
  SELECT completed_at::date AS day,
         COALESCE(sum(expected_size), 0)::bigint AS uploaded_bytes,
         count(*)::bigint AS completed_files
  FROM /* TEMPLATE: schema */upload_sessions
  WHERE user_id = $2
    AND state = 'completed'
    AND completed_at >= CURRENT_DATE - ($1::integer - 1)
  GROUP BY completed_at::date
)
SELECT d.day, COALESCE(t.uploaded_bytes, 0)::bigint AS uploaded_bytes,
       COALESCE(t.completed_files, 0)::bigint AS completed_files
FROM days d
LEFT JOIN totals t USING (day)
ORDER BY d.day
`

type ListUploadDailyStatisticsParams struct {
	Days   int32 `json:"days"`
	UserID int64 `json:"user_id"`
}

type ListUploadDailyStatisticsRow struct {
	Day            pgtype.Date `json:"day"`
	UploadedBytes  int64       `json:"uploaded_bytes"`
	CompletedFiles int64       `json:"completed_files"`
}

func (q *Queries) ListUploadDailyStatistics(ctx context.Context, arg ListUploadDailyStatisticsParams) ([]*ListUploadDailyStatisticsRow, error) {
	rows, err := q.db.Query(ctx, listUploadDailyStatistics, arg.Days, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListUploadDailyStatisticsRow{}
	for rows.Next() {
		var i ListUploadDailyStatisticsRow
		if err := rows.Scan(&i.Day, &i.UploadedBytes, &i.CompletedFiles); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadParts = `-- name: ListUploadParts :many
SELECT upload_id, part_no, channel_id, message_id, plain_size, stored_size, checksum, salt, state, lease_token, lease_expires_at, last_error_code, created_at, updated_at, block_hashes
FROM /* TEMPLATE: schema */upload_parts
WHERE upload_id = $1
  AND (
    $2::integer IS NULL
    OR part_no > $2::integer
  )
ORDER BY part_no
LIMIT $3
`

type ListUploadPartsParams struct {
	UploadID    pgtype.UUID `json:"upload_id"`
	AfterPartNo pgtype.Int4 `json:"after_part_no"`
	PageSize    int32       `json:"page_size"`
}

func (q *Queries) ListUploadParts(ctx context.Context, arg ListUploadPartsParams) ([]*UploadPart, error) {
	rows, err := q.db.Query(ctx, listUploadParts, arg.UploadID, arg.AfterPartNo, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UploadPart{}
	for rows.Next() {
		var i UploadPart
		if err := rows.Scan(
			&i.UploadID,
			&i.PartNo,
			&i.ChannelID,
			&i.MessageID,
			&i.PlainSize,
			&i.StoredSize,
			&i.Checksum,
			&i.Salt,
			&i.State,
			&i.LeaseToken,
			&i.LeaseExpiresAt,
			&i.LastErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlockHashes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadPartsForCleanup = `-- name: ListUploadPartsForCleanup :many
SELECT up.upload_id, up.part_no, up.channel_id, up.message_id, up.plain_size, up.stored_size, up.checksum, up.salt, up.state, up.lease_token, up.lease_expires_at, up.last_error_code, up.created_at, up.updated_at, up.block_hashes
FROM /* TEMPLATE: schema */upload_parts up
JOIN /* TEMPLATE: schema */upload_sessions us ON us.id = up.upload_id
WHERE us.id = $1
  AND us.state IN ('aborted', 'expired')
  AND up.message_id IS NOT NULL
ORDER BY up.part_no
`

func (q *Queries) ListUploadPartsForCleanup(ctx context.Context, uploadID pgtype.UUID) ([]*UploadPart, error) {
	rows, err := q.db.Query(ctx, listUploadPartsForCleanup, uploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UploadPart{}
	for rows.Next() {
		var i UploadPart
		if err := rows.Scan(
			&i.UploadID,
			&i.PartNo,
			&i.ChannelID,
			&i.MessageID,
			&i.PlainSize,
			&i.StoredSize,
			&i.Checksum,
			&i.Salt,
			&i.State,
			&i.LeaseToken,
			&i.LeaseExpiresAt,
			&i.LastErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlockHashes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadSessions = `-- name: ListUploadSessions :many
SELECT id, user_id, parent_id, name, normalized_name, expected_size, expected_hash_algorithm, expected_hash_value, mime_type, mod_time, encryption, encryption_key_version, conflict_policy, part_size, state, file_id, expires_at, created_at, updated_at, completed_at
FROM /* TEMPLATE: schema */upload_sessions
WHERE user_id = $1
  AND ($2::/* TEMPLATE: schema */upload_state IS NULL OR state = $2::/* TEMPLATE: schema */upload_state)
  AND (
    $3::timestamptz IS NULL
    OR (created_at, id) < (
      $3::timestamptz,
      $4::uuid
    )
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListUploadSessionsParams struct {
	UserID         int64              `json:"user_id"`
	State          NullUploadState    `json:"state"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	PageSize       int32              `json:"page_size"`
}

func (q *Queries) ListUploadSessions(ctx context.Context, arg ListUploadSessionsParams) ([]*UploadSession, error) {
	rows, err := q.db.Query(ctx, listUploadSessions,
		arg.UserID,
		arg.State,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UploadSession{}
	for rows.Next() {
		var i UploadSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.NormalizedName,
			&i.ExpectedSize,
			&i.ExpectedHashAlgorithm,
			&i.ExpectedHashValue,
			&i.MimeType,
			&i.ModTime,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.ConflictPolicy,
			&i.PartSize,
			&i.State,
			&i.FileID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadSessionsPendingCleanup = `-- name: ListUploadSessionsPendingCleanup :many
SELECT DISTINCT us.id, us.user_id, us.parent_id, us.name, us.normalized_name, us.expected_size, us.expected_hash_algorithm, us.expected_hash_value, us.mime_type, us.mod_time, us.encryption, us.encryption_key_version, us.conflict_policy, us.part_size, us.state, us.file_id, us.expires_at, us.created_at, us.updated_at, us.completed_at
FROM /* TEMPLATE: schema */upload_sessions us
JOIN /* TEMPLATE: schema */upload_parts up ON up.upload_id = us.id
WHERE us.state IN ('aborted', 'expired')
  AND up.message_id IS NOT NULL
ORDER BY us.updated_at, us.id
LIMIT $1
`

func (q *Queries) ListUploadSessionsPendingCleanup(ctx context.Context, batchSize int32) ([]*UploadSession, error) {
	rows, err := q.db.Query(ctx, listUploadSessionsPendingCleanup, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UploadSession{}
	for rows.Next() {
		var i UploadSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.NormalizedName,
			&i.ExpectedSize,
			&i.ExpectedHashAlgorithm,
			&i.ExpectedHashValue,
			&i.MimeType,
			&i.ModTime,
			&i.Encryption,
			&i.EncryptionKeyVersion,
			&i.ConflictPolicy,
			&i.PartSize,
			&i.State,
			&i.FileID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUploadDestinationConflict = `-- name: LockUploadDestinationConflict :one
SELECT id, user_id, parent_id, name, normalized_name, kind, mime_type, size, hash_algorithm, hash_value, encryption, encryption_key_version, status, mod_time, generation, created_at, updated_at, deleted_at
FROM /* TEMPLATE: schema */files
WHERE user_id = $1
  AND parent_id IS NOT DISTINCT FROM $2::uuid
  AND normalized_name = $3
  AND status = 'active'
FOR UPDATE
`

type LockUploadDestinationConflictParams struct {
	UserID         int64       `json:"user_id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	NormalizedName string      `json:"normalized_name"`
}

func (q *Queries) LockUploadDestinationConflict(ctx context.Context, arg LockUploadDestinationConflictParams) (*File, error) {
	row := q.db.QueryRow(ctx, lockUploadDestinationConflict, arg.UserID, arg.ParentID, arg.NormalizedName)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.Kind,
		&i.MimeType,
		&i.Size,
		&i.HashAlgorithm,
		&i.HashValue,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.Status,
		&i.ModTime,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const lockUploadSessionForCompletion = `-- name: LockUploadSessionForCompletion :one
SELECT id, user_id, parent_id, name, normalized_name, expected_size, expected_hash_algorithm, expected_hash_value, mime_type, mod_time, encryption, encryption_key_version, conflict_policy, part_size, state, file_id, expires_at, created_at, updated_at, completed_at
FROM /* TEMPLATE: schema */upload_sessions
WHERE id = $1
  AND user_id = $2
FOR UPDATE
`

type LockUploadSessionForCompletionParams struct {
	UploadID pgtype.UUID `json:"upload_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) LockUploadSessionForCompletion(ctx context.Context, arg LockUploadSessionForCompletionParams) (*UploadSession, error) {
	row := q.db.QueryRow(ctx, lockUploadSessionForCompletion, arg.UploadID, arg.UserID)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.ExpectedSize,
		&i.ExpectedHashAlgorithm,
		&i.ExpectedHashValue,
		&i.MimeType,
		&i.ModTime,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.ConflictPolicy,
		&i.PartSize,
		&i.State,
		&i.FileID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return &i, err
}

const markActiveFileDeletionPendingForReplace = `-- name: MarkActiveFileDeletionPendingForReplace :execrows
UPDATE /* TEMPLATE: schema */files
SET status = 'deletion_pending',
    deleted_at = COALESCE(deleted_at, now()),
    updated_at = now(),
    generation = generation + 1
WHERE id = $1
  AND user_id = $2
  AND status = 'active'
`

type MarkActiveFileDeletionPendingForReplaceParams struct {
	FileID pgtype.UUID `json:"file_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) MarkActiveFileDeletionPendingForReplace(ctx context.Context, arg MarkActiveFileDeletionPendingForReplaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, markActiveFileDeletionPendingForReplace, arg.FileID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markUploadCompleting = `-- name: MarkUploadCompleting :one
UPDATE /* TEMPLATE: schema */upload_sessions
SET state = 'completing',
    updated_at = now()
WHERE id = $1
  AND user_id = $2
  AND state = 'open'
RETURNING id, user_id, parent_id, name, normalized_name, expected_size, expected_hash_algorithm, expected_hash_value, mime_type, mod_time, encryption, encryption_key_version, conflict_policy, part_size, state, file_id, expires_at, created_at, updated_at, completed_at
`

type MarkUploadCompletingParams struct {
	UploadID pgtype.UUID `json:"upload_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) MarkUploadCompleting(ctx context.Context, arg MarkUploadCompletingParams) (*UploadSession, error) {
	row := q.db.QueryRow(ctx, markUploadCompleting, arg.UploadID, arg.UserID)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.NormalizedName,
		&i.ExpectedSize,
		&i.ExpectedHashAlgorithm,
		&i.ExpectedHashValue,
		&i.MimeType,
		&i.ModTime,
		&i.Encryption,
		&i.EncryptionKeyVersion,
		&i.ConflictPolicy,
		&i.PartSize,
		&i.State,
		&i.FileID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return &i, err
}

const markUploadPartFailed = `-- name: MarkUploadPartFailed :one
UPDATE /* TEMPLATE: schema */upload_parts
SET state = 'failed',
    lease_token = NULL,
    lease_expires_at = NULL,
    last_error_code = $1,
    updated_at = now()
WHERE upload_id = $2
  AND part_no = $3
  AND lease_token = $4
RETURNING upload_id, part_no, channel_id, message_id, plain_size, stored_size, checksum, salt, state, lease_token, lease_expires_at, last_error_code, created_at, updated_at, block_hashes
`

type MarkUploadPartFailedParams struct {
	ErrorCode  pgtype.Text `json:"error_code"`
	UploadID   pgtype.UUID `json:"upload_id"`
	PartNo     int32       `json:"part_no"`
	LeaseToken pgtype.UUID `json:"lease_token"`
}

func (q *Queries) MarkUploadPartFailed(ctx context.Context, arg MarkUploadPartFailedParams) (*UploadPart, error) {
	row := q.db.QueryRow(ctx, markUploadPartFailed,
		arg.ErrorCode,
		arg.UploadID,
		arg.PartNo,
		arg.LeaseToken,
	)
	var i UploadPart
	err := row.Scan(
		&i.UploadID,
		&i.PartNo,
		&i.ChannelID,
		&i.MessageID,
		&i.PlainSize,
		&i.StoredSize,
		&i.Checksum,
		&i.Salt,
		&i.State,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlockHashes,
	)
	return &i, err
}

const markUploadPartStored = `-- name: MarkUploadPartStored :one
UPDATE /* TEMPLATE: schema */upload_parts
SET message_id = $1,
    stored_size = $2,
    checksum = $3,
    salt = $4,
    block_hashes = $5,
    state = 'stored',
    lease_token = NULL,
    lease_expires_at = NULL,
    last_error_code = NULL,
    updated_at = now()
WHERE upload_id = $6
  AND part_no = $7
  AND state = 'uploading'
  AND lease_token = $8
RETURNING upload_id, part_no, channel_id, message_id, plain_size, stored_size, checksum, salt, state, lease_token, lease_expires_at, last_error_code, created_at, updated_at, block_hashes
`

type MarkUploadPartStoredParams struct {
	MessageID   pgtype.Int8 `json:"message_id"`
	StoredSize  pgtype.Int8 `json:"stored_size"`
	Checksum    pgtype.Text `json:"checksum"`
	Salt        pgtype.Text `json:"salt"`
	BlockHashes []byte      `json:"block_hashes"`
	UploadID    pgtype.UUID `json:"upload_id"`
	PartNo      int32       `json:"part_no"`
	LeaseToken  pgtype.UUID `json:"lease_token"`
}

func (q *Queries) MarkUploadPartStored(ctx context.Context, arg MarkUploadPartStoredParams) (*UploadPart, error) {
	row := q.db.QueryRow(ctx, markUploadPartStored,
		arg.MessageID,
		arg.StoredSize,
		arg.Checksum,
		arg.Salt,
		arg.BlockHashes,
		arg.UploadID,
		arg.PartNo,
		arg.LeaseToken,
	)
	var i UploadPart
	err := row.Scan(
		&i.UploadID,
		&i.PartNo,
		&i.ChannelID,
		&i.MessageID,
		&i.PlainSize,
		&i.StoredSize,
		&i.Checksum,
		&i.Salt,
		&i.State,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlockHashes,
	)
	return &i, err
}

const renameUploadSession = `-- name: RenameUploadSession :execrows
UPDATE /* TEMPLATE: schema */upload_sessions
SET name = $1,
    normalized_name = $2,
    updated_at = now()
WHERE id = $3
  AND user_id = $4
`

type RenameUploadSessionParams struct {
	Name           string      `json:"name"`
	NormalizedName string      `json:"normalized_name"`
	UploadID       pgtype.UUID `json:"upload_id"`
	UserID         int64       `json:"user_id"`
}

func (q *Queries) RenameUploadSession(ctx context.Context, arg RenameUploadSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameUploadSession,
		arg.Name,
		arg.NormalizedName,
		arg.UploadID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewUploadPartLease = `-- name: RenewUploadPartLease :execrows
UPDATE /* TEMPLATE: schema */upload_parts
SET lease_expires_at = $1,
    updated_at = now()
WHERE upload_id = $2
  AND part_no = $3
  AND state = 'uploading'
  AND lease_token = $4
`

type RenewUploadPartLeaseParams struct {
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	UploadID       pgtype.UUID        `json:"upload_id"`
	PartNo         int32              `json:"part_no"`
	LeaseToken     pgtype.UUID        `json:"lease_token"`
}

func (q *Queries) RenewUploadPartLease(ctx context.Context, arg RenewUploadPartLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewUploadPartLease,
		arg.LeaseExpiresAt,
		arg.UploadID,
		arg.PartNo,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeActiveSharesForFile = `-- name: RevokeActiveSharesForFile :exec
UPDATE /* TEMPLATE: schema */file_shares
SET revoked_at = COALESCE(revoked_at, now())
WHERE file_id = $1
  AND owner_id = $2
  AND revoked_at IS NULL
`

type RevokeActiveSharesForFileParams struct {
	FileID pgtype.UUID `json:"file_id"`
	UserID int64       `json:"user_id"`
}

func (q *Queries) RevokeActiveSharesForFile(ctx context.Context, arg RevokeActiveSharesForFileParams) error {
	_, err := q.db.Exec(ctx, revokeActiveSharesForFile, arg.FileID, arg.UserID)
	return err
}
