// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: view_states.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFileViewState = `-- name: DeleteFileViewState :execrows
DELETE FROM /* TEMPLATE: schema */file_view_states
WHERE user_id = $1
  AND file_id = $2
`

type DeleteFileViewStateParams struct {
	UserID int64       `json:"user_id"`
	FileID pgtype.UUID `json:"file_id"`
}

func (q *Queries) DeleteFileViewState(ctx context.Context, arg DeleteFileViewStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFileViewState, arg.UserID, arg.FileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFileViewState = `-- name: GetFileViewState :one
SELECT user_id, file_id, viewer_kind, position, preferences, bookmarks, created_at, updated_at
FROM /* TEMPLATE: schema */file_view_states
WHERE user_id = $1
  AND file_id = $2
`

type GetFileViewStateParams struct {
	UserID int64       `json:"user_id"`
	FileID pgtype.UUID `json:"file_id"`
}

func (q *Queries) GetFileViewState(ctx context.Context, arg GetFileViewStateParams) (*FileViewState, error) {
	row := q.db.QueryRow(ctx, getFileViewState, arg.UserID, arg.FileID)
	var i FileViewState
	err := row.Scan(
		&i.UserID,
		&i.FileID,
		&i.ViewerKind,
		&i.Position,
		&i.Preferences,
		&i.Bookmarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertFileViewState = `-- name: UpsertFileViewState :one
INSERT INTO /* TEMPLATE: schema */file_view_states (
    user_id, file_id, viewer_kind, position, preferences, bookmarks
) SELECT
    $1, $2, $3,
    $4, $5, $6
FROM /* TEMPLATE: schema */files
WHERE id = $2
  AND kind = 'file'
  AND status = 'active'
ON CONFLICT (user_id, file_id) DO UPDATE
SET viewer_kind = EXCLUDED.viewer_kind,
    position = EXCLUDED.position,
    preferences = EXCLUDED.preferences,
    bookmarks = EXCLUDED.bookmarks,
    updated_at = now()
RETURNING user_id, file_id, viewer_kind, position, preferences, bookmarks, created_at, updated_at
`

type UpsertFileViewStateParams struct {
	UserID      int64       `json:"user_id"`
	FileID      pgtype.UUID `json:"file_id"`
	ViewerKind  string      `json:"viewer_kind"`
	Position    []byte      `json:"position"`
	Preferences []byte      `json:"preferences"`
	Bookmarks   []byte      `json:"bookmarks"`
}

func (q *Queries) UpsertFileViewState(ctx context.Context, arg UpsertFileViewStateParams) (*FileViewState, error) {
	row := q.db.QueryRow(ctx, upsertFileViewState,
		arg.UserID,
		arg.FileID,
		arg.ViewerKind,
		arg.Position,
		arg.Preferences,
		arg.Bookmarks,
	)
	var i FileViewState
	err := row.Scan(
		&i.UserID,
		&i.FileID,
		&i.ViewerKind,
		&i.Position,
		&i.Preferences,
		&i.Bookmarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
