//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	APIKeys = APIKeys.FromSchema(schema)
	Bots = Bots.FromSchema(schema)
	Channels = Channels.FromSchema(schema)
	CronJobs = CronJobs.FromSchema(schema)
	Events = Events.FromSchema(schema)
	FileShares = FileShares.FromSchema(schema)
	Files = Files.FromSchema(schema)
	Kv = Kv.FromSchema(schema)
	PeriodicJobs = PeriodicJobs.FromSchema(schema)
	Sessions = Sessions.FromSchema(schema)
	Uploads = Uploads.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
