//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Uploads = newUploadsTable("teldrive", "uploads", "")

type uploadsTable struct {
	postgres.Table

	// Columns
	UploadID    postgres.ColumnString
	Name        postgres.ColumnString
	UserID      postgres.ColumnInteger
	PartNo      postgres.ColumnInteger
	PartID      postgres.ColumnInteger
	ChannelID   postgres.ColumnInteger
	Size        postgres.ColumnInteger
	CreatedAt   postgres.ColumnTimestamp
	Encrypted   postgres.ColumnBool
	Salt        postgres.ColumnString
	BlockHashes postgres.ColumnBytea

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UploadsTable struct {
	uploadsTable

	EXCLUDED uploadsTable
}

// AS creates new UploadsTable with assigned alias
func (a UploadsTable) AS(alias string) *UploadsTable {
	return newUploadsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UploadsTable with assigned schema name
func (a UploadsTable) FromSchema(schemaName string) *UploadsTable {
	return newUploadsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UploadsTable with assigned table prefix
func (a UploadsTable) WithPrefix(prefix string) *UploadsTable {
	return newUploadsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UploadsTable with assigned table suffix
func (a UploadsTable) WithSuffix(suffix string) *UploadsTable {
	return newUploadsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUploadsTable(schemaName, tableName, alias string) *UploadsTable {
	return &UploadsTable{
		uploadsTable: newUploadsTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newUploadsTableImpl("", "excluded", ""),
	}
}

func newUploadsTableImpl(schemaName, tableName, alias string) uploadsTable {
	var (
		UploadIDColumn    = postgres.StringColumn("upload_id")
		NameColumn        = postgres.StringColumn("name")
		UserIDColumn      = postgres.IntegerColumn("user_id")
		PartNoColumn      = postgres.IntegerColumn("part_no")
		PartIDColumn      = postgres.IntegerColumn("part_id")
		ChannelIDColumn   = postgres.IntegerColumn("channel_id")
		SizeColumn        = postgres.IntegerColumn("size")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		EncryptedColumn   = postgres.BoolColumn("encrypted")
		SaltColumn        = postgres.StringColumn("salt")
		BlockHashesColumn = postgres.ByteaColumn("block_hashes")
		allColumns        = postgres.ColumnList{UploadIDColumn, NameColumn, UserIDColumn, PartNoColumn, PartIDColumn, ChannelIDColumn, SizeColumn, CreatedAtColumn, EncryptedColumn, SaltColumn, BlockHashesColumn}
		mutableColumns    = postgres.ColumnList{UploadIDColumn, NameColumn, UserIDColumn, PartNoColumn, SizeColumn, CreatedAtColumn, EncryptedColumn, SaltColumn, BlockHashesColumn}
		defaultColumns    = postgres.ColumnList{CreatedAtColumn, EncryptedColumn}
	)

	return uploadsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UploadID:    UploadIDColumn,
		Name:        NameColumn,
		UserID:      UserIDColumn,
		PartNo:      PartNoColumn,
		PartID:      PartIDColumn,
		ChannelID:   ChannelIDColumn,
		Size:        SizeColumn,
		CreatedAt:   CreatedAtColumn,
		Encrypted:   EncryptedColumn,
		Salt:        SaltColumn,
		BlockHashes: BlockHashesColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
