# GENERATED by `just nix-generate` (internal/tools/nixconfig). Do not edit.
# Option schema for services.teldrive.settings, derived from internal/config.
# Every leaf defaults to null so only explicitly set values reach the
# daemon environment; Teldrive applies its own defaults otherwise.
{ lib, ... }:
{
  "http" = {
    "address" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "HTTP listen address (Default: 127.0.0.1:8080) [validate: required]";
    };
    "read-header-timeout" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Maximum time to read request headers (Default: 10s) [validate: gte=0]";
    };
    "read-timeout" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Maximum time to read an entire request; zero disables it for streaming uploads (Default: 1h) [validate: gte=0]";
    };
    "write-timeout" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Maximum response write duration; zero disables it for streaming (Default: 1h) [validate: gte=0]";
    };
    "idle-timeout" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "HTTP keep-alive idle timeout (Default: 2m) [validate: gte=0]";
    };
    "shutdown-timeout" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Graceful shutdown timeout (Default: 10s) [validate: gte=0]";
    };
    "trusted-proxies" = lib.mkOption {
      type = lib.types.nullOr (lib.types.listOf lib.types.str);
      default = null;
      description = "Proxy IP addresses or CIDRs trusted to set forwarding headers (No default; upstream applies its own.)";
    };
  };
  "database" = {
    "url" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "PostgreSQL connection URL (No default; upstream applies its own.) [validate: required]";
    };
    "schema" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "PostgreSQL schema for all TelDrive and River tables (Default: teldrive) [validate: required]";
    };
    "application-name" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "PostgreSQL application name (Default: teldrive-v2) [validate: required]";
    };
    "max-connections" = lib.mkOption {
      type = lib.types.nullOr (lib.types.int);
      default = null;
      description = "Maximum PostgreSQL connections (Default: 25) [validate: gte=1]";
    };
    "min-connections" = lib.mkOption {
      type = lib.types.nullOr (lib.types.int);
      default = null;
      description = "Minimum PostgreSQL connections (Default: 2) [validate: gte=0]";
    };
    "max-connection-idle" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Maximum idle time for a PostgreSQL connection (Default: 5m) [validate: gte=0]";
    };
    "max-connection-life" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Maximum lifetime for a PostgreSQL connection (Default: 30m) [validate: gte=0]";
    };
    "health-check-interval" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "PostgreSQL pool health-check interval (Default: 30s) [validate: gt=0]";
    };
    "connect-timeout" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "PostgreSQL connection timeout (Default: 10s) [validate: gt=0]";
    };
    "auto-migrate-legacy" = lib.mkOption {
      type = lib.types.nullOr (lib.types.bool);
      default = null;
      description = "Automatically migrate a detected TelDrive v1 database during startup (Default: true)";
    };
  };
  "telegram" = {
    "backend" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Telegram backend: remote or filesystem (Default: remote) [validate: oneof=remote filesystem]";
    };
    "local-root" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Filesystem root used by the local Telegram emulator (Default: ./var/local-telegram) [validate: required_if=Backend filesystem]";
    };
    "app-id" = lib.mkOption {
      type = lib.types.nullOr (lib.types.int);
      default = null;
      description = "Telegram application ID (Default: 2496) [validate: required_if=Backend remote,omitempty,gt=0]";
    };
    "app-hash" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Telegram application hash (Default: 8da85b0d5bfe62527e5b244c209159c3) [validate: required_if=Backend remote]";
    };
    "device-model" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Telegram client device model (Default: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0) [validate: required]";
    };
    "system-version" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Telegram client system version (Default: Win32) [validate: required]";
    };
    "app-version" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Telegram client application version (Default: 6.1.4 K) [validate: required]";
    };
    "language-code" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Telegram client language code (Default: en) [validate: required]";
    };
    "system-language-code" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Telegram client system language code (Default: en-US) [validate: required]";
    };
    "language-pack" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Telegram client language pack (Default: webk)";
    };
    "dial-timeout" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Telegram connection timeout (Default: 10s) [validate: gt=0]";
    };
    "reconnect-timeout" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Maximum Telegram reconnect backoff duration (Default: 5m) [validate: gt=0]";
    };
    "max-retries" = lib.mkOption {
      type = lib.types.nullOr (lib.types.int);
      default = null;
      description = "Maximum Telegram transport retry attempts (Default: 10) [validate: gte=0]";
    };
    "rate-limit" = lib.mkOption {
      type = lib.types.nullOr (lib.types.bool);
      default = null;
      description = "Enable Telegram API request rate limiting (Default: true)";
    };
    "rate-interval" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Minimum interval between Telegram API requests (Default: 50ms) [validate: gt=0]";
    };
    "rate-burst" = lib.mkOption {
      type = lib.types.nullOr (lib.types.int);
      default = null;
      description = "Telegram API request burst allowance (Default: 10) [validate: gt=0]";
    };
    "proxy" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "HTTP, HTTPS, or SOCKS5 proxy URL (No default; upstream applies its own.)";
    };
    "mtproxy" = {
      "address" = lib.mkOption {
        type = lib.types.nullOr (lib.types.str);
        default = null;
        description = "MTProto proxy address in host:port form (No default; upstream applies its own.)";
      };
      "secret" = lib.mkOption {
        type = lib.types.nullOr (lib.types.str);
        default = null;
        description = "MTProto proxy secret in hexadecimal form (No default; upstream applies its own.)";
      };
    };
    "client-logging" = lib.mkOption {
      type = lib.types.nullOr (lib.types.bool);
      default = null;
      description = "Enable verbose gotd Telegram client logs through the application logger (Default: false)";
    };
    "upload-threads" = lib.mkOption {
      type = lib.types.nullOr (lib.types.int);
      default = null;
      description = "Concurrent Telegram upload workers (Default: 8) [validate: min=1,max=32]";
    };
    "download-bots" = lib.mkOption {
      type = lib.types.nullOr (lib.types.int);
      default = null;
      description = "Maximum enabled bots used for download rotation; zero uses the authenticated user (Default: 0) [validate: min=0,max=32]";
    };
    "download-client-pool" = lib.mkOption {
      type = lib.types.nullOr (lib.types.bool);
      default = null;
      description = "Keep authenticated Telegram download clients warm between HTTP requests (Default: false)";
    };
    "download-read-buffers" = lib.mkOption {
      type = lib.types.nullOr (lib.types.int);
      default = null;
      description = "Number of prefetched Telegram download chunks buffered in memory per stream (Default: 32) [validate: min=1,max=256]";
    };
    "download-read-parallel" = lib.mkOption {
      type = lib.types.nullOr (lib.types.int);
      default = null;
      description = "Concurrent Telegram chunk fetches per download stream (Default: 4) [validate: min=1,max=32]";
    };
    "randomize-part-names" = lib.mkOption {
      type = lib.types.nullOr (lib.types.bool);
      default = null;
      description = "Randomize Telegram document names (Default: true)";
    };
    "auto-channel-create" = lib.mkOption {
      type = lib.types.nullOr (lib.types.bool);
      default = null;
      description = "Create storage channels automatically (Default: true)";
    };
    "bot-rotation-backend" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Bot rotation backend: memory for single-instance speed or database for cluster-wide coordination (Default: memory) [validate: oneof=memory database]";
    };
    "channel-part-limit" = lib.mkOption {
      type = lib.types.nullOr (lib.types.int);
      default = null;
      description = "Maximum parts stored in one Telegram channel (Default: 500000) [validate: gt=0]";
    };
    "channel-name-prefix" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Prefix for automatically created channels (Default: teldrive) [validate: required]";
    };
  };
  "encryption" = {
    "active-key-version" = lib.mkOption {
      type = lib.types.nullOr (lib.types.int);
      default = null;
      description = "Active server-managed encryption key version for new uploads (Default: 0) [validate: gte=0]";
    };
    "keys" = lib.mkOption {
      type = lib.types.nullOr (lib.types.attrsOf lib.types.str);
      default = null;
      description = "Encryption keys as comma-separated version:key entries (No default; upstream applies its own.)";
    };
  };
  "security" = {
    "signing-key" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "JWT signing key (No default; upstream applies its own.) [validate: required,min=32]";
    };
    "data-key" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Key used to encrypt stored Telegram credentials (No default; upstream applies its own.) [validate: required]";
    };
    "issuer" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "JWT issuer (Default: teldrive-v2) [validate: required]";
    };
    "allowed-users" = lib.mkOption {
      type = lib.types.nullOr (lib.types.listOf lib.types.str);
      default = null;
      description = "Allowed Telegram usernames; empty permits every user (No default; upstream applies its own.)";
    };
    "access-token-ttl" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Access-token lifetime (Default: 15m) [validate: gt=0]";
    };
    "refresh-token-ttl" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Refresh-token lifetime (Default: 720h) [validate: gt=0]";
    };
    "login-flow-ttl" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Telegram login-flow lifetime (Default: 10m) [validate: gt=0]";
    };
  };
  "logging" = {
    "log-level" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Log level: debug, info, warn, or error (Default: info) [validate: oneof=debug info warn error]";
    };
    "log-format" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Log format: json or text (Default: text) [validate: oneof=json text]";
    };
  };
  "events" = {
    "batch-size" = lib.mkOption {
      type = lib.types.nullOr (lib.types.int);
      default = null;
      description = "Maximum events read from PostgreSQL per SSE batch (Default: 100) [validate: min=1,max=1000]";
    };
    "max-connections-per-user" = lib.mkOption {
      type = lib.types.nullOr (lib.types.int);
      default = null;
      description = "Maximum concurrent SSE connections per user on one API instance (Default: 5) [validate: min=1,max=1000]";
    };
    "heartbeat" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "SSE heartbeat interval (Default: 20s) [validate: gt=0]";
    };
    "write-timeout" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Maximum duration for one SSE write and flush (Default: 10s) [validate: gt=0]";
    };
    "ticket-ttl" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Lifetime of browser event stream tickets (Default: 2m) [validate: gt=0]";
    };
    "cleanup-interval" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Expired event stream ticket cleanup interval (Default: 1h) [validate: gt=0]";
    };
    "connect-timeout" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "PostgreSQL event listener connection timeout (Default: 10s) [validate: gt=0]";
    };
    "ping-interval" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "PostgreSQL event listener health-check interval (Default: 5s) [validate: gt=0]";
    };
    "reconnect-min" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Minimum PostgreSQL listener reconnect delay (Default: 100ms) [validate: gt=0]";
    };
    "reconnect-max" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Maximum PostgreSQL listener reconnect delay (Default: 30s) [validate: gt=0]";
    };
  };
  "uploads" = {
    "session-ttl" = lib.mkOption {
      type = lib.types.nullOr (lib.types.str);
      default = null;
      description = "Lifetime of resumable upload sessions (Default: 168h) [validate: gt=0]";
    };
    "hashing-enabled" = lib.mkOption {
      type = lib.types.nullOr (lib.types.bool);
      default = null;
      description = "Compute and store BLAKE3 hashes for uploaded files (Default: true)";
    };
    "local-import-roots" = lib.mkOption {
      type = lib.types.nullOr (lib.types.listOf lib.types.str);
      default = null;
      description = "Absolute server directories allowed as local background-upload sources; empty disables local imports (No default; upstream applies its own.)";
    };
  };
  "jobs" = {
    "run-workers" = lib.mkOption {
      type = lib.types.nullOr (lib.types.bool);
      default = null;
      description = "Run River background job workers in this process (Default: true)";
    };
  };
  "cache" = {
    "memory" = {
      "size" = lib.mkOption {
        type = lib.types.nullOr (lib.types.str);
        default = null;
        description = "Global Ristretto memory cache size (e.g., 5MB, 10MB) (Default: 5MB) [validate: gt=0]";
      };
    };
  };
}
